// Perfectum Produktdatabas V7 — Expert-pitchar
const PRODUCTS=[
// ══ 1. SPOLARVÄTSKA & GLYKOL ══
{id:"spolar",n:"Spolarvätska",cat:"Spolarvätska & Glykol",r:1,e:"💧",c:"#0ea5e9",tags:["åkeri","verkstad","bygg"],box:"2x25L → 1x25L",bonus:"Gängsats 110 delar (M2-M18) värd 3000-3500kr GRATIS vid 2x25L, pris 89→79kr/L",p:"Vi jobbar med Swedhandling i Norrköping — en av Sveriges största tillverkare, de förser halva industrin. 93% aktivhalt alltså rent koncentrat, späds 3-6 gånger beroende på årstid — brukslösning hamnar på 59-69 kr/L vilket är billigast på marknaden. 1L-packet är klassat som ej farligt gods så det kan stå i förråd utan kemikaliepärm, medan 25L-dunken och 205L-fatet kräver UN-märkning. Vi har även en 90% koncentrat som späds 5-6x till en ännu billigare brukslösning — det är den 90% av åkerierna väljer när de räknar kalkylen. Hur mycket kör ni per år, och väljer ni koncentrat eller färdigblandat idag?",sp:["93% aktivhalt","Späds 3-6x","1L: EJ farligt gods"],pr:"59-69kr/L | Kampanj: 79kr/L vid 2x25L",fm:["1L (12/24-pack)","25L dunk","205L fat"],di:[{q:"Koncentrat eller färdigblandad?"},{q:"Hur mycket per år?"},{q:"Glykol?",lk:"glykol"}]},
{id:"glykol",n:"Glykol",cat:"Spolarvätska & Glykol",r:1,e:"🧊",c:"#6366f1",tags:["åkeri","verkstad"],box:"2x25L → 1x25L",p:"93% aktivhalt longlife Klass 3 — håller 5 år i både maskineri och dunk, så du får lager som inte dör på hyllan. Vi har 5 färger eftersom olika fordon kräver olika typer: Blå etylen 69 kr/L är standarden, Röd 69-79 för nyare personbilar, Grön propylen-baserad 79-99 är miljöglykolen (den du helst ska ha), Gul 69-79 för Volvo-specifikationen, och Transparent 79-89 som blandbar när du inte vet vad som finns i systemet. OBS — aldrig blanda färger utan kontroll, då kan du få klumpar och proppar i kylaren. Vilken färg kör ni på fordonen, och behöver ni också för maskiner?",sp:["93% aktivhalt","Klass 3 longlife","5 år","5 färger"],pr:"69-99 kr/L beroende färg",fm:["4L","20L","25L","205L fat"],di:[{q:"Vilken FÄRG?"},{q:"Maskiner eller fordon?"},{q:"AD-Blue?",lk:"adblue"}]},
{id:"adblue",n:"AD-Blue",cat:"Spolarvätska & Glykol",r:1,e:"🔵",c:"#3b82f6",tags:["åkeri"],box:"205L → 25L",p:"AD-Blue är lagkrav för alla Euro 6-dieselmotorer sedan 2014, så kör ni lastbilar eller tyngre entreprenadmaskiner så MÅSTE ni ha det — annars går motorn i nödläge. Det är en urealösning på 32,5% som sprutas in i avgaserna och bryter ner NOx till kväve och vatten via SCR-katalysatorn. Förbrukningen ligger på ca 3-5% av dieseln, så kör ni 10 000L diesel i månaden drar ni 300-500L AD-Blue. Vi jobbar med Swedhandling, ISO 22241-certifierad kvalité så det funkar i alla system — Volvo, Scania, Mercedes, MAN, DAF, alla. Volymrabatt från 10L upp till 1000L IBC-tank, och ju större du kör desto billigare per liter. Hur mycket diesel tankar ni per månad så räknar jag ut behovet?",sp:["ISO 22241","SCR","Euro 6 lagkrav"],pr:"Volymbaserat",fm:["10L","25L","205L","1000L IBC"],di:[{q:"Hur mycket i månaden?"}]},

// ══ 2. SPRAYER & AEROSOLER ══
{id:"sprayer",n:"Sprayer — Översikt",cat:"Sprayer",r:2,e:"🧴",c:"#ef4444",tags:["verkstad","svetsare","bygg"],box:"24st blandlåda → 12st dussin",bonus:"Paket 24st + kylsnyckelsats = 2995kr. Styckpris från 12st: 129kr",p:"Aerosoler på burk är konsumtionsvaror som alltid går åt — ingen verkstad klarar sig utan. Det här är Tony Rikardsson-serien, 149 kr/burk hos mig (159 ut över disk) och Brakeclean är 60 spänn billigare just för att den går åt mest. 14 olika typer så vi täcker i princip allt en verkstad behöver. Jäkla tryck i flaskorna, massa teflon och aktiva ämnen — inget av det där utspädda skräpet du får på grossist. Kunden innan dig tog Brakeclean, Rostlösare och Allround-PTFE — vilka tre använder ni mest?",sp:["Tony Rikardsson","149-159kr/burk","Brakeclean billigare","14 typer"],pr:"149-159kr/burk | Paket 24st: 2995kr",fm:["Enstaka","Dussin 12","Blandlåda 24"],di:[{q:"Brakeclean?",lk:"brake"},{q:"Rostlösare?",lk:"rost"},{q:"Allround/VD40?",lk:"allround"},{q:"Kedjespray?",lk:"kedja"},{q:"Krypfett?",lk:"kryp"},{q:"Kylspray?",lk:"kyl"},{q:"Teflon?",lk:"tefl"},{q:"Citrus A?",lk:"citr"},{q:"Glasrent?",lk:"glas"},{q:"Multiskum?",lk:"multi"},{q:"Kopparspray?",lk:"kopp"},{q:"Kontaktspray?",lk:"kont"}]},
{id:"brake",n:"Brakeclean/Maskinrent",cat:"Sprayer",r:2,e:"🔵",c:"#3b82f6",tags:["verkstad","svetsare"],p:"Brakeclean är den absolut mest sålda sprayen vi har — inget fordon eller maskinverkstad klarar sig utan. Snabbverkande fettlösare baserad på aceton/heptan som löser olja, bromsdamm, vägsmuts och gamla fettrester från bromsskivor, hjulhus och chassi — allt utan att lämna några rester. Vår är 60 spänn billigare än övriga sprayer i sortimentet, just för att den går åt så extremt mycket — vi vill att du alltid ska ha den i hyllan istället för att få slut. Högt tryck, snabbtorkande — sprut, vänta 30 sekunder, torka av. Hur många burkar går det hos er i månaden?",sp:["Fettlösare","Billigaste","Snabbtorkande"],pr:"~89-99kr",fm:["Enstaka","Dussin"],di:[{q:"Hur många i månaden?"}],art:"000000"},
{id:"rost",n:"Rostlösare",cat:"Sprayer",r:2,e:"🟠",c:"#f97316",tags:["verkstad"],p:"Rostlösare som verkligen penetrerar — den där fastrostade muttern som suttit i 10 år går loss på minuter. Kryper in i minsta gängan via kapilläreffekt och löser rosten underifrån, istället för att bara lägga sig som en film på toppen. Tar också gnissel i gångjärn, låskolvar, wirefästen och dörrupphängningar — allt som börjat tjura av väta eller ålder. Efter behandling sitter det en smörjfilm kvar så det inte kärvar nästa gång. En burk räcker längre än man tror — men när du behöver den så behöver du den JU.",sp:["Löser rost","Kapillärverkan","Smörjfilm kvar"],pr:"149kr",fm:["Enstaka","Dussin"],di:[],art:"942100"},
{id:"allround",n:"Allroundspray PTFE",cat:"Sprayer",r:2,e:"🟢",c:"#10b981",tags:["verkstad"],p:"Vår Allroundspray PTFE är som VD40 fast bättre — och jag säger det med pondus. Skillnaden är tillsatsen av PTFE (Teflon) som ger riktigt smörjning där vanliga universalsprayer bara fuktar ytan. Trycker ut vatten, skyddar mot korrosion, smörjer gångjärn, lås, skenor och kedjedrev — samma flaska till allt. Starkt tryck i förpackningen, sprider sig jämnt och torkar inte ut lika fort som vanlig allround. Kör ni VD40 idag så är det här en ren uppgradering — samma pris, betydligt bättre prestanda. Hur många burkar går åt per månad?",sp:["Motsvarar VD40","PTFE Teflon","Vattenutträngande"],pr:"149kr",fm:["Enstaka","Dussin"],di:[{q:"Kör ni VD40?"}],art:"250200"},
{id:"kedja",n:"Kedjespray",cat:"Sprayer",r:2,e:"⛓️",c:"#8b5cf6",tags:["skog"],p:"Kedjespray med extrem vidhäftning — den sätter sig där den ska och stannar. Penetrerar först in i kedjans leder och länkar, sen bygger den upp en seg hartsfilm som inte slungas av även vid högt varvtal. Funkar lika bra på motorsågar som industrikedjor, transportkedjor och cykelkedjor. Vattenavvisande så den håller i regn, snö och tvättvatten. Kör ni skogsmaskin, motorsåg eller industrikedja — för då är det olika dosering.",sp:["Vidhäftning","Vattenavvisande","Håller i varvtal"],pr:"149kr",fm:["Enstaka"],di:[],art:"070106"},
{id:"kryp",n:"Krypfett/Mos2",cat:"Sprayer",r:2,e:"💛",c:"#eab308",tags:["verkstad"],p:"Krypfett med MoS2 (molybdendisulfid) — de där svarta partiklarna som lägger sig som ett hårt smörjande skikt under belastning. Kryper in i springor via kapillärverkan så du sprutar utanför och den hittar vägen in till gängor och glidytor som är svåråtkomliga. Mellanting mellan ett klassiskt smörjfett och en allroundspray — bättre än båda på rätt ställe. MoS2 är samma grundämne som används i militärfordon och flyg just för att den håller även under extremt tryck och temperatur. Perfekt på bultar som ska lossas senare utan att fastna.",sp:["MoS2 molybdendisulfid","Kryper in","Högtryck"],pr:"149kr",fm:["Enstaka"],di:[],art:"240200"},
{id:"kyl",n:"Kylspray/Skärspray",cat:"Sprayer",r:2,e:"❄️",c:"#06b6d4",tags:["verkstad"],p:"Kylspray (skärspray) som förlänger livslängden på borr och skärverktyg rejält — vi pratar 2-3x längre hållbarhet på dyra kvalitetsborr. Kyler ner skäreggen, minskar friktion och spolar bort spånor i samma rörelse. Extra viktigt när du borrar i rostfritt, titan eller härdat stål där värmen snabbt glödgar ut härdningen i spetsen. Ett sprut på skäret mellan drag räcker, du slösar inte. Hur mycket borrar och svarvar ni, och vilka material är det mestadels?",sp:["Kyler verktyg","Förlänger livslängd 2-3x","Rostfritt/härdat"],pr:"149kr",fm:["Enstaka"],di:[],art:"72012"},
{id:"tefl",n:"Teflonspray PTFE",cat:"Sprayer",r:2,e:"⚪",c:"#64748b",tags:["verkstad"],p:"Teflonspray med rent PTFE-film som ger friktionskoefficient ner mot 0,04 — det är i princip halkigt som is. Lägger sig som ett mikrotunt skikt på rörliga delar: skenor, lager, gångjärn, styrbultar och glidytor. Torkar snabbt, fläckar inte och samlar inte damm som oljor alltid gör — där du inte vill ha kladd är detta bästa valet. Perfekt för skjutdörrar, teleskopiska armar, verktygsvagnar. Vad smörjer ni på rörliga delar idag?",sp:["PTFE","Friktionskoeff 0,04","Samlar inte damm"],pr:"149kr",fm:["Enstaka"],di:[],art:"520800"},
{id:"citr",n:"Citrus A",cat:"Sprayer",r:2,e:"🍊",c:"#f59e0b",tags:["verkstad"],p:"Citrus A med d-limonen — samma naturliga ämne som finns i apelsinskal och som löser klister och lim som smör i solen. Tar bort klisterrester, dekalrester, tuggummi, tjära, kåda och gamla tejprester utan att skada lack, plast eller gummi. Fantastisk citrusdoft som faktiskt gör verkstaden trevligare att vistas i — kunderna kommenterar. Perfekt på kassor efter streckkoder, begagnade bilar med gamla dekaler, efter renovering när du ska ta bort maskeringstejp. Har ni problem med klisterrester någonstans idag?",sp:["D-limonen","Lack-/plastsäker","Klister"],pr:"149kr",fm:["Enstaka"],di:[],art:"550200"},
{id:"glas",n:"Glasrent",cat:"Sprayer",r:2,e:"🪟",c:"#0ea5e9",tags:["verkstad"],p:"Glasrent har fått en rejäl uppgradering senaste året — nu absolut strimfri även på större ytor. Ammoniakfri formula som inte anfräter plast- eller listgummi som vissa fönsterputsar gör med tiden. Funkar lika bra på bilrutor, butiksfönster, speglar och glasade dörrar. Skummar upp, bryter ner fett, nikotin och vägfilm, torkar bort rent utan att lämna film. Kör ni personbilsverkstad så säljer den sig själv vid reception — kunderna frågar efter den.",sp:["Ammoniakfri","Strimfri","Plast/gummi-säker"],pr:"149kr",fm:["Enstaka"],di:[],art:"340100"},
{id:"multi",n:"Multiskum",cat:"Sprayer",r:2,e:"🫧",c:"#a855f7",tags:["åkeri"],p:"Multiskum för interiör — bilar, lastbilshytter, entreprenadmaskiner. Skummar upp fint och bryter ner fett, svett och smuts från textil, plast, läderinredning och gummidetaljer utan att skada materialet. Torkas bort med en fuktig mikrofibertrasa — inget vatten behövs, så perfekt för hytter där du inte kan spola. Ljusa säten, ratt, rattstång, dörrpaneler — allt blir fräscht igen. Kör ni tvätt på lastbilshytterna så säljer den sig själv på chaufförerna.",sp:["Interiör","Textil/plast/läder","Ingen spolning"],pr:"149kr",fm:["Enstaka"],di:[],art:"101100"},
{id:"kopp",n:"Kopparspray",cat:"Sprayer",r:2,e:"🟤",c:"#b45309",tags:["verkstad"],p:"Kopparspray (kopparpasta) som klarar upp till 1100°C — avgasgrenrör, bromssadelsbultar, lambdasondens gängor, tändstiftsgängor, allt som blir riktigt varmt. Fungerar som anti-seize så när du ska lossa muttern 3 år senare går den loss utan att gänga av sig. Tunt skikt räcker — en burk räcker länge om man inte överdriver. OBS: använd INTE på aluminium, där vill du ha keramikpastan istället för att undvika galvanisk korrosion. Hur ofta byter ni avgaskomponenter?",sp:["1100°C","Anti-seize","Ej på alu"],pr:"149kr",fm:["Enstaka"],di:[],art:"060100"},
{id:"kont",n:"Kontaktspray",cat:"Sprayer",r:2,e:"⚡",c:"#eab308",tags:["verkstad"],p:"Kontaktspray för el — trycker ut fukt från elkontakter, säkringshållare och kopplingar, och lämnar sen en torr smörjande film som skyddar mot korrosion. Löser också oxid från kopparkontakter så ledningen får perfekt kontakt igen. Godkänd på all elektronik inkl känslig styrelektronik, så du kan spraya på fordonselektronik utan rädsla. Perfekt vid fordonsfel som kommer tillbaka — 70% av så kallade elfel är i verkligheten dålig kontakt. Jobbar ni mycket med elfelsökning?",sp:["Fuktutträngande","Löser oxid","Elektroniksäker"],pr:"149kr",fm:["Enstaka"],di:[],art:"4148100"},
{id:"kera",n:"Keramikpasta",cat:"Sprayer",r:2,e:"⚪",c:"#d1d5db",tags:["verkstad"],p:"Keramikpasta med keramiska partiklar som klarar upp till 1400°C och är 100% neutral mot aluminium — det är hela poängen. Använder du kopparpasta på aluminiumavgasdelar så får du galvanisk korrosion (elektrolys) på kort tid som fräter sönder gängan. Keramiken reagerar inte med någonting. Samma anti-seize funktion som kopparpastan, gängor går loss år senare. Perfekt på moderna bilar där mycket är alu — motorfästen, avgasgrenrör, mc-avgassystem.",sp:["1400°C","Aluminium-säker","Ingen galvanisk reaktion"],pr:"149kr",fm:["Enstaka"],di:[],art:"200792"},
{id:"tjar",n:"Tjärspray",cat:"Sprayer",r:2,e:"⬛",c:"#1e293b",tags:["åkeri"],p:"Tjärspray löser asfalt, tjära, oljefläckar och bitumen från lack utan att skada klarlacken — vi pratar mycket skonsammare än de gamla tjärborttagarna som också åt upp lacken över tid. Fordonslack-säker, testad på modern vattenbaserad lack. Perfekt efter sommarkörning när tjärstänk fastnar i flanker och stötfångare, eller efter väg-arbeten när asfaltrester hamnar under bilarna. Sprut på, vänta 2 minuter, torka bort med mikrofiber. Kör ni många lastbilar eller bilar med mycket motorvägskörning?",sp:["Lack-säker","Löser bitumen","Modern lack"],pr:"149kr",fm:["Enstaka"],di:[],art:"70022"},

// ══ 3. AVFETTNING & KEM ══
{id:"bamse",n:"Bamse Alkalisk Special",cat:"Avfettning & Kem",r:3,e:"🐻",c:"#dc2626",tags:["verkstad","åkeri","bygg"],box:"205L fat → 25L dunk → 5L",bonus:"108-delars verktygsväska (2000kr) + gottepåse gratis vid köp",p:"Bamse är vår mest sålda produkt på 30 år — det säger en del. 87% aktivhalt där andra alkaliska ligger på 18-23% — kör du en grossist idag så är det vatten med lite kem. Lutbaserad och späds 50 gånger, så brukslösningen hamnar på 2-4 kr/L — absolut billigaste på marknaden när du räknar verklig kostnad. Kundlistan säger allt: Modo Skog, Assi Domän, Stockholms kommun, kriminalvården och 6000 åkerier i Sverige. Tar ALLT inklusive miljöoljor och fastbrända oljor. OBS — koncentrat tar lacken så var försiktig med spilldroppar. Finns med på kemikaliesvepets vita lista, miljövänlig utan lösningsmedel eller petroleum. Funkar i högtryck och handspruta. Vad kör ni på avfettning idag?",sp:["87% aktivhalt","Lutbaserad","Späds 50x","Brukslösning 2-4kr/L","30 år på marknaden","Miljövänlig, vita listan"],pr:"119-149kr/L | Ord: 99,90/fat",fm:["5L","25L dunk","205L fat"],di:[{q:"Alkaliskt eller kall?"},{q:"Prickbort?",lk:"prickbort"},{q:"Skumglans/Foamer?",lk:"skumglans"}]},
{id:"prickbort",n:"Prickbort Kallavfettning",cat:"Avfettning & Kem",r:3,e:"✨",c:"#e11d48",tags:["verkstad","åkeri"],box:"2x25L → 1x25L",p:"Perfectums starkaste av 3 Prickbort-varianter — högtrycksrengöring för de riktigt svårlösliga oljeföroreningarna: asfalt, vägsmuts, gödsel, kåda, flygrost. Till skillnad från de flesta konkurrenter så späds den INTE — rakt i sprutan och kör, det sparar tid och ingen blandningskrångel. Sprayas på torr yta, verkar i 2 minuter, sköljs av med högtryckstvätt. Svensktillverkad och biologiskt nedbrytbar, godkänd på vita listan. Rengör ni lastbilar, maskiner eller bilar på egen anläggning?",sp:["Späds INTE","Starkaste","Svensktillverkad","Biologiskt nedbrytbar"],pr:"119kr/L (25L)",fm:["25L dunk"],di:[],art:"197"},
{id:"skumglans",n:"Skumglanschampo/Foamer",cat:"Avfettning & Kem",r:3,e:"🫧",c:"#0891b2",tags:["åkeri","verkstad"],box:"25L → 5L",p:"Skumglanschampo aka Foamer — tänk grädtårta på maskinen! 2-i-1 lösning som både rengör och bilvårdar i ett enda drag. Appliceras via skumlans eller kemiblandare på högtrycktvätten — maskinen blir täckt i ett tjockt krämigt skum som bryter ner smutsen medan vax-komponenten samtidigt bygger en skyddsfilm. Spola av, och ytan dammar sedan av snabbare i veckor framåt. 149 kr/L låter högt tills du räknar att det ersätter både schampo och vaxning separat. Har ni Foamer-skumlansar på tvätthallen idag?",sp:["2-i-1","Foamlancer/högtryck","Skyddsfilm","149kr/L"],pr:"149kr/L",fm:["5L","25L"],di:[{q:"Har ni foamer?"}]},
{id:"algfasad",n:"Alg & Fasadtvätt",cat:"Avfettning & Kem",r:3,e:"🏠",c:"#059669",tags:["bygg"],box:"25L",p:"Vår Alg & Fasadtvätt är Sveriges billigaste sätt att rengöra fastigheter från grön och svart hinna. Späds 10 gånger = brukslösning på 16,90 kr/L — hitta det någon annanstans! Tar alger, mögel och lav på fasader, plasttak, utemöbler, båtbotten och stuprännor. Biologiskt nedbrytbar och behöver INTE spolas — regnet sköter det åt dig över närmaste veckorna. Håller rent i 2 år efter en behandling. Har ni fastighetsförvaltning eller hus där det alltid kommer tillbaka grön hinna på norrsidan?",sp:["Späds 10x","16,90kr/L brukslösning","Behöver ej spolas","2 år verkan"],pr:"~169kr/L",fm:["25L"],di:[{q:"Fastigheter med alger/mögel?"}]},
{id:"vegavfett",n:"Veg-Avfettning Special",cat:"Avfettning & Kem",r:3,e:"🌿",c:"#16a34a",tags:["verkstad"],p:"Veg-Avfettning Special — helt vegetabilisk bas istället för petroleum, tillverkad i samma svenska kemfabrik i 25 år. pH 12,5 så det sparkar riktigt bra, men betydligt hudvänligare än lutbaserat vilket personalen märker direkt. Blandningsförhållande 1:5, absolut klassiker till fordonstvätt, maskinavfettning och verkstadsgolv. Miljöfördelen är enorm jämfört med petroleumbaserat — grönt tänk som kunder gillar att se i hållbarhetsrapporten och som hjälper vid upphandlingar. GPS-vakt värd 2995 kr ingår som bonus.",sp:["Vegetabilisk","pH 12,5","Svensk fabrik 25 år","Hudvänlig"],pr:"Kontakta",fm:["4x5L kartong"],bonus:"GPS-vakt värd 2995kr",di:[]},
{id:"vaxschampo",n:"Vaxschampo",cat:"Avfettning & Kem",r:3,e:"🚗",c:"#0ea5e9",tags:["åkeri"],p:"Vaxschampo som bygger en vaxemulsion över karossen vid tvätt — skyddar mot vägsalt, diesel, fett och industriföroreningar i samma arbetsmoment. Efter tvätten sitter en tunn skyddsfilm kvar som gör att nästa tvätt går snabbare och rostangreppen minskar rejält. pH 10, skonsam mot både lack och plastdetaljer. Kör ni åkeri eller busstrafik så ser ni skillnaden direkt — bilarna ser nyare ut betydligt längre och håller färgen bättre än konkurrenternas. Hur ofta tvättar ni fordonsflottan?",sp:["Vaxemulsion","Skyddsfilm","pH 10","Rostskydd"],pr:"Kontakta",fm:["5L"],di:[],art:"513"},
{id:"handrent",n:"Handrent Aloe Vera",cat:"Avfettning & Kem",r:3,e:"🤲",c:"#10b981",tags:["verkstad"],p:"Handrent med aloe vera — tar bort diesel, olja, fett, lim och grafit helt utan vatten. Fantastisk citrusdoft istället för den typiska kemilukten, och aloe veran gör att huden inte torkas ut som hos vanliga hårda handrengöringar med pimpsten. Perfekt ute på projekt där det inte finns vatten, eller vid slutet av dagen innan man åker hem. Finns i 1,5L, 2,7L och 4,5L pumpflaska — verkstaden borde ha den stora vid handfatet. Hur många är ni som jobbar med olja dagligen?",sp:["Utan vatten","Aloe vera","Citrusdoft","Hudvänlig"],pr:"~12kr",fm:["1.5L","2.7L","4.5L"],di:[],art:"149"},

// ══ 4. HANDSKAR ══
{id:"handskar",n:"Handskar — Översikt",cat:"Handskar",r:4,e:"🧤",c:"#2563eb",tags:["verkstad","svetsare","bygg","åkeri","skog"],box:"2 dussin (24 par) → 1 dussin (12 par)",p:"Något som alltid går åt — man kan inte gå runt naken, som sagt Börje. Tunn montage? Nitril? Getskinn? Oljiga miljöer eller vanlig montering? Vi har 8 modeller som täcker allt från precisions-montering till skärskydd klass C och vintervatten. Social proof: 69 000 par sålda 2024, det är inte bara prat. Vilka handskar kör ni mest av idag, och vad är största problemet — att de slits ut, att de inte passar, eller att de är för dyra?",sp:["8 modeller","Stl 6-12","Från 49kr/st","69000 par sålda 2024"],pr:"49-189kr/st",fm:["Styckvis","Dussin 12","Kartong 24"],di:[{q:"Tunn montage/nitril?",lk:"ergotec"},{q:"Oljiga/våta miljöer?",lk:"aquaguard"},{q:"Vinterhandskar getskinn?",lk:"ducavinter"},{q:"Skärskydd?",lk:"foamcut"},{q:"Svetshandskar?",lk:"svetshandske"},{q:"Premium allround?",lk:"perfhandsken"},{q:"Sommar precision?",lk:"ducasommar"}]},
{id:"ergotec",n:"Ergo Tec (Tunn montage)",cat:"Handskar",r:4,e:"✋",c:"#2563eb",tags:["verkstad","bygg"],box:"24 par → 12 par",p:"Ergo Tec — nitril undertill, tunn tygväv upptill, 49 kr/st. PU+Nitril blandning på ovansidan, sömnlös stickad stomme, helt siliconfri, kromfri och nickelfri så ingen allergirisk. Tvättbar, slitstark, håller dussintals tvättar utan att förlora grepp. Jag brukar säga: du kan lyfta en 50-öring med dessa — så tunn känsla har du. Finns stl 6-12 så alla passar. Hur många är ni som använder montagehandskar, och vilken storlek kör du?",sp:["PU+Nitril","Sömnlös stickad","Siliconfri/kromfri/nickelfri","Tvättbar","49kr/st"],pr:"49kr/st",fm:["Stl 6-12"],di:[{q:"Storlek?"},{q:"Hur många är ni?"}],art:"ADF-874"},
{id:"aquaguard",n:"Aquaguard Thermo (Vinter/Olja)",cat:"Handskar",r:4,e:"💦",c:"#0284c7",tags:["verkstad","åkeri"],box:"24→12",p:"Aquaguard Thermo — 100% vattentät tack vare TRIPPELDOPPAD nitrilbeläggning, vilket är unikt på marknaden. De flesta vattentäta är singel-doppade och läcker efter några veckor. Sandygrip-textur på handflatan ger grepp i olja, blöta ytor och på stålrör. Vinterfodrad med akrylfoder som isolerar utan att bli klumpig — du får extremt tunn känsla trots att den är varm, och den är riktigt elastisk. Jobbar du ute i slask och olja på vintern så är det här räddningen.",sp:["Trippeldoppad (unikt)","100% vattentät","Sandygrip","Akrylfoder","Tunn trots vinter"],pr:"99-119kr/st",fm:["Stl 8-12"],di:[{q:"Oljiga miljöer?"},{q:"Vattentät?"}],art:"HV-LKX970"},
{id:"ducavinter",n:"Perfectum Duca Vinter",cat:"Handskar",r:4,e:"❄️",c:"#1d4ed8",tags:["verkstad","bygg"],box:"24→12",p:"Perfectum Duca Vinter — äkta getskinn utvändigt och fleece vinterfoder invändigt. Getskinn är slitstarkare än kohud men fortfarande mjukt, så du får precision trots vinterskyddet. Fingertopparna är förstärkta där slitaget alltid kommer först, och handsken går lätt på och av även med kalla händer. Finns också som ofodrad sommarvariant med samma design. Stl 7-11 vinter, 7-12 sommar. Vad använder folket hos er för handskar på vintern idag?",sp:["Äkta getskinn","Fleece","Fingertopps förstärkt","Lätt på/av"],pr:"99-149kr/st",fm:["Stl 7-11(vinter) 7-12(sommar)"],di:[{q:"Vinter eller sommar?"}],art:"6900(V)/7900(S)"},
{id:"ducasommar",n:"Perfectum Duca Sommar",cat:"Handskar",r:4,e:"☀️",c:"#f59e0b",tags:["verkstad"],p:"Duca Sommar — samma getskinn och design som vintervarianten fast utan fleece-foder, så du får mycket smidigare grepp och bättre känsla. Getskinn andas betydligt bättre än kohud, så händerna svettas inte i varmen vilket är stort problem på sommaren med vanliga arbetshandskar. Precision nog att hantera bultar och små skruvar utan att dra av sig handsken. Förstärkt tumme och pekfinger där slitaget alltid kommer. Perfekt för bygg, verkstad, montering — vår och sommar. Hur ligger ni till med sommarhandskar idag?",sp:["Getskinn","Ofodrad","Andningsaktiv","Förstärkt tumme/pekfinger"],pr:"Kontakta",fm:["Stl 7-12"],di:[],art:"7900"},
{id:"perfhandsken",n:"Perfectum Handsken (Brand Glove)",cat:"Handskar",r:4,e:"🏆",c:"#f97316",tags:["verkstad","bygg","svetsare"],box:"24→12",bonus:"Mest uppskattade handsken alla kategorier",p:"Perfectum Handsken — vår absoluta flaggskepps-handske, mest uppskattade i alla kategorier. Riktigt mockaläder på insidan som andas och sitter som en smäck. Förstärkt tumme och pekfinger där slitaget kommer, spandex-stickad baksida med komfortdyna som ger vibrationsdämpning — du märker skillnaden efter en timme med slagborr. Air vent-hål för att andas ut. Funkar för alla branscher: verkstad, bygg, lätt svets. Sommarversion 149 kr, vintervariant 189 kr. Hur många är ni som slår och borrar mycket?",sp:["Mockaläder","Vibrationsdämpning","Air vent","Förstärkt tumme/pekfinger","Allround"],pr:"Sommar 149kr | Vinter 189kr",fm:["Sommar+Vinter"],di:[{q:"Storlek?"},{q:"Hur många är ni?"}]},
{id:"foamcut",n:"Foamcut C (Skärskydd)",cat:"Handskar",r:4,e:"🔪",c:"#4f46e5",tags:["verkstad"],box:"24→12",p:"Foamcut C — skärskydd nivå C enligt EN388: 4X42C, vilket betyder högsta vardagliga nivån (A-F skala, C är där arbetsmiljö kräver). Stickat i HPPE (högpresterande polyetylen) blandat med ståltråd, doppad i nitril på handflatan så den är både skärbeständig OCH oljebeständig OCH vattenresistent. 2-i-1 montagehandske + skärskydd — du slipper byta handskar när du går från montage till hantering av plåt. Helt ny på marknaden, smidig nog att passa alla. Jobbar ni med plåt, glas eller vassa kanter?",sp:["Nivå C (EN388 4X42C)","HPPE+stål","2-i-1","Oljebeständig","Nylanserad"],pr:"79-129kr/st",fm:["Stl 6-12 (12/120)"],di:[{q:"Kräver ni skärskydd?"}],art:"HV-NJE3231"},
{id:"svetshandske",n:"Svetshandskar",cat:"Handskar",r:4,e:"🔥",c:"#b91c1c",tags:["svetsare"],p:"Svetshandskar som faktiskt håller sig mjuka över tid — det är hela poängen. Billiga svetshandskar är bra en vecka, sen blir de stenhårda efter första riktiga användningen när svetten och värmen gjort sitt, och de åker i soptunnan. Våra är oxidbehandlat mocka med bomullsfoder som isolerar utan att förlora smidighet i fingrarna. Funkar lika bra för TIG som MIG och MMA — du behöver inte ha tre olika par i verkstaden. Hur många svetsare är ni, och vilken process kör de mest?",sp:["Mjuka över tid","Oxidbehandlat mocka","TIG/MIG/MMA","Bomullsfoder"],pr:"Kontakta",fm:["Styckvis"],di:[]},

// ══ 5. KAP & SLIP ══
{id:"kapskivor",n:"Kapskivor Perfectum Premium",cat:"Kap & Slip",r:5,e:"⚙️",c:"#a855f7",tags:["verkstad","svetsare","bygg"],box:"100st (2 lådor) → 50st",bonus:"25% rabatt: 49→34,95. FLEX 125 vinkelslip (1700kr) vid 2 lådor. Paket 4995:-. Bara ~10 kvar!",p:"Perfectum Premium kommer från Rhodius i Tyskland — samma fabrik som gör världsrankade kapskivor. Motsvarar Tyrolit XGTS (som vann världsbäst 2022) men är 20-40% bättre i livslängd och samma pris som 2021 trots förbättrad 2025-formula. Nyckeln är dubbel ythärdning — skivan vobbar eller splittras inte ens vid sneda kap. Hydroteck-behandling gör att den tål vatten och väte utan att försvagas som vanliga skivor gör efter lagerhållning. Högkvalitativ korund (aluminiumoxid) bunden i fenol-harts med 2 glasdukslager för säkerhet. 49 kr/st ordpris, 34,95 i kampanj. Jag har plöjt igenom ett kylskåp med en enda skiva — de tål mer än folk tror. Kör ni 125 eller 230, och hur går det åt idag?",sp:["20-40% längre vs Tyrolit","Hydroteck","Dubbel ythärdning","Förbättrad 2025","Samma pris som 2021"],pr:"49kr/st → 34,95 rabatt | Paket 4995:- inkl FLEX",fm:["125x0.8/1.0/1.5","180x1.5","230x1.9/2.5","50st/packe"],di:[{q:"125 eller 230?"},{q:"Slip?",lk:"slipskivor"},{q:"Lamell?",lk:"lamell"},{q:"Vision Pro?",lk:"visionpro"}],art:"6912510/515/6918015/6923019"},
{id:"slipskivor",n:"Slipskivor Ferox",cat:"Kap & Slip",r:5,e:"💿",c:"#9333ea",tags:["verkstad"],p:"Slipskivor Ferox — tysk tillverkning, samma teknologi som Bosch använder i sin premium-serie. Korund i kombination med bindemedel som är optimerat för metall, extra viktigt för rostfritt där man måste undvika värmeskador som ger regnbågsanlöpning. 125x7 och 180x7, 7 mm tjocklek för verklig slipning inte bara polering. Jämn finish utan att skivan glöder rött eller bränner materialet. Jobbar ni mycket med svets-förslipning så är det här daglig-skivan hos er.",sp:["Ferox tysk","Korund","Rostfritt-säker","Jämn finish"],pr:"49kr/st",fm:["125x7.0","180x7.0","230x7.0"],di:[],art:"200451/442/466"},
{id:"lamell",n:"Lamellskivor",cat:"Kap & Slip",r:5,e:"🌀",c:"#7c3aed",tags:["verkstad"],p:"Lamellskivor i P40, P60 och P80 — allt från grovjobb till finish i samma skivtyp. P40 för att ta bort svetsfogar och rostkanter, P60 för utjämning efter grovslipning, P80 för finish innan lackering eller slutgiltig yta. Finns både 125 och 180 mm. Fiberpapperslameller i zirkonium-korund som roterar fram nytt skärkorn kontinuerligt — därför jämn slipning utan att glöda eller fastna i materialet som fasta skivor gör. En låda håller länge om du väljer rätt grovlek per jobb. Vad är vanligast för er — grov eller fin?",sp:["P40/P60/P80","Zirkonium-korund","Glöder ej","Självskärpande"],pr:"Kontakta",fm:["125/180"],di:[],art:"204015/018/021"},
{id:"visionpro",n:"Vision Pro Cool (Premium Lamell)",cat:"Kap & Slip",r:5,e:"🌟",c:"#eab308",tags:["verkstad","svetsare"],box:"10st → 5st",bonus:"Ord 279→189kr (32% rabatt). Ferox borrsats värd 3300kr.",p:"Vision Pro Cool — FÖRSTA I SVERIGE med denna design, vilket är stor grej. Flygplanspropeller-inspirerad konstruktion med 3 stora mellanrum mellan lamellsektionerna som ger dig klar sikt på arbetsytan under slipningen (vanliga lameller blockerar sikten helt) OCH kylande luftströmning som sänker yttemperaturen. Perfekt på rostfritt och aluminium där du annars får värme som förstör materialet eller deformerar tunnplåt. Fastnar INTE i kanter som traditionella lameller gör. Ord 279 kr, nu 189 kr — 32% rabatt. Jobbar ni mycket med rostfritt eller alu?",sp:["Första i Sverige","Flygplanspropeller","Kylande slipning","Rostfritt/alu","Klar sikt"],pr:"189kr/st (ord 279, 32% rabatt)",fm:["P40/P60/P80"],di:[{q:"Rostfritt/alu?"}]},

// ══ 6. SMÖRJFETT ══
{id:"smorjfett",n:"Smörjfett LX-Polar",cat:"Smörjfett",r:6,e:"🔧",c:"#f97316",tags:["verkstad"],box:"2 lådor (50 tuber) → 1 låda (25)",bonus:"Vid 2 lådor: GRATIS batterispruta 690 bar (4000-6000kr). 340000 sålda/år. Bransch 140-190kr → Perfectum 89kr.",p:"Smörjfett LX-Polar är EP2 litiumkomplex utvecklat för nordisk marknad — testat i USA 2010 och blev snabbt standard. Pumpbarhet ner till -33°C där konkurrenterna stannar vid -20°C, så ditt fett funkar även i januari på släpvagnsbromsar. Droppunkt 260°C vilket är mer än dubbelt mot vanligt fett (100-120°C), och viskositet 220 centistoke jämfört med konkurrentens 50 cst — fettet stannar kvar där det ska även under belastning. Lube Shuttle-tuber med skruvgänga är helt kladdfria, slipper du det där klassiska fettet på händerna vid byte. Vi representerade Castrol förut — detta är en helt annan nivå i test efter test. 340 000 tuber sålda senaste året, det säger något. Bransch ligger på 140-190 kr per tub, vi tar 89 kr. Vilken fettspruta har ni — vanligt lock eller skruvgängat?",sp:["EP2 litiumkomplex","-33°C pumpbarhet","260°C droppunkt","220 cst","340000 sålda/år","Lube Shuttle"],pr:"89kr/tub (bransch 140-190) | Maxi 99kr",fm:["LX 25 tuber","Maxi 50","Hugo Eff 0002 (skruv)"],di:[{q:"Vanligt/skruvgängat lock?"},{q:"Fettspruta?",lk:"fettspruta"}],art:"Hugo Eff 0002"},
{id:"fettspruta",n:"Fettspruta Batteri 690 bar",cat:"Smörjfett",r:6,e:"💉",c:"#ea580c",tags:["verkstad"],p:"Batterispruta med 690 bar maxtryck — normalt ligger handsprutor på 450 bar, så den här pressar igenom smutsiga och packade nipplar som andra bara stannar vid. 100 gram fett per minut i flödeshastighet, batteridriven så du slipper pumpa manuellt vilket sparar axeln efter en hel dags smörjning på entreprenadmaskin. Tar Lube Shuttle-patroner (kladdfria, skruva fast) eller klassiska 400 g tuber. Jobbar du med åkeri eller entreprenad där nipplarna ofta är rostiga och fulla av gammalt fett så är skillnaden enorm. Värd 4000-6000 kr — GRATIS vid 2 lådor smörjfett, vilket är en riktig no-brainer.",sp:["690 bar (normalt 450)","100gr/min","Batteri","Lube Shuttle+400g"],pr:"4000-6000kr (GRATIS vid 2 lådor fett)",fm:["Batteridragen"],di:[]},

// ══ 7. RENGÖRING ══
{id:"vatservetter",n:"Våtservetter Unicleaner",cat:"Rengöring",r:7,e:"🧻",c:"#14b8a6",tags:["verkstad","åkeri"],box:"50st → 12st → 6st",p:"Våtservetter Unicleaner med slät sida för sensibla ytor (skärmar, instrument) och räfflad baksida för tuffare rengöring (oljiga händer, verktyg). Scrubs-burken som de flesta verkstäder har kostar 299 kr — våra ligger på ca 80 kr för 50-pack, alltså nästan en fjärdedel av priset. Och de torkar inte ut i burken som Scrubs börjar göra efter några veckor, och frostar inte heller vid kyla. Lagom blöta så de biter utan att droppa. Använd på händer, verktyg, interiörer, allt. Hur många burkar går det åt hos er idag?",sp:["80kr (Scrubs 299)","Torkar inte ut","Frostar inte","Slät+räfflad"],pr:"~80kr/burk",fm:["50st","12st","6st"],di:[{q:"Kör ni Scrubs?"}]},

// ══ 8. KLÄDER ══
{id:"understall",n:"Underställ Millers Bambu",cat:"Kläder",r:8,e:"👕",c:"#059669",tags:["verkstad","bygg","åkeri"],p:"Millers bambuunderställ — bambu är både andningsaktivt OCH temperaturreglerande, till skillnad från ull som bara håller värmen. Naturligt antibakteriellt så det luktar inte svett lika snabbt som syntet, kan bäras flera dagar mellan tvätt utan att stinka. Mjukt mot huden utan att klia som ull, absorberar fukt och transporterar bort den från kroppen. Halva priset jämfört med kvalitetsull (som ligger över 1500 kr) — vi ligger under 750 kr. Finns i dam och herr, styckvis som överdel eller underdel så du kan bygga lager som du vill. Perfekt för er som jobbar i växlande temperaturer.",sp:["Bambu","Halva priset","Styckvis","Dam+herr","Antibakteriell"],pr:"Under 750kr",fm:["Överdel","Underdel"],di:[{q:"Kör ni ull?"},{q:"Hur många?"}],art:"5212(H)/5307(D)"},
{id:"strumptjock",n:"Perfectum Dura (Tjock strumpa)",cat:"Kläder",r:8,e:"🧦",c:"#b45309",tags:["verkstad","bygg","åkeri"],box:"12 par → 6 par",p:"Perfectum Dura är arbetsstrumpan som sålde 85 000 par senaste året — det säger en del om kvalitén. Rejäl, frottéförstärkt sula som dämpar hela dagen i säkerhetsstövlar, kraftigt resår över vristen som faktiskt håller strumpan uppe istället för att glida ner i stöveln som billiga strumpor alltid gör — det är där folk klagar mest. Frotten absorberar fukt och dämpar stötar. Sitter klockrent utan att vandra runt. Stl 35-38, 39-42, 43-46, 47-50. Kör 6- eller 12-pack. Vilken skostorlek har du själv?",sp:["Frotesula","Kraftigt resår","Glider inte","Stövlar","85000 sålda"],pr:"89-99kr/par",fm:["Stl 35-38/39-42/43-46/47-50"],di:[{q:"Skostorlek?"},{q:"Hur många?"}],art:"69-(stl)"},
{id:"strumptunn",n:"Perfectum Dura Spring (Tunn)",cat:"Kläder",r:8,e:"🧦",c:"#16a34a",tags:["verkstad","bygg","åkeri"],box:"12→6",p:"Perfectum Dura Spring — den tunnare varianten av vår arbetsstrumpa för vår och sommar. 80% bomull, 15% polyester, 5% elastane — förstärkt tå och häl där slitaget alltid kommer först, elastisk vriststrikning som håller formen tvätt efter tvätt. Går lika bra på jobbet som till vardags med sneakers — den ser ren och enkel ut i svart. Torkar snabbt, andas betydligt bättre än tjocka strumpor när det är varmt i skon. Vid 300-pack kan vi trycka er logga på skaftet för 59 kr/par — bra profilprodukt. Vad kör ni idag, tunt eller tjockt?",sp:["80% cotton","Funktion","Förstärkt tå/häl","Vår/sommar","Logga möjlig"],pr:"69-99kr/par (300st: 59kr eget tryck)",fm:["Stl 39-42/43-46/47-50"],di:[{q:"Tunna eller tjocka?"}],art:"69-10101"},

// ══ 9. SVETS ══
{id:"svetshjalm",n:"Svetshjälmar",cat:"Svets",r:9,e:"⚡",c:"#dc2626",tags:["svetsare"],p:"Svetshjälmar med automatisk mörkläggning — reaktionstid under 0,1 millisekunder så ljusbågen aldrig bränner ögat, vilket gamla statiska hjälmar fortfarande gör i uppstart. DIN 9-13 justerbart beroende på process: DIN 9-10 för TIG på tunnplåt, 11-12 för MIG, 13 för grov pinnsvets. Slipfunktion gör att du kan växla mellan slipning och svets utan att byta hjälm — stor produktivitetsvinst vid reparationssvets. Litiumbatteri plus solceller i toppen, så den är alltid laddad efter en arbetsdag under taklysrör. Hur många svetsare är ni, och vad kör de mest — TIG, MIG eller pinne?",sp:["Reaktion <0,1 ms","DIN 9-13","Slipfunktion","Solcell+batteri"],pr:"Se katalog",fm:["Diverse"],di:[{q:"Hur många svetsare?"}]},
{id:"svetsmaskin",n:"Svetsmaskiner",cat:"Svets",r:9,e:"🔌",c:"#b91c1c",tags:["svetsare"],p:"Svetsmaskiner i hela spektret — TIG, MIG/MAG och MMA (pinne). Inverterteknologi gör att de väger bara 5-15 kg trots att de levererar 200+ ampere, så du kan bära med maskinen upp i ställning istället för att dra slang. TIG för rostfritt, aluminium och tunnplåt där du vill ha precis kontroll på värmeinmatning. MIG/MAG för produktion när du ska lägga meter svets snabbt och konsekvent. MMA (pinne) för grovt jobb och utomhus där det blåser och MIG inte går. Vill ni ha en dedikerad maskin eller en kombimaskin som klarar flera processer?",sp:["TIG/MIG/MMA","Inverter","5-15 kg","200+ amp"],pr:"Se katalog",fm:["Diverse"],di:[{q:"TIG, MIG eller pinne?"}]},
{id:"elektroder",n:"NC 312ER Super Speed",cat:"Svets",r:9,e:"⚡",c:"#991b1b",tags:["svetsare"],box:"16-20kg kartong → 4kg",p:"NC 312ER Super Speed är reparationselektroden som löser de där jobben när du inte vet exakt vad materialet är. Funkar på rostfritt, fjäderstål, mangan, gjutjärn, verktygsstål, låglegerat stål — alla blandningar och gamla osäkra sammansättningar. Sprickbeständig och korrosionsbeständig svets i alla lägen (vertikal, tak, horisontellt) på både växel- och likström. Jämn båge, rent smälte, klänger inte materialet vilket är typiskt problem med billiga elektroder. Lätt att tända även första drag. Syrafri och rostfri svets. Vilken dimension kör ni mest — 2,5 eller 3,25?",sp:["Alla svetslägen","Sprickbeständig","Rostfritt/fjäder/mangan/gjut","Lätt tänd","AC+DC"],pr:"2.00: 236kr(in)/599(ut)/680\n2.50: 165(in)/179(ut)\n3.25: 150(in)/449/221\n4.00: 160(in)",fm:["2.00x300 4kg","2.50x300 4kg","3.25x350 5kg","4.00x350 5kg"],di:[{q:"Vilken dimension?"}],art:"1612212/249250/244320/1614312"},
{id:"svetskl",n:"Svetskläder",cat:"Svets",r:9,e:"🧥",c:"#a21c1c",tags:["svetsare"],p:"Svetskläder — förkläden i crust-läder, svetsärmar, huvor och nackskydd. EN ISO 11611 certifierat specifikt för svetsning, vilket är lagkrav i princip. Svets-läder tål gnistor och stänk utan att brinna till skillnad från vanliga arbetskläder som tänder vid första slagg-stänket. En enda glödrester i byxfickan och det är dagar av brännblåsor och plåster. Crust-läder andas bättre än split-läder och är mer slitstarkt. Kör ni mycket tak- eller vertikalsvets där stänket ramlar ner?",sp:["EN ISO 11611","Crust-läder","Arbetsmiljökrav","Förkläden/ärmar/huvor"],pr:"Se katalog",fm:["Diverse"],di:[]},

// ══ 10. MASKINER ══
{id:"flex",n:"Vinkelslip FLEX 125",cat:"Maskiner",r:10,e:"🔩",c:"#6366f1",tags:["verkstad"],p:"FLEX 125 är vinkelslipen från tyska FLEX-Elektrowerkzeuge — varumärket som bokstavligen uppfann vinkelslipen 1954, därav namnet. 1010 W motor, 11 500 varv per minut, myckte jämn gång tack vare vibrationsdämpat handtag som sparar handlederna på långa jobb. Tyskt proffsmonster som håller i 10+ år med daglig användning — Bosch Blå och Makita är samma klass men Flex är originalet. Soft-start gör att den inte rycker till vid påslag. GRATIS vid köp av 2 lådor Perfectum Premium kapskivor — värde ca 1700 kr.",sp:["1010W","11500 varv","Vibrationsdämpad","Tysk original 1954"],pr:"~1700kr (bonus vid 2 lådor kap)",fm:["1st"],di:[],art:"4383"},
{id:"slangvindor",n:"Slangvindor Blubird",cat:"Maskiner",r:10,e:"🔄",c:"#475569",tags:["verkstad"],box:"2st → 1st",p:"Slangvindor Blubird — visades på Köln verktygsmässa 2025, tysk producent som bara tillverkar åt bästa märkena. Vi säljer under Perfectum-namnet med 5 års garanti vilket ingen annan ger. Lättaste slangvindan på marknaden, vilket märks när du drar ner den från väggen flera gånger per dag. Tål solljus utan att slangen sprödnar (normalt UV-förstör slang inom 2 år på soligt vägg), är olje-, fett- och dieselresistent och flexibel även i minusgrader. Finns i 2 dimensioner per vinda för både vatten och luft. Har ni slangvindor idag, eller släpar ni slang på golvet?",sp:["Tysk producent, Köln 2025","5 års garanti","Lättaste","Tål solljus","Olje/fett/dieselresistent","Flexibel i minus"],pr:"Kontakta",fm:["Vatten","Luft","2 dimensioner/vinda"],di:[{q:"Har ni slangvindor?"},{q:"Tryckluft?"}]},
{id:"induktion",n:"Induktionsvärmare",cat:"Maskiner",r:10,e:"🌡️",c:"#9333ea",tags:["verkstad"],p:"Induktionsvärmare — elektromagnetisk induktion värmer enbart metallen, inte omgivningen. 30 sekunder för att få en fastrostad bult röd istället för 5 minuter med gasbrännare — och du bränner inte packningen, kablarna eller lacken bredvid som brännaren oundvikligen gör. Perfekt för fastrostade bultar, kullager som ska krympas på axel, rostade däcksbultar och avgaselement. Ingen brandrisk, ingen gasflamma i verkstaden, ingen gasaccumulering. Stor tidsbesparing på gamla fordon där allt är rostat. Jobbar ni mycket med äldre bilar eller lastvagnar?",sp:["30 sek vs 5 min","Ingen brandrisk","Enbart metall","Ej skador intilliggande"],pr:"Kontakta",fm:["Diverse"],di:[{q:"Fastrostade bultar?"}]},
{id:"starthjalp",n:"Starthjälp RIMAC",cat:"Maskiner",r:10,e:"🚗",c:"#059669",tags:["åkeri","verkstad"],p:"Starthjälp från RIMAC — kompakta litium-jon booster-paket som startar allt från småbilar till tunga lastbilar på 24V. Finns i 12V och 24V modeller, 20 000 mAh+ kapacitet så du får flera starts per laddning. USB-C snabbladdning så den är på 80% på en timme, LED-arbetsljus inbyggt för nattarbete. Klarar pålastade dieselmotorer som ligger döda efter helgen. Perfekt i åkerirygan eller serviceboxen på lastbil — en lastbil som inte startar på vintern vid -20° är guldvärd när du kommer på plats snabbt och löser det.",sp:["RIMAC","12V/24V","20000+ mAh","USB-C snabbladd","LED-ljus"],pr:"Se katalog",fm:["Diverse"],di:[]},
{id:"led",n:"LED-lampor",cat:"Maskiner",r:10,e:"💡",c:"#eab308",tags:["verkstad"],p:"LED-lampor i hela bredden — arbetsljus, ficklampor, pannlampor. 500-3000 lumen beroende på modell, magnetfäste på arbetsljusen, IP54-67 klassade för verkstadsmiljö med damm och stänk. Alla laddningsbara via USB-C, så du slipper kasta engångsbatterier varannan vecka som med gamla ficklampor. Arbetsljuset med stativ är favoriten i verkstad — lyser upp hela motorrummet vid nattskift utan skugga. Pannlampan med rödljus för när du inte vill blända kollegorna. Vilken typ behöver ni mest?",sp:["500-3000 lumen","Magnetfäste","IP54-67","USB-C laddning"],pr:"Kontakta",fm:["Diverse"],di:[]},

// ══ 11. VERKTYG ══
{id:"gangsats",n:"Gängsats Mannesmann 110 delar",cat:"Verktyg",r:11,e:"🔩",c:"#334155",tags:["verkstad"],p:"Mannesmann gängsats — tyskt kvalitetsmärke från Düsseldorf, 10 års garanti. 110 delar komplett sats, M2 till M18 med 70 gängtappar totalt (35 förtappar och 35 sluttappar) i olika stigningar, plus gängsnitt, gängklopphållare, gängkloppar och tappadapter. Allt i HSS-stål som klarar stål, rostfritt och gjutjärn. Värde 3000-3500 kr styck ute i handeln — vi har 400 st inköpta och kampanjar ut dem GRATIS vid köp av 2x25L spolarvätska. Vilken gängsats har ni i verkstaden idag?",sp:["110 delar","M2-M18","70 gängtappar","10 års garanti","HSS-stål","Värd 3000-3500kr"],pr:"GRATIS vid kampanj",fm:["Komplett sats"],di:[]},
{id:"handverktyg",n:"Handverktyg & Väskor",cat:"Verktyg",r:11,e:"🛠️",c:"#334155",tags:["verkstad","bygg"],p:"Komplett handverktyg och verktygsväskor — nyckelsatser, hylsor, skruvmejslar, tänger, kombinationer. 94-delars verktygsväska ingår vid samarbete, 108-delars vid större köp som kampanjerbjudande. Cromvanadin-stål i alla hylsor och nycklar, härdade skruvmejslar med magnetiska spetsar. Ergonomiska handtag med mjuk grepp som inte glider när du har olja på händerna. Vad saknas i er verkstad just nu — eller är ni fullt utrustade?",sp:["Cromvanadin","94/108-delarsväska","Ergonomiska handtag","Magnetiska spetsar"],pr:"Väska ingår",fm:["Satser"],di:[]},
{id:"sagblad",n:"Mandrex Tigersågblad",cat:"Verktyg",r:11,e:"🪚",c:"#64748b",tags:["verkstad","bygg"],p:"Mandrex Tigersågblad — tyskt tillverkade (Made in Germany), en av Europas ledande varumärken. 9 olika typer för alla material: 3X Fastcut (bi-metal med 8% kobolt, trippelsidig tandning så den kapar åt 3 håll utan att vända bladet), Multicut (allround inkl trä med spik), Multicut Renovering (extra tjock för rivning), Multicut Varia (fintandad variabel pitch för plåt och tunna material), Steelcut (bi-metal för plåt, rör och profiler), Hardcut TCT (tungsten carbide för härdat stål), Woodcut (krom-vanadin för rent trä), Toughcut (diamantkorn för gjutjärn, kolfiber, cementskiva, betong), Ezygrind (diamantbelagd rörkapare). Säljs i 2-pack. Vilka material jobbar ni mest i?",sp:["9 typer","Made in Germany","Trä/metall/sten/plast/stål","8% kobolt (3X Fastcut)"],pr:"Se prislista",fm:["Diverse (2st förp.)"],di:[{q:"Vilka material?"}]},
{id:"brandsack",n:"Brandsläckare",cat:"Verktyg",r:11,e:"🧯",c:"#ef4444",tags:["verkstad"],p:"Brandsläckare — ABC-pulver 6 kg är standard för verkstad och fordon och klarar de flesta scenarier (A=fast material, B=vätskor, C=gas). CO2 för elutrymmen där pulver skadar utrustning, skumsläckare för lösningsmedelslager. Årlig kontroll är lagkrav via SVEBRA-certifierad tekniker, och hela släckaren måste bytas vart 5:e år oavsett skick. Vi kan leverera nya släckare OCH koppla upp er med kontrollfirma för årlig revision. Hur många har ni ute i lokal och fordon idag, och när gjordes senaste kontroll?",sp:["ABC-pulver 6kg","SVEBRA-kontroll","Årlig kontroll","Byte vart 5:e år"],pr:"Kontakta",fm:["Diverse"],di:[]},
];

// Kundtyper
const CTYPES=[
{id:"verkstad",n:"🔧 Verkstad",ps:["sprayer","brake","smorjfett","kapskivor","handskar","ergotec","vatservetter","bamse"]},
{id:"svetsare",n:"⚡ Svetsare",ps:["kapskivor","slipskivor","svetshandske","svetshjalm","svetsmaskin","elektroder","sprayer","brake","visionpro"]},
{id:"åkeri",n:"🚛 Åkeri",ps:["spolar","glykol","adblue","handskar","aquaguard","vatservetter","citr","skumglans","starthjalp"]},
{id:"bygg",n:"🏗️ Bygg",ps:["handskar","ergotec","ducavinter","kapskivor","sprayer","understall","strumptjock","algfasad"]},
{id:"skog",n:"🌲 Skog",ps:["kedja","handskar","foamcut","sprayer","understall","strumptjock"]}
];

// Invändningar
const OBJ=[
{q:"Vi har redan leverantör",a:"Perfekt — vi kompletterar med det de inte har. Testa en handske!",w:"Tala inte illa"},
{q:"Skicka mejl",a:"Mejl hamnar bland hundra. Testpaket — 2 min att utvärdera?",w:"Bara maila"},
{q:"Inte intresserad",a:"De flesta säger så innan de sett. Köper ni handskar nånstans?",w:"Ge upp"},
{q:"Ingen budget",a:"Budget för förbrukningsvaror har ni redan — ni testar en produkt ni redan köper.",w:"Acceptera"},
{q:"Ring i augusti",a:"Skickar varuprov nu — du testar, vi stämmer av i augusti!",w:"Bara boka om"},
{q:"Inte beslutsfattare",a:"Vem bestämmer om inköp? Jag ringer rätt person.",w:"Avfärda"},
{q:"Får inte ta emot gåvor",a:"Inga gåvor — varuprover för utvärdering. Som Würth-tester.",w:"Insistera gåva"},
{q:"Vi har ramavtal",a:"Ramavtal täcker inte allt. Specifikt på handskar/kem? Komplettera!",w:"Bryta ramavtal"},
{q:"Skicka prislista",a:"Vilka 3 produkter mest? Skräddarsyr offert.",w:"Generisk PDF"},
{q:"Vi köper lokalt",a:"Vi sitter i Skövde — mer lokalt blir det inte!",w:"Argumentera"},
{q:"Låter för bra",a:"18 000 kunder, Skövde sedan 2017. Ingen hake.",w:"Bli defensiv"},
{q:"Vad är haken?",a:"Haken: vi räknar med att du gillar det. Inget avtal.",w:"Undvika"},
{q:"Har inte tid",a:"45 sek: vi levererar handskar, kem, verktyg. Vilken adress?",w:"Prata längre"},
{q:"Nöjda med leverantör",a:"Inte ersätta — vi är back-up som alltid har grejerna.",w:"Attackera"},
{q:"Tionde som ringer",a:"Skillnaden: jag ber inte köpa. Testpaket, du bestämmer.",w:"Ignorera"},
{q:"Ring chefen",a:"Vad heter chefen? Kan jag nämna att vi pratat?",w:"Inte ta namn"},
{q:"Bara huvudleverantörer",a:"Fortsätt! Vi kompletterar — det lilla varje vecka.",w:"Dag 1 huvud"},
{q:"För dyrt",a:"Jämfört med vad? Totalkostnad med leverans = billigare.",w:"Sänk direkt"},
{q:"Testade er förut",a:"Vad funkade inte? Vi gjort om en hel del.",w:"Förneka"},
{q:"Ska tänka",a:"Vad specifikt? Kanske jag kan hjälpa med info?",w:"Bara okej"},
{q:"Kör Biltema/Jula",a:"Levererar till dörren, faktura, bättre löpande.",w:"Tala illa"},
{q:"Vi är för små",a:"Perfekt! Exakt sådana vi jobbar med — 5-20 anställda.",w:"Köp mer"},
{q:"Litar inte telefonsäljare",a:"Köper det. Därför vill jag komma ut. En kvart?",w:"Bli kränkt"},
];

// Skämt
const JOKES=[
{cat:"🎤 Öppning",items:["Sitter du i grävarn?","Brödfödan ska ju in oavsett tid och väder!","Femte växeln!","Hoppas jag inte ringer mitt i fikat","Ännu en telefonförsäljare — men trevligaste idag!","Stör mitt i nåt viktigt? Typ googla semesterresor?"]},
{cat:"😅 Självdiss",items:["Min chef sa jag ska bli jobbig — jag gör mitt bästa!","Inget är gratis — men det här kommer nära","Lovar att inte ringa igen... förrän om 2 månader","Skövdes trevligaste telefonförsäljare"]},
{cat:"🎬 Avslut",items:["Svetsmaskin också va? Nej tänkte väl det!","Ska jag skicka Tesla? Skämt... eller?","Verktygsvagn 339 delar på det? Om du inte vill?"]},
{cat:"🔄 Comeback",items:["Bra! Testa handskarna — skämta mer nästa gång","Roligare än förra kunden — han la bara på","Den sparar jag!"]},
{cat:"⏰ Stressad",items:["30 sekunder, lovar","Kortare än reklamfilm","Halv minut bara"]},
];

// Status pipeline
const STATUSES=[
{id:"ny",l:"🟡 Ny kontakt",c:"#f59e0b"},
{id:"skickad",l:"📦 Skickad",c:"#3b82f6"},
{id:"uppfoljning",l:"📞 Uppföljning",c:"#8b5cf6"},
{id:"order",l:"✅ Första order",c:"#10b981"},
{id:"aterkommande",l:"🔄 Återkommande",c:"#059669"},
{id:"forlorad",l:"❌ Förlorad",c:"#6b7280"},
];
