// Perfectum Produktdatabas V8 — Perfekta expert-pitchar
const PRODUCTS=[
// ══ 1. SPOLARVÄTSKA & GLYKOL ══
{id:"spolar",n:"Spolarvätska",cat:"Spolarvätska & Glykol",r:1,e:"💧",c:"#0ea5e9",tags:["åkeri","verkstad","bygg"],box:"2x25L → 1x25L",bonus:"Gängsats 110 delar (M2-M18) värd 3000-3500kr GRATIS vid 2x25L, pris 89→79kr/L",p:"Vår spolarvätska kommer från Swedhandling i Norrköping — ENDA företaget i Sverige med Svanenmärkning på spolarvätska, vilket är det absolut tuffaste miljökriteriet i Europa idag. Bioetanolbaserad, 93% aktivhalt koncentrat som späds 3-6 gånger beroende på årstid — brukslösningen hamnar på 59-69 kr/L vilket är billigast i branschen. 1L-packet är klassat som ej farligt gods så den kan stå i förråd utan UN-märkning, 25L-dunk och 205L-fat kräver kemikaliepärm men ger bättre literpris. Swedhandling kör 7 turbilar plus en tankbil på HVO-biobränsle så leveranser når hela Sverige dagligen, ISO 9001 och 14001-certifierade. Hur mycket kör ni per år — och är det koncentrat eller färdigblandat idag?",sp:["93% aktivhalt","Svanenmärkt (enda i SE)","Bioetanol","Späds 3-6x","1L ej farligt gods"],pr:"59-69kr/L | Kampanj: 79kr/L vid 2x25L",fm:["1L (12/24-pack)","25L dunk","205L fat"],di:[{q:"Koncentrat eller färdigblandad?"},{q:"Hur mycket per år?"},{q:"Glykol?",lk:"glykol"}]},
{id:"glykol",n:"Glykol",cat:"Spolarvätska & Glykol",r:1,e:"🧊",c:"#6366f1",tags:["åkeri","verkstad"],box:"2x25L → 1x25L",p:"Glykol också från Swedhandling — 93% aktivhalt longlife Klass 3 som håller 5 år i både maskineri och dunk, så ert lager dör inte på hyllan. Uppfyller ASTM D3306, BS 6580, AFNOR NF R15-601, BWB Tyska försvaret OCH svenska försvarsstandarden FSD 8704 — det är kvalitetsbevis som faktiskt betyder något i upphandling. Nitrit-, amin-, fosfat-, borat- och silikatfri vilket gör den säker i alla moderna aluminiummotorer där silikatglykol kan ge propp i kylaren. Vi har 5 färger eftersom fordonen kräver olika: Blå etylen 69 kr/L är standard, Röd 69-79 för nyare personbilar, Grön propylen 79-99 är miljövalet, Gul 69-79 för Volvo-specifikationen, Transparent 79-89 när du inte vet vad som finns i systemet. OBS — blanda aldrig färger okontrollerat, då får du klumpar och proppar. Vilken färg kör ni på fordonen, och behöver ni även till maskiner?",sp:["93% aktivhalt","ASTM D3306 + FSD 8704","Nitrit/silikat-fri","Klass 3 longlife 5 år","5 färger"],pr:"69-99 kr/L beroende färg",fm:["4L","20L","25L","205L fat"],di:[{q:"Vilken FÄRG?"},{q:"Maskiner eller fordon?"},{q:"AD-Blue?",lk:"adblue"}]},
{id:"adblue",n:"AD-Blue",cat:"Spolarvätska & Glykol",r:1,e:"🔵",c:"#3b82f6",tags:["åkeri"],box:"205L → 25L",p:"AD-Blue är lagkrav för alla Euro 6-dieselmotorer sedan 2014, så kör ni lastbil eller tyngre entreprenadmaskiner så MÅSTE ni ha det — annars går motorn i nödläge med begränsat varvtal. Det är en urealösning på 32,5% som sprutas in i avgaserna och bryter ner NOx till kväve och vatten via SCR-katalysatorn. Förbrukning ligger på 3-5% av dieseln, så kör ni 10 000 L diesel i månaden drar ni 300-500 L AD-Blue. Swedhandling kör en egen dedikerad tankbil för AD-Blue-leveranser ut i hela Sverige, ISO 22241-certifierad kvalité så det funkar perfekt i Volvo, Scania, Mercedes, MAN och DAF utan risk för kristallisering i systemet. Volymrabatt från 10L dunk upp till 1000L IBC-tank — ju större desto billigare per liter. Hur mycket diesel tankar ni per månad så räknar jag ut behovet?",sp:["ISO 22241","Euro 6 lagkrav","Egen tankbil","32,5% urea"],pr:"Volymbaserat",fm:["10L","25L","205L","1000L IBC"],di:[{q:"Hur mycket i månaden?"}]},

// ══ 2. SPRAYER & AEROSOLER ══
{id:"sprayer",n:"Sprayer — Översikt",cat:"Sprayer",r:2,e:"🧴",c:"#ef4444",tags:["verkstad","svetsare","bygg"],box:"24st blandlåda → 12st dussin",bonus:"Paket 24st + kylsnyckelsats = 2995kr. Styckpris från 12st: 129kr",p:"Aerosoler på burk är konsumtionsvaror som alltid går åt — ingen verkstad klarar sig utan. Det här är Tony Rikardsson-serien, 149 kr/burk hos mig (159 ut över disk) och Brakeclean är 60 spänn billigare just för att den går åt mest. 14 olika typer så vi täcker i princip allt en verkstad behöver. Jäkla tryck i flaskorna, massa aktiva ämnen och teflontillsats — inget av det där utspädda skräpet som grossisterna säljer under eget märke. Kunden innan dig tog Brakeclean, Rostlösare och Allround-PTFE som tre-paketet. Vilka tre använder ni mest?",sp:["Tony Rikardsson","149-159kr/burk","Brakeclean billigare","14 typer"],pr:"149-159kr/burk | Paket 24st: 2995kr",fm:["Enstaka","Dussin 12","Blandlåda 24"],di:[{q:"Brakeclean?",lk:"brake"},{q:"Rostlösare?",lk:"rost"},{q:"Allround/VD40?",lk:"allround"},{q:"Kedjespray?",lk:"kedja"},{q:"Krypfett?",lk:"kryp"},{q:"Kylspray?",lk:"kyl"},{q:"Teflon?",lk:"tefl"},{q:"Citrus A?",lk:"citr"},{q:"Glasrent?",lk:"glas"},{q:"Multiskum?",lk:"multi"},{q:"Kopparspray?",lk:"kopp"},{q:"Kontaktspray?",lk:"kont"}]},
{id:"brake",n:"Brakeclean/Maskinrent",cat:"Sprayer",r:2,e:"🔵",c:"#3b82f6",tags:["verkstad","svetsare"],p:"Brakeclean är den absolut mest sålda sprayen i hela vårt sortiment — ingen fordons- eller maskinverkstad klarar sig utan. Snabbverkande fettlösare baserad på aceton och heptan som löser olja, bromsdamm, asbestrester, vägsmuts och gamla fettrester från bromsskivor, hjulhus, bromssadlar och chassi — allt utan att lämna rester efter sig. Vår ligger 60 spänn billigare än övriga sprayer, just för att den går åt så extremt mycket att vi vill ni alltid ska ha den i hyllan istället för att stå utan. Högt tryck i burken, snabbtorkande på 30 sekunder — sprut, vänta, torka av med fiberduk. Hur många burkar går det hos er i månaden?",sp:["Aceton/heptan","Snabbtorkande 30s","Billigaste","Ingen rest"],pr:"~89-99kr",fm:["Enstaka","Dussin"],di:[{q:"Hur många i månaden?"}],art:"000000"},
{id:"rost",n:"Rostlösare",cat:"Sprayer",r:2,e:"🟠",c:"#f97316",tags:["verkstad"],p:"Rostlösare som verkligen penetrerar — den där fastrostade muttern som suttit i 10 år går loss på bara minuter. Hemligheten är kapilläreffekten: vätskan kryper in i minsta gängspringa och löser rosten underifrån, istället för att bara lägga sig som en film på toppen vilket är vad billiga rostlösare gör. Tar också gnissel i gångjärn, låskolvar, wirefästen, dörrgångjärn och bakstycksrullar — allt som börjat tjura av väta eller ålder. Efter behandling sitter en tunn smörjfilm kvar så det inte kärvar nästa gång. En burk räcker länge — men när du behöver den så behöver du den JU.",sp:["Kapillärverkan","Löser rost","Smörjfilm kvar","Gnisslet borta"],pr:"149kr",fm:["Enstaka","Dussin"],di:[],art:"942100"},
{id:"allround",n:"Allroundspray PTFE",cat:"Sprayer",r:2,e:"🟢",c:"#10b981",tags:["verkstad"],p:"Vår Allroundspray PTFE är VD40 fast bättre — och jag säger det med pondus. Skillnaden är tillsatsen av PTFE (det riktiga Teflon) som ger verklig smörjning där vanliga universalsprayer bara fuktar ytan tillfälligt. Trycker ut vatten, skyddar mot korrosion, smörjer gångjärn, lås, skenor, kedjedrev och linjerare — samma flaska till allt. Starkt tryck i förpackningen, sprider sig jämnt och torkar inte ut lika fort som vanlig allround gör. Kör ni VD40 idag så är det här en ren uppgradering för samma pris — bättre prestanda i varje test. Hur många burkar går åt per månad hos er?",sp:["VD40-ersättare","PTFE (Teflon)","Vattenutträngande","Korrosionsskydd"],pr:"149kr",fm:["Enstaka","Dussin"],di:[{q:"Kör ni VD40?"}],art:"250200"},
{id:"kedja",n:"Kedjespray",cat:"Sprayer",r:2,e:"⛓️",c:"#8b5cf6",tags:["skog"],p:"Kedjespray med extrem vidhäftning — den sätter sig där den ska och stannar kvar även vid högt varvtal. Penetrerar först in i kedjans leder och länkar (där slitaget faktiskt sker), sen bygger den upp en seg harts-film som inte slungas av när du gasar. Funkar lika bra på motorsågar som industrikedjor, transportkedjor och cykelkedjor. Vattenavvisande så den håller i regn, snö och efter tvätt — du slipper smörja om efter varje skur. Kör ni skogsmaskin, motorsåg eller industrikedja? För doseringen är lite olika.",sp:["Vidhäftning","Vattenavvisande","Slungas ej av","Hartsfilm"],pr:"149kr",fm:["Enstaka"],di:[],art:"070106"},
{id:"kryp",n:"Krypfett/Mos2",cat:"Sprayer",r:2,e:"💛",c:"#eab308",tags:["verkstad"],p:"Krypfett med MoS2 (molybdendisulfid) — de där svarta partiklarna som lägger sig som ett hårt smörjande skikt under belastning. Kryper in i springor via kapillärverkan så du sprutar utanför och den hittar vägen in till gängor, glidytor och svåråtkomliga lager. MoS2 är samma grundämne som används i militärfordon och flygindustri just för att den håller även under extremt tryck och temperatur. Mellanting mellan klassiskt smörjfett och allroundspray — bättre än båda på rätt ställe. Perfekt på bultar som ska lossas senare utan att fastna.",sp:["MoS2 molybdendisulfid","Kryper in","Högtryck/värme","Militär/flyg-standard"],pr:"149kr",fm:["Enstaka"],di:[],art:"240200"},
{id:"kyl",n:"Kylspray/Skärspray",cat:"Sprayer",r:2,e:"❄️",c:"#06b6d4",tags:["verkstad"],p:"Kylspray (skärspray) som förlänger livslängden på borr och skärverktyg rejält — vi pratar 2-3 gånger längre hållbarhet på dyra kvalitetsborr jämfört med torrborrning. Kyler ner skäreggen, minskar friktionen och spolar bort spånorna i samma rörelse. Extra viktigt när du borrar i rostfritt, titan eller härdat stål där värmen snabbt glödgar ut härdningen i spetsen och borret blir värdelöst. Ett enda sprut på skäret mellan drag räcker — du slösar inte. Hur mycket borrar och svarvar ni, och vilka material är det mest?",sp:["2-3x längre livslängd","Kyler skärgegg","Rostfritt/titan/härdat","Spånutkast"],pr:"149kr",fm:["Enstaka"],di:[],art:"72012"},
{id:"tefl",n:"Teflonspray PTFE",cat:"Sprayer",r:2,e:"⚪",c:"#64748b",tags:["verkstad"],p:"Teflonspray med rent PTFE-film som ger friktionskoefficient ner mot 0,04 — det är i princip halkigt som is. Lägger sig som ett mikrotunt torkat skikt på rörliga delar: skenor, kullager, gångjärn, styrbultar och glidytor. Torkar snabbt, fläckar inte och samlar INTE damm som oljor alltid gör — där du inte vill ha kladd är detta bästa valet. Perfekt för skjutdörrar, teleskopiska armar, verktygsvagnar, linjerare. Vad smörjer ni på rörliga delar idag?",sp:["PTFE rent","Friktion 0,04","Samlar inte damm","Torkar snabbt"],pr:"149kr",fm:["Enstaka"],di:[],art:"520800"},
{id:"citr",n:"Citrus A",cat:"Sprayer",r:2,e:"🍊",c:"#f59e0b",tags:["verkstad"],p:"Citrus A med d-limonen — samma naturliga lösningsmedel som finns i apelsinskal och som löser klister och lim som smör i solen. Tar bort klisterrester, dekalrester, tuggummi, tjära, kåda och gamla tejprester utan att skada lack, plast eller gummi underlag. Fantastisk citrusdoft som faktiskt gör verkstaden trevligare att jobba i — kunderna kommenterar det nästan varje gång. Perfekt på begagnade bilar med gamla dekaler, efter renovering när du tar bort maskeringstejp, eller på kontorslokaler efter butiksombyggnad. Har ni problem med klisterrester någonstans idag?",sp:["D-limonen (apelsinskal)","Lack-/plast-säker","Klister/tjära","Trevlig doft"],pr:"149kr",fm:["Enstaka"],di:[],art:"550200"},
{id:"glas",n:"Glasrent",cat:"Sprayer",r:2,e:"🪟",c:"#0ea5e9",tags:["verkstad"],p:"Glasrent har fått en rejäl uppgradering senaste året — nu absolut strimfri även på stora ytor. Ammoniakfri formula som inte anfräter plast eller listgummi på sikt som vissa fönsterputsar gör efter några år. Funkar lika bra på bilrutor, butiksfönster, speglar och glasade dörrar. Skummar upp fint, bryter ner fett, nikotin och vägfilm, torkar sedan bort rent utan att lämna skyddsfilm som syns mot ljuset. Kör ni personbilsverkstad så säljer den sig själv vid receptionen — kunderna frågar efter den.",sp:["Ammoniakfri","Strimfri","Plast/gummi-säker","Nikotin/vägfilm"],pr:"149kr",fm:["Enstaka"],di:[],art:"340100"},
{id:"multi",n:"Multiskum",cat:"Sprayer",r:2,e:"🫧",c:"#a855f7",tags:["åkeri"],p:"Multiskum för interiör — bilar, lastbilshytter, entreprenadmaskiner. Skummar upp fint och bryter ner fett, svett och smuts från textil, plast, läderinredning och gummidetaljer utan att skada materialet under. Torkas bort med en fuktig mikrofibertrasa — inget vatten behövs, så perfekt för hytter där du inte kan spola. Säten, ratt, rattstång, dörrpaneler — allt blir fräscht igen. Kör ni tvätt på lastbilshytterna så säljer den sig själv på chaufförerna som ser skillnaden direkt.",sp:["Interiör","Textil/plast/läder","Ingen spolning","Fiberduk räcker"],pr:"149kr",fm:["Enstaka"],di:[],art:"101100"},
{id:"kopp",n:"Kopparspray",cat:"Sprayer",r:2,e:"🟤",c:"#b45309",tags:["verkstad"],p:"Kopparspray (kopparpasta) som klarar upp till 1100°C — avgasgrenrör, bromssadelsbultar, lambdasondens gängor, tändstiftsgängor, allt som blir riktigt varmt. Fungerar som anti-seize så när du ska lossa muttern 3 år senare går den loss utan att gänga av sig eller bryta skallen. Tunt skikt räcker — en burk håller mycket längre än man tror om man inte överdriver doseringen. VIKTIG VARNING: använd INTE på aluminium — då får du galvanisk korrosion eftersom koppar och alu reagerar elektriskt. Där vill du ha keramikpastan istället. Hur ofta byter ni avgaskomponenter?",sp:["1100°C","Anti-seize","Ej på alu","Lambda/tändstift"],pr:"149kr",fm:["Enstaka"],di:[],art:"060100"},
{id:"kont",n:"Kontaktspray",cat:"Sprayer",r:2,e:"⚡",c:"#eab308",tags:["verkstad"],p:"Kontaktspray för el — trycker ut fukt från elkontakter, säkringshållare och kopplingar, och lämnar sen en torr smörjande film som skyddar mot framtida korrosion. Löser också oxidbeläggning från kopparkontakter så ledningen får perfekt kontakt igen — det räddar dig vid intermittenta fel. Godkänd på all elektronik inklusive känslig styrelektronik (ECU, ABS-styrdon), så du kan spraya på fordonselektronik utan rädsla för kortslutning. Perfekt vid fordonsfel som kommer tillbaka gång på gång — statistiken är att 70% av alla så kallade elfel i verkligheten är dålig kontakt. Jobbar ni mycket med elfelsökning?",sp:["Fuktutträngande","Löser oxid","ECU-säker","70% av elfel = kontakt"],pr:"149kr",fm:["Enstaka"],di:[],art:"4148100"},
{id:"kera",n:"Keramikpasta",cat:"Sprayer",r:2,e:"⚪",c:"#d1d5db",tags:["verkstad"],p:"Keramikpasta med keramiska partiklar som klarar upp till 1400°C och är 100% neutral mot aluminium — det är hela poängen jämfört med kopparpastan. Om du använder kopparpasta på aluminiumavgasdelar får du galvanisk korrosion (elektrolys) som fräter sönder gängan på några månader. Keramiken reagerar inte med någonting, varken järn eller alu. Samma anti-seize funktion som kopparpastan — gängor går loss år senare utan problem. Perfekt på moderna bilar där mycket är alu: motorfästen, avgasgrenrör, hjulnav och MC-avgassystem. Har ni alugrenrör eller fälgbultar ni brukar fastnar med?",sp:["1400°C","Aluminium-säker","Ingen galvanisk","Modern bil"],pr:"149kr",fm:["Enstaka"],di:[],art:"200792"},
{id:"tjar",n:"Tjärspray",cat:"Sprayer",r:2,e:"⬛",c:"#1e293b",tags:["åkeri"],p:"Tjärspray löser asfalt, tjära, oljefläckar och bitumen från lack utan att skada klarlacken — mycket skonsammare än de gamla tjärborttagarna som också åt upp lacken över tid. Fordonslack-säker, testad på modern vattenbaserad 2K-lack som finns på alla nybilar sedan 2005. Perfekt efter sommarkörning när tjärstänk fastnar i flanker och stötfångare, eller efter vägarbeten när asfaltrester hamnar under bilen. Sprut på, vänta 2 minuter, torka bort med mikrofiber. Kör ni mycket motorvägstrafik med lastbilar eller bilar så är det här konstant-säljare.",sp:["Lack-säker (2K)","Löser bitumen","Asfaltstänk","Modern vattenbaserad"],pr:"149kr",fm:["Enstaka"],di:[],art:"70022"},

// ══ 3. AVFETTNING & KEM ══
{id:"bamse",n:"Bamse Alkalisk Special",cat:"Avfettning & Kem",r:3,e:"🐻",c:"#dc2626",tags:["verkstad","åkeri","bygg"],box:"205L fat → 25L dunk → 5L",bonus:"108-delars verktygsväska (2000kr) + gottepåse gratis vid köp",p:"Bamse är vår mest sålda produkt på 30 år — det säger en del. 87% aktivhalt där konkurrenter ligger på 18-23% — kör du grossist idag så är det nästan bara vatten med lite kem i. Lutbaserad och späds hela 50 gånger, så brukslösningen hamnar på 2-4 kr/L — absolut billigaste på marknaden när du räknar VERKLIG literkostnad. Kundlistan säger allt: Modo Skog, Assi Domän, Stockholms kommun, kriminalvården och 6 000 åkerier i Sverige. Tar ALLT inklusive miljöoljor och fastbrända oljerester som andra bara lämnar efter sig. VIKTIGT — koncentratet tar lacken, så var försiktig med spilldroppar vid hantering. Finns med på Kemikaliesvepets vita lista (Naturskyddsföreningens kriterier sedan 1990-talet), miljövänlig utan petroleum eller lösningsmedel. Funkar både i högtryck och handspruta. Vad kör ni på avfettning idag?",sp:["87% aktivhalt (bransch 18-23)","Späds 50x","Brukslösn. 2-4kr/L","30 år","6000 åkerier-kunder","Kemikaliesvepet"],pr:"119-149kr/L | Ord: 99,90/fat",fm:["5L","25L dunk","205L fat"],di:[{q:"Alkaliskt eller kall?"},{q:"Prickbort?",lk:"prickbort"},{q:"Skumglans/Foamer?",lk:"skumglans"}]},
{id:"prickbort",n:"Prickbort Kallavfettning",cat:"Avfettning & Kem",r:3,e:"✨",c:"#e11d48",tags:["verkstad","åkeri"],box:"2x25L → 1x25L",p:"Perfectums starkaste av 3 Prickbort-varianter — högtrycksrengöring för de riktigt svårlösliga oljeföroreningarna: asfalt, vägsmuts, gödsel, kåda och flygrost. Till skillnad från de flesta konkurrenter späds den INTE — rakt i sprutan och kör, vilket sparar både tid och blandningskrångel i verkstan. Sprayas på torr yta, verkar i 2 minuter, sköljs av med högtryckstvätt. Svensktillverkad och biologiskt nedbrytbar, godkänd på Kemikaliesvepets vita lista. Rengör ni lastbilar, maskiner eller bilar på egen anläggning?",sp:["Späds INTE","Starkaste av 3","Svensktillverkad","Biologiskt nedbrytbar","Kemikaliesvepet"],pr:"119kr/L (25L)",fm:["25L dunk"],di:[],art:"197"},
{id:"skumglans",n:"Skumglanschampo/Foamer",cat:"Avfettning & Kem",r:3,e:"🫧",c:"#0891b2",tags:["åkeri","verkstad"],box:"25L → 5L",p:"Skumglanschampo aka Foamer — tänk grädtårta på hela maskinen! Det är en 2-i-1 lösning som både rengör och bilvårdar i samma arbetsmoment. Appliceras via skumlans eller kemiblandare på högtrycktvätten — bilen blir täckt i tjockt krämigt skum som bryter ner smutsen medan vax-komponenten samtidigt bygger en skyddsfilm över lacken. Spola av, och ytan dammar sedan av snabbare i veckor framöver eftersom skyddsfilmen håller. 149 kr/L låter högt tills du räknar att det ersätter både schampo och separatvax. Har ni foamer-skumlans på tvätthallen idag, eller kör ni handtvätt?",sp:["2-i-1 tvätt+vax","Foamlans/högtryck","Skyddsfilm","Grädtårt-effekt"],pr:"149kr/L",fm:["5L","25L"],di:[{q:"Har ni foamer?"}]},
{id:"algfasad",n:"Alg & Fasadtvätt",cat:"Avfettning & Kem",r:3,e:"🏠",c:"#059669",tags:["bygg"],box:"25L",p:"Vår Alg & Fasadtvätt är Sveriges billigaste sätt att rengöra fastigheter från grön hinna och svart mögel. Späds 10 gånger = brukslösning på endast 16,90 kr/L — hitta det någon annanstans, det går inte. Tar alger, mögel och lav på fasader (puts, trä, eternit), plasttak, utemöbler, båtbotten och stuprännor. Biologiskt nedbrytbar och behöver INTE spolas av — regnet sköter det åt dig över närmaste veckorna, vilket sparar vattenkostnad och tid. Håller rent i 2 år efter en enda behandling. Har ni fastighetsförvaltning eller hus där det alltid kommer tillbaka grön hinna på norrsidan?",sp:["Späds 10x","16,90kr/L brukslösning","Behöver ej spolas","2 år verkan","Biologiskt nedbrytbar"],pr:"~169kr/L",fm:["25L"],di:[{q:"Fastigheter med alger/mögel?"}]},
{id:"vegavfett",n:"Veg-Avfettning Special",cat:"Avfettning & Kem",r:3,e:"🌿",c:"#16a34a",tags:["verkstad"],p:"Veg-Avfettning Special — helt vegetabilisk bas istället för petroleum, tillverkas i samma svenska kemfabrik sedan 25 år tillbaka. pH 12,5 så det sparkar riktigt bra på tung smuts, men betydligt hudvänligare än traditionellt lutbaserat vilket personalen märker direkt efter några dagars användning. Blandningsförhållande 1:5 för fordonstvätt och maskinavfettning, 1:2 för verkstadsgolv och riktigt tufft jobb. Miljöfördelen är enorm jämfört med petroleumbaserat — det är grönt tänk som era kunder gillar att se i hållbarhetsrapporten och som hjälper kraftigt vid offentliga upphandlingar. GPS-vakt värd 2995 kr ingår som bonus vid köp.",sp:["100% vegetabilisk","25 år svensk fabrik","pH 12,5","Hudvänlig","Upphandlings-vänlig"],pr:"Kontakta",fm:["4x5L kartong"],bonus:"GPS-vakt värd 2995kr",di:[]},
{id:"vaxschampo",n:"Vaxschampo",cat:"Avfettning & Kem",r:3,e:"🚗",c:"#0ea5e9",tags:["åkeri"],p:"Vaxschampo som bygger upp en vaxemulsion över karossen under själva tvätten — skyddar mot vägsalt, diesel, fett och industriföroreningar i samma arbetsmoment som rengöringen. Efter tvätten sitter en tunn hydrofob skyddsfilm kvar som gör att nästa tvätt går snabbare OCH minskar rostangrepp på lackfel och stensprut. pH 10, skonsam mot både lack och plastdetaljer — kan köras varje tvätt utan att slita ner lacken. Kör ni åkeri eller busstrafik så ser ni skillnaden direkt efter 2-3 månader: bilarna ser nyare ut betydligt längre och håller färgen bättre. Hur ofta tvättar ni fordonsflottan?",sp:["Vaxemulsion","Hydrofob skyddsfilm","pH 10 skonsam","Rostskydd"],pr:"Kontakta",fm:["5L"],di:[],art:"513"},
{id:"handrent",n:"Handrent Aloe Vera",cat:"Avfettning & Kem",r:3,e:"🤲",c:"#10b981",tags:["verkstad"],p:"Handrent med aloe vera — tar bort diesel, olja, fett, lim och grafit helt utan vatten. Fantastisk citrusdoft istället för den typiska industrikemilukten, och aloe veran gör att huden inte torkas ut som hos traditionella hårda handrengöringar med pimpstenskorn. Perfekt ute på projekt där det inte finns vatten, i servicebilen, eller vid slutet av dagen innan man åker hem och ska hantera ratten i egna bilen. Finns i 1,5L, 2,7L och 4,5L pumpflaska — verkstaden borde ha den stora varianten vid handfatet, det blir billigare per användning. Hur många är ni som jobbar med olja och fett dagligen?",sp:["Utan vatten","Aloe vera","Citrusdoft","Hudvänlig","Pumpflaska"],pr:"~12kr",fm:["1.5L","2.7L","4.5L"],di:[],art:"149"},

// ══ 4. HANDSKAR ══
{id:"handskar",n:"Handskar — Översikt",cat:"Handskar",r:4,e:"🧤",c:"#2563eb",tags:["verkstad","svetsare","bygg","åkeri","skog"],box:"2 dussin (24 par) → 1 dussin (12 par)",p:"Något som alltid går åt — man kan inte gå runt naken, som Börje sa. Tunn montage? Nitril? Getskinn? Oljiga miljöer eller vanlig montering? Vi har 8 modeller som täcker allt från precisionsmontage till skärskydd klass C och vattenavvisande vinterhandskar. Social proof: 69 000 par sålda under 2024 — det är inte bara prat, det är konkreta siffror från vårt eget lager. Vilka handskar kör ni mest av idag, och vad är största problemet — att de slits ut för fort, att storlekarna inte passar, eller att de bara är för dyra?",sp:["8 modeller","Stl 6-12","Från 49kr/st","69000 par sålda 2024"],pr:"49-189kr/st",fm:["Styckvis","Dussin 12","Kartong 24"],di:[{q:"Tunn montage/nitril?",lk:"ergotec"},{q:"Oljiga/våta miljöer?",lk:"aquaguard"},{q:"Vinterhandskar getskinn?",lk:"ducavinter"},{q:"Skärskydd?",lk:"foamcut"},{q:"Svetshandskar?",lk:"svetshandske"},{q:"Premium allround?",lk:"perfhandsken"},{q:"Sommar precision?",lk:"ducasommar"}]},
{id:"ergotec",n:"Ergo Tec (Tunn montage)",cat:"Handskar",r:4,e:"✋",c:"#2563eb",tags:["verkstad","bygg"],box:"24 par → 12 par",p:"Ergo Tec — nitril undertill, tunn tygväv upptill, 49 kr/st vilket är extremt konkurrenskraftigt. PU+Nitril blandning på insidan handflata, sömnlös stickad stomme för jämn passform, helt siliconfri, kromfri och nickelfri så ingen allergirisk även för känsliga. Tvättbar i 40°C, slitstark och håller dussintals tvättar utan att förlora greppförmåga eller krympa. Jag brukar säga: du kan lyfta en 50-öring med dessa — så tunn känsla har du i fingertopparna. Finns i stl 6-12 så alla passar, även de med stora eller små händer. Hur många är ni som använder montagehandskar, och vilken storlek har du själv?",sp:["PU+Nitril","Sömnlös stickad","Siliconfri/kromfri/nickelfri","Tvättbar 40°C","49kr/st"],pr:"49kr/st",fm:["Stl 6-12"],di:[{q:"Storlek?"},{q:"Hur många är ni?"}],art:"ADF-874"},
{id:"aquaguard",n:"Aquaguard Thermo (Vinter/Olja)",cat:"Handskar",r:4,e:"💦",c:"#0284c7",tags:["verkstad","åkeri"],box:"24→12",p:"Aquaguard Thermo — 100% vattentät tack vare TRIPPELDOPPAD nitrilbeläggning, vilket är helt unikt på marknaden där alla andra tillverkare kör singel- eller dubbel-doppning. De flesta vattentäta blir genomsläppliga efter några veckors verkligt bruk, vår håller hela vintern ut. Sandygrip-textur på handflatan ger exceptionellt grepp även i olja, blöta ytor och på stålrör där vanliga handskar glider bort. Vinterfodrad med akrylfoder som isolerar utan att bli klumpig — du får extremt tunn känsla trots att den är varm, och hela handsken är riktigt elastisk. Jobbar du ute i slask, regn och olja på vintern så är det här räddningen.",sp:["Trippeldoppad (unikt)","100% vattentät","Sandygrip-textur","Akrylfoder","Elastisk"],pr:"99-119kr/st",fm:["Stl 8-12"],di:[{q:"Oljiga miljöer?"},{q:"Vattentät?"}],art:"HV-LKX970"},
{id:"ducavinter",n:"Perfectum Duca Vinter",cat:"Handskar",r:4,e:"❄️",c:"#1d4ed8",tags:["verkstad","bygg"],box:"24→12",p:"Perfectum Duca Vinter — äkta getskinn utvändigt och fleece vinterfoder invändigt. Getskinn är slitstarkare än kohud men fortfarande mjukt, så du behåller precisionen trots vinterskyddet — det är skillnaden mot grova arbetshandskar. Fingertopparna är förstärkta där slitaget alltid kommer först, och handsken går lätt på och av även med kalla stelnade händer. Finns också som ofodrad sommarvariant med samma design så du bygger ett system året om. Stl 7-11 vintervariant, 7-12 sommar. Vad använder gänget hos er för handskar på vintern idag?",sp:["Äkta getskinn","Fleece","Fingertopps förstärkt","Lätt på/av","Sommar finns"],pr:"99-149kr/st",fm:["Stl 7-11(vinter) 7-12(sommar)"],di:[{q:"Vinter eller sommar?"}],art:"6900(V)/7900(S)"},
{id:"ducasommar",n:"Perfectum Duca Sommar",cat:"Handskar",r:4,e:"☀️",c:"#f59e0b",tags:["verkstad"],p:"Duca Sommar — samma getskinn och design som vintervarianten fast utan fleece-foder, så du får mycket smidigare grepp och bättre fingerkänsla. Getskinn andas betydligt bättre än kohud, så händerna svettas inte lika mycket i sommarvärmen — ett klassiskt problem med grova arbetshandskar som gör att folk slänger av sig handskarna och skadar sig. Precision nog att hantera bultar och små skruvar utan att dra av sig handsken. Förstärkt tumme och pekfinger där slitaget kommer först. Perfekt för bygg, verkstad och montering vår och sommar. Hur ligger ni till med sommarhandskar idag?",sp:["Getskinn","Ofodrad","Andningsaktiv","Förstärkt tumme/pekfinger","Vår/sommar"],pr:"Kontakta",fm:["Stl 7-12"],di:[],art:"7900"},
{id:"perfhandsken",n:"Perfectum Handsken (Brand Glove)",cat:"Handskar",r:4,e:"🏆",c:"#f97316",tags:["verkstad","bygg","svetsare"],box:"24→12",bonus:"Mest uppskattade handsken alla kategorier",p:"Perfectum Handsken är vår absoluta flaggskepps-handske och den mest uppskattade i alla kategorier hos våra 18 000 kunder. Riktigt mockaläder som andas och sitter som en smäck från dag ett. Förstärkt tumme och pekfinger där slitaget alltid kommer först, spandex-stickad baksida med komfortdyna som ger vibrationsdämpning — du märker skillnaden klart efter en timme med slagborr eller mutterdragare. Air vent-hål för ventilation så händerna andas ut. Funkar för alla branscher: verkstad, bygg, lätt svetsarbete, montering. Sommarversion 149 kr, vintervariant 189 kr med fleece. Hur många hos er använder slagborr och mutterdragare dagligen?",sp:["Mockaläder","Vibrationsdämpning","Air vent","Förstärkt tumme/pekfinger","Mest uppskattade"],pr:"Sommar 149kr | Vinter 189kr",fm:["Sommar+Vinter"],di:[{q:"Storlek?"},{q:"Hur många är ni?"}]},
{id:"foamcut",n:"Foamcut C (Skärskydd)",cat:"Handskar",r:4,e:"🔪",c:"#4f46e5",tags:["verkstad"],box:"24→12",p:"Foamcut C — skärskydd nivå C enligt EN388: 4X42C, vilket är högsta vardagliga nivån (skala A-F, C är där riktiga arbetsmiljökrav börjar gälla). Stickad i HPPE (högpresterande polyetylen) blandat med tunn ståltråd, doppad i nitril på handflatan så den är både skärbeständig OCH oljebeständig OCH vattenresistent samtidigt. 2-i-1 montagehandske + skärskydd — du slipper byta handskar när du går från montage till hantering av plåtkanter eller glas. Nylanserad, smidig nog att passa alla med precision kvar i fingertopparna. Jobbar ni med plåt, glas eller vassa kanter där Arbetsmiljöverket kräver skärskydd?",sp:["Nivå C (EN388 4X42C)","HPPE+stål","2-i-1","Oljebeständig","Nylanserad"],pr:"79-129kr/st",fm:["Stl 6-12 (12/120)"],di:[{q:"Kräver ni skärskydd?"}],art:"HV-NJE3231"},
{id:"svetshandske",n:"Svetshandskar",cat:"Handskar",r:4,e:"🔥",c:"#b91c1c",tags:["svetsare"],p:"Svetshandskar som faktiskt håller sig mjuka över tid — det är hela poängen och där billiga svetshandskar helt missar. Billig variant är bra en vecka, sen blir den stenhård efter första riktiga dagen när svetten och värmen gjort sitt, och åker i soptunnan. Våra är oxidbehandlat mocka med bomullsfoder som isolerar utan att förlora smidighet i fingrarna. Funkar lika bra för TIG som MIG och MMA-svets — du behöver inte ha tre olika par hängande vid svetsstationen. Hur många svetsare är ni, och vilken process kör de mest?",sp:["Mjuka över tid","Oxidbehandlat mocka","TIG/MIG/MMA","Bomullsfoder"],pr:"Kontakta",fm:["Styckvis"],di:[]},

// ══ 5. KAP & SLIP ══
{id:"kapskivor",n:"Kapskivor Perfectum Premium",cat:"Kap & Slip",r:5,e:"⚙️",c:"#a855f7",tags:["verkstad","svetsare","bygg"],box:"100st (2 lådor) → 50st",bonus:"25% rabatt: 49→34,95. FLEX 125 vinkelslip (1700kr) vid 2 lådor. Paket 4995:-. Bara ~10 kvar!",p:"Perfectum Premium kommer från Rhodius XT-serien i Tyskland — samma fabrik som gör världsrankade kapskivor och motsvarar Tyrolit XGTS som vann världsbäst 2022. Men våra är 20-40% bättre i livslängd och ligger samma pris som 2021 trots förbättrad 2025-formula. Nyckeln är dubbel ythärdning — skivan vobbar eller splittras inte ens vid sneda kap. HydroProtect-behandling gör att den tål vatten och väte utan att försvagas som vanliga skivor gör efter några månader i lager. Tillverkade av högkvalitativ korund (aluminiumoxid) bunden i fenol-harts med 2 glasdukslager för säkerhet, och varje skiva testas destruktivt innan leverans — järn- och svavelfri så inget påverkar rostfritt. 49 kr/st ordpris, 34,95 i kampanj. Jag har plöjt igenom ett helt kylskåp med en enda skiva — de tål mer än folk tror. Kör ni 125 eller 230 mm, och hur många går det åt?",sp:["Rhodius XT tysk","20-40% längre vs Tyrolit","HydroProtect","Dubbel ythärdning","Destruktivt testade","Järn-/svavelfri"],pr:"49kr/st → 34,95 rabatt | Paket 4995:- inkl FLEX",fm:["125x0.8/1.0/1.5","180x1.5","230x1.9/2.5","50st/packe"],di:[{q:"125 eller 230?"},{q:"Slip?",lk:"slipskivor"},{q:"Lamell?",lk:"lamell"},{q:"Vision Pro?",lk:"visionpro"}],art:"6912510/515/6918015/6923019"},
{id:"slipskivor",n:"Slipskivor Ferox",cat:"Kap & Slip",r:5,e:"💿",c:"#9333ea",tags:["verkstad"],p:"Slipskivor Ferox — tysk tillverkning, samma teknologi som Bosch använder i sin premium-serie. Korund bundet med optimerad harts för metall, extra viktigt för rostfritt där du måste undvika värmeskador som ger regnbågsanlöpning och försämrar korrosionsbeständigheten på ytan. 125x7 och 180x7 mm, alltså 7 mm tjocklek för verklig slipning inte bara polering. Jämn finish utan att skivan glöder rött eller bränner materialet under. Jobbar ni mycket med svets-förslipning eller kantfasning så är det här daglig-skivan hos er. Samma ordpris som konkurrenterna men betydligt längre livslängd.",sp:["Ferox tysk","Korund","Rostfritt-säker","Jämn finish","7mm tjocklek"],pr:"49kr/st",fm:["125x7.0","180x7.0","230x7.0"],di:[],art:"200451/442/466"},
{id:"lamell",n:"Lamellskivor",cat:"Kap & Slip",r:5,e:"🌀",c:"#7c3aed",tags:["verkstad"],p:"Lamellskivor i P40, P60 och P80 — allt från grovjobb till finish i samma skivtyp, du väljer grovlek efter behov. P40 för att ta bort svetsfogar, rostkanter och grov oxid. P60 för utjämning efter grovslipning. P80 för finish innan lackering eller slutgiltig yta. Finns både i 125 och 180 mm diameter. Fiberpapperslameller i zirkonium-korund som roterar fram nytt skärkorn kontinuerligt — därför jämn slipning utan att glöda eller fastna i materialet som fasta skivor gör när de blivit blanka. En låda håller länge om du väljer rätt grovlek per jobb. Vad är vanligast för er — grovslipning eller finish?",sp:["P40/P60/P80","Zirkonium-korund","Självskärpande","125/180","Glöder ej"],pr:"Kontakta",fm:["125/180"],di:[],art:"204015/018/021"},
{id:"visionpro",n:"Vision Pro Cool (Premium Lamell)",cat:"Kap & Slip",r:5,e:"🌟",c:"#eab308",tags:["verkstad","svetsare"],box:"10st → 5st",bonus:"Ord 279→189kr (32% rabatt). Ferox borrsats värd 3300kr.",p:"Vision Pro Cool — FÖRSTA I SVERIGE med denna design, vilket är stor grej. Flygplanspropeller-inspirerad konstruktion med 3 stora mellanrum mellan lamellsektionerna som ger dig klar sikt på arbetsytan under slipningen (vanliga lameller blockerar sikten helt) OCH kylande luftströmning som sänker yttemperaturen med upp till 30% mot konventionella lameller. Perfekt på rostfritt och aluminium där värme annars förstör materialet eller deformerar tunnplåt. Fastnar INTE i kanter som traditionella lameller alltid gör — slutar med att du inte måste sänka hastigheten. Ord 279 kr, nu 189 kr — 32% rabatt. Jobbar ni mycket med rostfritt, alu eller tunnplåt?",sp:["Första i Sverige","Flygplanspropeller-design","30% kylare","Klar sikt","Rostfritt/alu"],pr:"189kr/st (ord 279, 32% rabatt)",fm:["P40/P60/P80"],di:[{q:"Rostfritt/alu?"}]},

// ══ 6. SMÖRJFETT ══
{id:"smorjfett",n:"Smörjfett LX-Polar",cat:"Smörjfett",r:6,e:"🔧",c:"#f97316",tags:["verkstad"],box:"2 lådor (50 tuber) → 1 låda (25)",bonus:"Vid 2 lådor: GRATIS batterispruta 690 bar (4000-6000kr). 340000 sålda/år. Bransch 140-190kr → Perfectum 89kr.",p:"Smörjfett LX-Polar är EP2 litiumkomplex utvecklat för nordisk marknad — testat i USA 2010 och blev snabbt standard i hela Skandinavien. Pumpbarhet ner till -33°C där konkurrenterna stannar vid -20°C, så ditt fett funkar även i januari på släpvagnsbromsar och kullager. Droppunkt 260°C vilket är mer än dubbelt mot vanligt litiumfett (100-120°C), och viskositet 220 centistoke jämfört med konkurrentens 50 cst — fettet stannar kvar där det ska även under hög belastning. Lube Shuttle-tuber med skruvgänga är helt kladdfria, slipper du det där klassiska fettet på händerna vid byte. Vi representerade Castrol förut — detta är en HELT annan nivå i test efter test. 340 000 tuber sålda senaste året, det säger något om marknadsacceptansen. Bransch ligger på 140-190 kr per tub, vi tar 89 kr. Vilken fettspruta har ni — vanligt lock eller skruvgängat Lube Shuttle?",sp:["EP2 litiumkomplex","-33°C pumpbarhet","260°C droppunkt","220 cst","340000 sålda/år","Lube Shuttle"],pr:"89kr/tub (bransch 140-190) | Maxi 99kr",fm:["LX 25 tuber","Maxi 50","Hugo Eff 0002 (skruv)"],di:[{q:"Vanligt/skruvgängat lock?"},{q:"Fettspruta?",lk:"fettspruta"}],art:"Hugo Eff 0002"},
{id:"fettspruta",n:"Fettspruta Batteri 690 bar",cat:"Smörjfett",r:6,e:"💉",c:"#ea580c",tags:["verkstad"],p:"Batterispruta med 690 bar maxtryck — normalt ligger handsprutor på 450 bar, så vår pressar igenom smutsiga och packade smörjnipplar som andra bara stannar vid. 100 gram fett per minut i flödeshastighet, batteridriven så du slipper pumpa manuellt — det sparar axeln rejält efter en hel dag med smörjning på entreprenadmaskin. Tar både Lube Shuttle-patroner (kladdfria, skruva fast) OCH klassiska 400 gram tuber. Jobbar du åkeri eller entreprenad där smörjnipplarna ofta är rostiga och packade med gammalt fett så är skillnaden enorm — du sparar 15-20 minuter per fordon. Värd 4 000-6 000 kr ute i handeln, GRATIS vid köp av 2 lådor smörjfett. Det är en no-brainer.",sp:["690 bar (normalt 450)","100gr/min","Batteridriven","Lube Shuttle + 400g","Sparar 15-20 min/fordon"],pr:"4000-6000kr (GRATIS vid 2 lådor fett)",fm:["Batteridragen"],di:[]},

// ══ 7. RENGÖRING ══
{id:"vatservetter",n:"Våtservetter Unicleaner",cat:"Rengöring",r:7,e:"🧻",c:"#14b8a6",tags:["verkstad","åkeri"],box:"50st → 12st → 6st",p:"Våtservetter Unicleaner med slät sida för sensibla ytor (instrument, skärmar, reception) och räfflad baksida för tuffare rengöring (oljiga händer, verktyg, motordelar). Scrubs-burken som de flesta verkstäder kör kostar 299 kr — våra ligger på ca 80 kr för 50-pack, alltså nästan en fjärdedel av priset för exakt samma funktion. Och de torkar INTE ut i burken som Scrubs börjar göra efter några veckor, och frostar inte heller vid kyla om de står i servicebil över natten. Lagom blöta så de biter direkt utan att droppa överallt. Använd på händer, verktyg, interiörer — allt. Hur många burkar går det åt hos er i månaden?",sp:["80kr (Scrubs 299)","Torkar inte ut","Frostar inte","Slät+räfflad","Samma funktion"],pr:"~80kr/burk",fm:["50st","12st","6st"],di:[{q:"Kör ni Scrubs?"}]},

// ══ 8. KLÄDER ══
{id:"understall",n:"Underställ Millers Bambu",cat:"Kläder",r:8,e:"👕",c:"#059669",tags:["verkstad","bygg","åkeri"],p:"Millers bambuunderställ — bambu är både andningsaktivt OCH temperaturreglerande, till skillnad från ren ull som bara håller värme. Naturligt antibakteriellt så det luktar inte svett lika snabbt som syntet eller polyester — kan bäras 2-3 dagar mellan tvätt utan att stinka, bra för montörer ute på långa projekt. Mjukt mot huden utan att klia som ull kan göra på känslig hud, absorberar fukt och transporterar bort den från kroppen. Halva priset jämfört med kvalitetsull som ligger över 1 500 kr — vi hamnar under 750. Finns i dam och herr, styckvis som överdel eller underdel så du bygger lager som du vill. Perfekt för er som jobbar i växlande temperaturer, inne och ute samma dag.",sp:["Bambu","Halva priset vs ull","Styckvis","Dam+herr","Antibakteriell","Temperaturreglerande"],pr:"Under 750kr",fm:["Överdel","Underdel"],di:[{q:"Kör ni ull?"},{q:"Hur många?"}],art:"5212(H)/5307(D)"},
{id:"strumptjock",n:"Perfectum Dura (Tjock strumpa)",cat:"Kläder",r:8,e:"🧦",c:"#b45309",tags:["verkstad","bygg","åkeri"],box:"12 par → 6 par",p:"Perfectum Dura är arbetsstrumpan som sålde 85 000 par senaste året — det säger en del om kvalitén och hur mycket folk beställer om. Rejäl frottéförstärkt sula som dämpar hela dagen i säkerhetsstövlar och på hårda betonggolv, kraftigt resår över vristen som FAKTISKT håller strumpan uppe istället för att glida ner i stöveln som billiga strumpor alltid gör — det är där folk klagar mest. Frotten absorberar fukt och dämpar stötar. Sitter klockrent utan att vandra runt under dagen. Stl 35-38, 39-42, 43-46, 47-50 så alla storlekar finns. Kör 6- eller 12-pack. Vilken skostorlek har du själv?",sp:["Frottésula","Kraftigt resår","Glider inte","Stövlar","85000 sålda"],pr:"89-99kr/par",fm:["Stl 35-38/39-42/43-46/47-50"],di:[{q:"Skostorlek?"},{q:"Hur många?"}],art:"69-(stl)"},
{id:"strumptunn",n:"Perfectum Dura Spring (Tunn)",cat:"Kläder",r:8,e:"🧦",c:"#16a34a",tags:["verkstad","bygg","åkeri"],box:"12→6",p:"Perfectum Dura Spring — den tunnare varianten av vår arbetsstrumpa för vår, sommar och höst. 80% bomull, 15% polyester, 5% elastan — förstärkt tå och häl där slitaget alltid kommer först, elastisk vriststrikning som håller formen tvätt efter tvätt utan att töjas ut. Går lika bra på jobbet som till vardags med sneakers — den ser ren och enkel ut i svart och matchar det mesta. Torkar snabbt och andas betydligt bättre än tjocka strumpor när det är varmt i skon på sommaren. Vid 300-packsbeställning trycker vi ER logga på skaftet för 59 kr/par — bra profilprodukt till personal eller kunder. Vad kör ni idag, tunt eller tjockt?",sp:["80% bomull","Funktion","Förstärkt tå/häl","Vår/sommar","Logga möjlig"],pr:"69-99kr/par (300st: 59kr eget tryck)",fm:["Stl 39-42/43-46/47-50"],di:[{q:"Tunna eller tjocka?"}],art:"69-10101"},

// ══ 9. SVETS ══
{id:"svetshjalm",n:"Svetshjälmar",cat:"Svets",r:9,e:"⚡",c:"#dc2626",tags:["svetsare"],p:"Svetshjälmar med automatisk mörkläggning — reaktionstid under 0,1 millisekunder så ljusbågen aldrig bränner ögat, vilket gamla statiska hjälmar fortfarande gör i uppstartsmomentet innan du hunnit fälla ner visiret. DIN 9-13 justerbart beroende på process: DIN 9-10 för TIG på tunnplåt, 11-12 för MIG, 13 för grov pinnsvets och höga ampere. Slipfunktion gör att du kan växla mellan slipning och svets utan att byta hjälm — stor produktivitetsvinst vid reparationssvetsning där du svetsar, slipar, svetsar igen. Litiumbatteri plus solceller i toppen så den är alltid laddad efter en arbetsdag under taklysrör. Hur många svetsare är ni, och vad kör de mest — TIG, MIG eller pinne?",sp:["Reaktion <0,1 ms","DIN 9-13","Slipfunktion","Solcell+batteri"],pr:"Se katalog",fm:["Diverse"],di:[{q:"Hur många svetsare?"}]},
{id:"svetsmaskin",n:"Svetsmaskiner",cat:"Svets",r:9,e:"🔌",c:"#b91c1c",tags:["svetsare"],p:"Svetsmaskiner i hela spektret — TIG, MIG/MAG och MMA (pinne). Modern inverterteknologi gör att maskinerna väger bara 5-15 kg trots att de levererar 200+ ampere, så du kan bära maskinen upp i en ställning istället för att dra 50 m kabel. TIG för rostfritt, aluminium och tunnplåt där du vill ha precis kontroll på värmeinmatning utan att bränna hål. MIG/MAG för produktionssvetsning när du ska lägga meter svets snabbt och konsekvent. MMA (pinne) för grovt jobb och utomhus där det blåser och MIG inte fungerar utan vindskydd. Vill ni ha dedikerade maskiner eller en kombimaskin som klarar flera processer i samma låda?",sp:["TIG/MIG/MMA","Inverter","5-15 kg","200+ amp","Kombi-möjligt"],pr:"Se katalog",fm:["Diverse"],di:[{q:"TIG, MIG eller pinne?"}]},
{id:"elektroder",n:"NC 312ER Super Speed",cat:"Svets",r:9,e:"⚡",c:"#991b1b",tags:["svetsare"],box:"16-20kg kartong → 4kg",p:"NC 312ER Super Speed är reparationselektroden som löser de där jobben när du inte vet exakt vad materialet består av. Funkar på rostfritt, fjäderstål, mangan, gjutjärn, verktygsstål, låglegerat stål — alla blandningar och gamla osäkra sammansättningar som äldre maskiner och jordbruksredskap ofta är gjorda av. Sprickbeständig och korrosionsbeständig svets i alla lägen (vertikal, tak, horisontellt) på både växel- och likström. Jämn båge, rent smälte, klänger inte materialet vilket är typiskt problem med billiga elektroder som lämnar slagg du måste slipa bort. Lätt att tända även första drag. Syrafri och rostfri svets. Vilken dimension kör ni mest — 2,5 eller 3,25?",sp:["Alla svetslägen","Sprickbeständig","Alla stålsorter","Lätt tänd","AC+DC"],pr:"2.00: 236kr(in)/599(ut)/680\n2.50: 165(in)/179(ut)\n3.25: 150(in)/449/221\n4.00: 160(in)",fm:["2.00x300 4kg","2.50x300 4kg","3.25x350 5kg","4.00x350 5kg"],di:[{q:"Vilken dimension?"}],art:"1612212/249250/244320/1614312"},
{id:"svetskl",n:"Svetskläder",cat:"Svets",r:9,e:"🧥",c:"#a21c1c",tags:["svetsare"],p:"Svetskläder — förkläden i crust-läder, svetsärmar, huvor och nackskydd. EN ISO 11611 certifierat specifikt för svetsning, vilket är lagkrav från Arbetsmiljöverket. Svets-läder tål gnistor och stänk utan att brinna till skillnad från vanliga arbetskläder som tänder vid första slagg-stänket. En enda glödrest i byxfickan och det är flera dagar av brännblåsor och plåster — inte värt sparsamheten på klädseln. Crust-läder andas bättre än split-läder och är mer slitstarkt, så en förklädd håller flera år. Kör ni mycket tak- eller vertikalsvets där stänket ramlar ner på benen?",sp:["EN ISO 11611","Crust-läder","Lagkrav AMV","Förkläden/ärmar/huvor"],pr:"Se katalog",fm:["Diverse"],di:[]},

// ══ 10. MASKINER ══
{id:"flex",n:"Vinkelslip FLEX 125",cat:"Maskiner",r:10,e:"🔩",c:"#6366f1",tags:["verkstad"],p:"FLEX 125 är vinkelslipen från tyska FLEX-Elektrowerkzeuge — varumärket som bokstavligen UPPFANN vinkelslipen 1954, därav namnet. 1010 W motor, 11 500 varv per minut, mycket jämn gång tack vare vibrationsdämpat handtag som sparar handlederna på långa jobb (karpaltunnelsyndrom är reellt i branschen). Tyskt proffsmonster som håller i 10+ år med daglig användning — Bosch Blå och Makita är i samma klass men Flex är originalet och har referensen. Soft-start gör att den inte rycker till vid påslag så du har full kontroll från start. GRATIS vid köp av 2 lådor Perfectum Premium kapskivor — värd ca 1 700 kr, alltså rena tjuvarna.",sp:["Uppfann vinkelslipen 1954","1010W","11500 varv","Vibrationsdämpad","Soft-start"],pr:"~1700kr (bonus vid 2 lådor kap)",fm:["1st"],di:[],art:"4383"},
{id:"slangvindor",n:"Slangvindor Blubird",cat:"Maskiner",r:10,e:"🔄",c:"#475569",tags:["verkstad"],box:"2st → 1st",p:"Slangvindor Blubird — visades på Köln verktygsmässa 2025, tysk producent som bara tillverkar åt de bästa märkena i Europa. Vi säljer under Perfectum-namnet med 5 års garanti vilket INGEN annan ger i Sverige. Lättaste slangvindan på marknaden, vilket märks tydligt när du drar ner och upp den flera gånger per dag. Tål direkt solljus utan att slangen sprödnar (normalt UV-förstör slang inom 2 år på soligt vägg), är olje-, fett- och dieselresistent och flexibel även i rejäla minusgrader. Finns i 2 dimensioner per vinda för både vatten och tryckluft. Har ni slangvindor idag, eller släpar ni slang på verkstadsgolvet?",sp:["Tysk producent","Köln 2025","5 års garanti","Lättaste","Tål solljus","Minus-flexibel"],pr:"Kontakta",fm:["Vatten","Luft","2 dimensioner/vinda"],di:[{q:"Har ni slangvindor?"},{q:"Tryckluft?"}]},
{id:"induktion",n:"Induktionsvärmare",cat:"Maskiner",r:10,e:"🌡️",c:"#9333ea",tags:["verkstad"],p:"Induktionsvärmare — elektromagnetisk induktion värmer enbart metallen, inte omgivningen runtomkring. 30 sekunder för att få en fastrostad bult glödande röd istället för 5 minuter med gasbrännare — och du bränner INTE packningen, kablarna eller lacken bredvid som gasbrännaren oundvikligen gör varje gång. Perfekt för fastrostade bultar, kullager som ska krympas på axel, rostade däcksbultar och avgaselement som svetsats fast av värmecykler. Ingen öppen brandrisk, ingen gasflamma i verkstaden, ingen gasackumulering mot lutande maskinkåpor. Stor tidsbesparing på gamla fordon där allt är fastrostat. Jobbar ni mycket med äldre bilar, skogsmaskiner eller lastvagnar?",sp:["30 sek vs 5 min gas","Ingen brandrisk","Enbart metallen","Ej skadar omgivning"],pr:"Kontakta",fm:["Diverse"],di:[{q:"Fastrostade bultar?"}]},
{id:"starthjalp",n:"Starthjälp RIMAC",cat:"Maskiner",r:10,e:"🚗",c:"#059669",tags:["åkeri","verkstad"],p:"Starthjälp från RIMAC — kompakta litium-jon booster-paket som startar allt från småbilar till tunga 24V-lastbilar. Finns både i 12V och 24V modeller, 20 000 mAh+ kapacitet så du får flera starts per laddning utan att behöva ladda om mellan fordon. USB-C snabbladdning så den är på 80% kapacitet på en timme, LED-arbetsljus inbyggt för nattarbete vid vägkanten. Klarar pålastade dieselmotorer som ligger döda efter helgen i minusgrader — där andra starthjälpspack bara ger upp. Perfekt i åkerirygan eller i serviceboxen på lastbil. En lastbil som inte startar i -20°C är guldvärd när ni kommer på plats snabbt och löser det utan bogsering.",sp:["RIMAC","12V/24V","20000+ mAh","USB-C snabbladd","LED-arbetsljus"],pr:"Se katalog",fm:["Diverse"],di:[]},
{id:"led",n:"LED-lampor",cat:"Maskiner",r:10,e:"💡",c:"#eab308",tags:["verkstad"],p:"LED-lampor i hela bredden — arbetsljus, ficklampor, pannlampor. 500-3 000 lumen beroende på modell, magnetfäste på alla arbetsljus, IP54-67 klassade för verkstadsmiljö med damm och stänk. Alla laddningsbara via USB-C så ni slipper kasta engångsbatterier varannan vecka som med gamla ficklampor — stor miljö- och kostnadsbesparing över tid. Arbetsljuset med stativ är favoriten i verkstad — lyser upp hela motorrummet vid nattskift utan skuggor där du ska se. Pannlampan med rödljus för när du inte vill blända kollegorna vid felsökning. Vilken typ behöver ni mest — arbetsljus, ficklampa eller pannlampa?",sp:["500-3000 lumen","Magnetfäste","IP54-67","USB-C laddning","Skuggfri"],pr:"Kontakta",fm:["Diverse"],di:[]},

// ══ 11. VERKTYG ══
{id:"gangsats",n:"Gängsats Mannesmann 110 delar",cat:"Verktyg",r:11,e:"🔩",c:"#334155",tags:["verkstad"],p:"Mannesmann gängsats — tyskt kvalitetsmärke från Remscheid, traditionellt verktygsdistrikt, 10 års garanti. 110 delar komplett sats: M2 till M18 med 70 gängtappar totalt (35 förtappar och 35 sluttappar) i olika stigningar, plus gängsnitt, gängklopphållare, gängkloppar och tappadapter. Allt i HSS-stål (High Speed Steel) som klarar stål, rostfritt och gjutjärn utan att rädda eggen. Värd 3 000-3 500 kr styckvis ute i handeln — vi har 400 st inköpta och kampanjar ut dem GRATIS vid köp av 2x25L spolarvätska. Vilken gängsats har ni i verkstan idag, och vad saknas av M-storlekar?",sp:["110 delar","M2-M18","70 gängtappar","10 års garanti","HSS-stål","Värd 3000-3500kr"],pr:"GRATIS vid kampanj",fm:["Komplett sats"],di:[]},
{id:"handverktyg",n:"Handverktyg & Väskor",cat:"Verktyg",r:11,e:"🛠️",c:"#334155",tags:["verkstad","bygg"],p:"Komplett handverktyg och verktygsväskor — nyckelsatser, hylsor, skruvmejslar, tänger, kombinationer, bitsboxar. 94-delars verktygsväska ingår vid samarbete, 108-delars vid större köp som kampanjerbjudande. Cromvanadin-stål i alla hylsor och nycklar (standardmaterial för proffskvalité), härdade skruvmejslar med magnetiska spetsar så skruvarna fastnar i verktyget och inte ramlar ner i motorn. Ergonomiska 2-komponenthandtag med mjukt grepp som inte glider när du har olja på händerna. Vad saknas mest i verkstan just nu — eller är ni fullt utrustade?",sp:["Cromvanadin","94/108-delarsväska","Magnetiska spetsar","2-komp handtag"],pr:"Väska ingår",fm:["Satser"],di:[]},
{id:"sagblad",n:"Mandrex Tigersågblad",cat:"Verktyg",r:11,e:"🪚",c:"#64748b",tags:["verkstad","bygg"],p:"Mandrex Tigersågblad — Made in Germany, ett av Europas ledande varumärken för reciprocating blades. 9 olika typer för alla material: 3X Fastcut (bi-metal med 8% kobolt, TRIPPELSIDIG tandning som kapar åt 3 håll utan att vända bladet — plunge cut utan att rycka), Multicut (allround inkl trä MED spik), Multicut Renovering (extra tjock för rivning), Multicut Varia (fintandad variabel pitch för plåt och tunna material), Steelcut (bi-metal specialdesignad för plåt, rör och profiler 2-8 mm), Hardcut TCT (tungsten carbide för härdat stål), Woodcut (krom-vanadin för rent trä), Toughcut (industriella diamantkorn för gjutjärn, kolfiber, cementskiva och betong), Ezygrind (diamantbelagd rörkapare). Säljs i 2-pack, universalskaft som passar alla tigersågar (AEG, Bosch, DeWalt, Hilti, Makita, Metabo). Vilka material jobbar ni mest i?",sp:["9 typer","Made in Germany","Alla material","8% kobolt (3X Fastcut)","Universalskaft","Passar alla tigersågar"],pr:"Se prislista",fm:["Diverse (2st förp.)"],di:[{q:"Vilka material?"}]},
{id:"brandsack",n:"Brandsläckare",cat:"Verktyg",r:11,e:"🧯",c:"#ef4444",tags:["verkstad"],p:"Brandsläckare — ABC-pulver 6 kg är standard för verkstad och fordon och klarar de tre vanligaste scenarierna (A=fasta material, B=vätskor, C=gas). CO2 för elrum där pulver förstör utrustning och skapar ren kontaminering. Skumsläckare för lösningsmedelslager. Årlig kontroll är lagkrav enligt SS 3656 via SVEBRA-certifierad tekniker, och hela släckaren måste bytas vart 5:e år oavsett skick. Vi kan leverera nya släckare OCH koppla upp er med kontrollfirma för årlig revision som sköter kontrollen automatiskt så ni slipper missa datum. Hur många har ni ute i lokal och fordon idag, och när gjordes senaste kontroll?",sp:["ABC-pulver 6kg","SS 3656","SVEBRA-kontroll","Årlig kontroll","Byte vart 5:e år"],pr:"Kontakta",fm:["Diverse"],di:[]},
];

// Kundtyper
const CTYPES=[
{id:"verkstad",n:"🔧 Verkstad",ps:["sprayer","brake","smorjfett","kapskivor","handskar","ergotec","vatservetter","bamse"]},
{id:"svetsare",n:"⚡ Svetsare",ps:["kapskivor","slipskivor","svetshandske","svetshjalm","svetsmaskin","elektroder","sprayer","brake","visionpro"]},
{id:"åkeri",n:"🚛 Åkeri",ps:["spolar","glykol","adblue","handskar","aquaguard","vatservetter","citr","skumglans","starthjalp"]},
{id:"bygg",n:"🏗️ Bygg",ps:["handskar","ergotec","ducavinter","kapskivor","sprayer","understall","strumptjock","algfasad"]},
{id:"skog",n:"🌲 Skog",ps:["kedja","handskar","foamcut","sprayer","understall","strumptjock"]}
];

// Invändningar
const OBJ=[
{q:"Vi har redan leverantör",a:"Perfekt — vi kompletterar med det de inte har. Testa en handske!",w:"Tala inte illa"},
{q:"Skicka mejl",a:"Mejl hamnar bland hundra. Testpaket — 2 min att utvärdera?",w:"Bara maila"},
{q:"Inte intresserad",a:"De flesta säger så innan de sett. Köper ni handskar nånstans?",w:"Ge upp"},
{q:"Ingen budget",a:"Budget för förbrukningsvaror har ni redan — ni testar en produkt ni redan köper.",w:"Acceptera"},
{q:"Ring i augusti",a:"Skickar varuprov nu — du testar, vi stämmer av i augusti!",w:"Bara boka om"},
{q:"Inte beslutsfattare",a:"Vem bestämmer om inköp? Jag ringer rätt person.",w:"Avfärda"},
{q:"Får inte ta emot gåvor",a:"Inga gåvor — varuprover för utvärdering. Som Würth-tester.",w:"Insistera gåva"},
{q:"Vi har ramavtal",a:"Ramavtal täcker inte allt. Specifikt på handskar/kem? Komplettera!",w:"Bryta ramavtal"},
{q:"Skicka prislista",a:"Vilka 3 produkter mest? Skräddarsyr offert.",w:"Generisk PDF"},
{q:"Vi köper lokalt",a:"Vi sitter i Skövde — mer lokalt blir det inte!",w:"Argumentera"},
{q:"Låter för bra",a:"18 000 kunder, Skövde sedan 2017. Ingen hake.",w:"Bli defensiv"},
{q:"Vad är haken?",a:"Haken: vi räknar med att du gillar det. Inget avtal.",w:"Undvika"},
{q:"Har inte tid",a:"45 sek: vi levererar handskar, kem, verktyg. Vilken adress?",w:"Prata längre"},
{q:"Nöjda med leverantör",a:"Inte ersätta — vi är back-up som alltid har grejerna.",w:"Attackera"},
{q:"Tionde som ringer",a:"Skillnaden: jag ber inte köpa. Testpaket, du bestämmer.",w:"Ignorera"},
{q:"Ring chefen",a:"Vad heter chefen? Kan jag nämna att vi pratat?",w:"Inte ta namn"},
{q:"Bara huvudleverantörer",a:"Fortsätt! Vi kompletterar — det lilla varje vecka.",w:"Dag 1 huvud"},
{q:"För dyrt",a:"Jämfört med vad? Totalkostnad med leverans = billigare.",w:"Sänk direkt"},
{q:"Testade er förut",a:"Vad funkade inte? Vi gjort om en hel del.",w:"Förneka"},
{q:"Ska tänka",a:"Vad specifikt? Kanske jag kan hjälpa med info?",w:"Bara okej"},
{q:"Kör Biltema/Jula",a:"Levererar till dörren, faktura, bättre löpande.",w:"Tala illa"},
{q:"Vi är för små",a:"Perfekt! Exakt sådana vi jobbar med — 5-20 anställda.",w:"Köp mer"},
{q:"Litar inte telefonsäljare",a:"Köper det. Därför vill jag komma ut. En kvart?",w:"Bli kränkt"},
];

// Skämt
const JOKES=[
{cat:"🎤 Öppning",items:["Sitter du i grävarn?","Brödfödan ska ju in oavsett tid och väder!","Femte växeln!","Hoppas jag inte ringer mitt i fikat","Ännu en telefonförsäljare — men trevligaste idag!","Stör mitt i nåt viktigt? Typ googla semesterresor?"]},
{cat:"😅 Självdiss",items:["Min chef sa jag ska bli jobbig — jag gör mitt bästa!","Inget är gratis — men det här kommer nära","Lovar att inte ringa igen... förrän om 2 månader","Skövdes trevligaste telefonförsäljare"]},
{cat:"🎬 Avslut",items:["Svetsmaskin också va? Nej tänkte väl det!","Ska jag skicka Tesla? Skämt... eller?","Verktygsvagn 339 delar på det? Om du inte vill?"]},
{cat:"🔄 Comeback",items:["Bra! Testa handskarna — skämta mer nästa gång","Roligare än förra kunden — han la bara på","Den sparar jag!"]},
{cat:"⏰ Stressad",items:["30 sekunder, lovar","Kortare än reklamfilm","Halv minut bara"]},
];

// Status pipeline
const STATUSES=[
{id:"ny",l:"🟡 Ny kontakt",c:"#f59e0b"},
{id:"skickad",l:"📦 Skickad",c:"#3b82f6"},
{id:"uppfoljning",l:"📞 Uppföljning",c:"#8b5cf6"},
{id:"order",l:"✅ Första order",c:"#10b981"},
{id:"aterkommande",l:"🔄 Återkommande",c:"#059669"},
{id:"forlorad",l:"❌ Förlorad",c:"#6b7280"},
];
