// Perfectum Produktdatabas V10 — Förbättrade pitches (3-4 meningar) + minst 5 fördelar/produkt
const PRODUCTS=[
// ══ 1. SPOLARVÄTSKA & GLYKOL ══
{id:"spolar",n:"Spolarvätska",cat:"Spolarvätska & Glykol",r:1,e:"💧",c:"#0ea5e9",tags:["åkeri","verkstad","bygg"],box:"2x25L → 1x25L",bonus:"Gängsats 110 delar (M2-M18) värd 3000-3500kr GRATIS vid 2x25L, pris 89→79kr/L",
p:"📋 ORIGINAL:\n\nVi jobbar med Swedhandling i Norrköping, en av Sveriges största leverantörer inom glykol, spolarvätska och AD-blue.\n\nDen är 93% aktivhalt/koncentrat, vilket innebär att du späder 3-6 gånger och på det viset har du en billig brukslösning.\n\nPris: 59-69kr/L\n\nFinns i format: 1-Liter (12-pack/24-pack etc etc) EJ FARLIGT GODS!! | 25L dunk (farligt gods avgift) | 205L fat\n\nVad skulle du säga går åt allra mest i förbrukningsväg?\n\n💡 TILLÄGG:\n\nKonkurrenter som Ahlsell/Würth säljer ofta färdigblandad 15-25kr/L — vår koncentrat blir 10-23kr/L i brukslösning. 1L-pack i 12/24-pack är standard till verkstad/åkeri eftersom EJ farligt gods. 25L dunk för industri, 205L fat för doseringsstation. Vi har även 90% koncentrat som späds 5-6x för riktigt billig brukslösning.",
sp:["✅ 93% aktivhalt — späd 3-6x och få Sveriges billigaste brukslösning","✅ Svanenmärkt som ENDA svenska spolarvätska","✅ Bioetanolbaserad — ingen metanol, säkrare arbetsmiljö","✅ 1L-pack är EJ farligt gods (slipper ADR-regler)","✅ Swedhandling är ISO 9001 + 14001-certifierad","✅ Fungerar ner till -20°C efter spädning, koncentrat klarar -40°C"],
discovery:"Hur mycket spolarvätska går åt per år, och kör ni koncentrat eller färdigblandat idag?",
di:[{q:"Koncentrat eller färdigblandad?"},{q:"Hur mycket per år?"},{q:"Glykol?",lk:"glykol"}],
pr:"59-69kr/L | Kampanj: 79kr/L vid 2x25L",fm:["1L (12/24-pack)","25L dunk","205L fat"]},

{id:"glykol",n:"Glykol",cat:"Spolarvätska & Glykol",r:1,e:"🧊",c:"#6366f1",tags:["åkeri","verkstad"],box:"2x25L → 1x25L",
p:"📋 ORIGINAL:\n\nVi jobbar med Swedhandling i Norrköping, en av Sveriges största leverantörer inom glykol, spolarvätska och AD-blue.\n\nGlykolen är även 93% aktivhalt vilket innebär att du kan späda den lite mer än hälta hälta.\n\nKlass 3 klassad longlife glykol så den står sig 5 år i maskineriet och på dunke.\n\nVilka färger kör du med?\nBlå: Vanligaste färgen (etylen) - 69KR/L\nRöd: 69-79kr/L\nGrön: (miljöglykol, Propylen) 79-99Kr/L\nGul: (volvo maskiner etc) 69-79kr/L\nTransparent/genomskinlig: (går att blanda med andra färger) 79-89Kr\n\nFinns i format: 4L / 20L / 25L / 205L fat\n\n💡 TILLÄGG:\n\nLonglife klass 3 är industristandard — vanlig glykol håller 2-3 år, vår 5 år vilket sparar rejält i maskinparker. Transparent är kungsgrepp om ni har blandade system eftersom den kan blandas med alla färger utan problem. Grön propylen är miljöval för t.ex. livsmedelsindustri.",
sp:["✅ 93% aktivhalt vs standardglykol 50-60%","✅ Klass 3 longlife = 5 års hållbarhet i maskineriet","✅ ASTM D3306 + FSD 8704 (svensk försvarsstandard)","✅ Nitrit- och silikatfri — alu-säker för moderna motorer","✅ 5 färger täcker alla fordonsmärken","⚠️ Blanda ALDRIG olika färger utan kompatibilitetskontroll"],
discovery:"Vilken färg kör ni på fordonen, och behöver ni även till maskiner?",
di:[{q:"Vilken FÄRG?"},{q:"Maskiner eller fordon?"},{q:"AD-Blue?",lk:"adblue"}],
pr:"69-99 kr/L beroende färg",fm:["4L","20L","25L","205L fat"]},

{id:"adblue",n:"AD-Blue",cat:"Spolarvätska & Glykol",r:1,e:"🔵",c:"#3b82f6",tags:["åkeri"],box:"205L → 25L",
p:"📋 ORIGINAL:\n\nVi jobbar med Swedhandling i Norrköping, en av Sveriges största leverantörer inom glykol, spolarvätska och AD-blue.\n\nDiesel-tillsats som rinner bara ur — inget man lagrar länge.\n\n💡 TILLÄGG:\n\nFinns i 10L, 25L, 205L fat och 1000L IBC med volymrabatt. ISO 22241-certifierad för alla SCR-motorer i moderna lastbilar och maskiner. Swedhandling är en av Sveriges största leverantörer så leveranssäkerhet och prissättning är bland de bästa i landet.",
sp:["✅ Lagkrav Euro 6 — utan den går motorn i reducerat läge","✅ Förbrukning 3-5% av diesel (planera volym efter det)","✅ ISO 22241-certifierad (skyddar SCR-systemet)","✅ Egen tankbil från Swedhandling vid IBC","✅ Volymrabatt från 10L dunk till 1000L IBC","✅ Universal för Volvo, Scania, MAN, Mercedes — samma formula"],
discovery:"Hur mycket diesel tankar ni per månad så räknar jag ut behovet?",
di:[{q:"Hur mycket i månaden?"}],
pr:"Volymbaserat",fm:["10L","25L","205L","1000L IBC"]},

// ══ 2. SPRAYER & AEROSOLER ══
{id:"sprayer",n:"Sprayer — Översikt",cat:"Sprayer",r:2,e:"🧴",c:"#ef4444",tags:["verkstad","svetsare","bygg"],box:"24st blandlåda → 12st dussin",bonus:"Paket 24st + kylsnyckelsats = 2995kr. Styckpris från 12st: 129kr",
p:"📋 ORIGINAL:\n\nAresoler på burk går ju alltid åt alltså sprayer, kunden innan tog lite VD40 alltså allroundspray, Brakeclean och någon rostlösare. Vilka sprayer skulle du säga går åt allra mest för dig?\n\nAresoler på burk (sprayer):\n• Alla våra sprayer har vi gjort med Tony Rikardsson vet du, jag är inte bitter. Nu gör man ju en del parodi på han men man får inte glömma bort att han var en jävel på speedway.\n• Alla våra sprayer ligger på 149 kr/burk bortsett brakeclean eller maskinrent som den heter här, den är ju 60 kr billigare och då är det ett jäkla tryck i sprayerna, du får ut allt och en jäkla massa teflon.\n\nEv frågor: Vad är aresoler för något?\nSvar: Sprayer, alltså brakeclean, fönsterputs osv.\n\nEv frågor: Hur många sprayer är det i en låda?\nSvar: Vanligtvis 24 st men då är det ju en blandlåda, då kan man blanda hur man vill utav dom sprayerna som används. 24 st av varje funkar ju inte det förstår jag med.\n\nEv frågor: Kan man bryta ett packe? Eller de är för mycket?\nSvar: Absolut, är det för mycket för dig kan du blanda några sprayer på ett dussin (12 st).\n\n💡 TILLÄGG:\n\n14 typer i sortimentet: Brakeclean, Rostlösare, Allroundspray PTFE (bättre än VD40), Kedjespray, Krypfett/Mos2, Kylspray, Teflonspray, Citrus A, Glasrent, Multiskum, Kopparspray, Kontaktspray, Keramikpasta, Tjärspray. Blandlåda 24st är normalen, dussin 12 vid brytning. Paket 24st + kylsnyckelsats för 2995kr — styckpris från 12st är 129kr.",
sp:["✅ 14 sprayer som täcker verkstad, svets och åkeri","✅ 149 kr/burk inköp (butikspris 159-199 kr)","✅ Brakeclean rabatterad — 60 kr billigare","✅ Blandlådor 24-pack efter eget behov","✅ Paket 24 + kylsnyckelsats = 2995 kr","✅ Tony Rikardsson står bakom serien (trovärdighet)"],
discovery:"Vilka tre sprayer använder ni mest idag?",
di:[{q:"Brakeclean?",lk:"brake"},{q:"Rostlösare?",lk:"rost"},{q:"Allround/VD40?",lk:"allround"},{q:"Kedjespray?",lk:"kedja"},{q:"Krypfett?",lk:"kryp"},{q:"Kylspray?",lk:"kyl"},{q:"Teflon?",lk:"tefl"},{q:"Citrus A?",lk:"citr"},{q:"Glasrent?",lk:"glas"},{q:"Multiskum?",lk:"multi"},{q:"Kopparspray?",lk:"kopp"},{q:"Kontaktspray?",lk:"kont"}],
pr:"149-159kr/burk | Paket 24st: 2995kr",fm:["Enstaka","Dussin 12","Blandlåda 24"]},

{id:"brake",n:"Brakeclean/Maskinrent",cat:"Sprayer",r:2,e:"🔵",c:"#3b82f6",tags:["verkstad","svetsare"],
p:"Mest sålda sprayen i hela sortimentet — aceton/heptan-baserad fettlösare som avdunstar på 30 sekunder utan att lämna rester. Tar bromsdamm, olja, fett och vägsmuts i ett drag, och till skillnad från generiska bromsrent 'ryker' den inte kvar på ytan. Vi säljer den 60 kr billigare än resten av sprayserien eftersom volymen är så hög — du får samma kvalitet som märkesvaran för ett pris som matchar generiskt.",
sp:["✅ Mest sålda sprayen — volymrabatt ger lägre pris","✅ Aceton/heptan-bas — industristandard för snabbtorkning","✅ Torkar helt på 30 sekunder utan restprodukt","✅ Tar bromsdamm, olja, fett och vägsmuts","✅ 60 kr billigare än övriga i serien","✅ Säker på lackerade ytor (kort kontakttid)"],
discovery:"Hur många burkar Brakeclean går det åt hos er i månaden?",
di:[{q:"Hur många i månaden?"}],
pr:"~89-99kr",fm:["Enstaka","Dussin"],art:"000000"},

{id:"rost",n:"Rostlösare",cat:"Sprayer",r:2,e:"🟠",c:"#f97316",tags:["verkstad"],
p:"Löser rost via kapillärverkan — den kryper in UNDER oxiden istället för att bara lägga sig på ytan som billiga rostlösare gör. Verkar i 5-10 minuter på normalt fastrostade muttrar, upp till 30 min på riktigt illa rostade. Lämnar en smörjfilm efteråt så gängan inte skär fast igen när du drar åt, och tar även gnissel i gångjärn och lås. En burk räcker typiskt till 15-20 fastrostade förband.",
sp:["✅ Kapillärverkan — kryper in under oxiden","✅ Löser rost på 5-10 min (normalt), 30 min (värsta)","✅ Lämnar smörjfilm efter = ingen återfastning","✅ Tar gnissel i lås, gångjärn och vredskruvar","✅ 15-20 fastrostade förband per burk","✅ Säker för lack och gummi vid normal kontakttid"],
discovery:"Har ni mycket fastrostade grejer på äldre fordon eller maskiner?",
di:[],
pr:"149kr",fm:["Enstaka","Dussin"],art:"942100"},

{id:"allround",n:"Allroundspray PTFE",cat:"Sprayer",r:2,e:"🟢",c:"#10b981",tags:["verkstad"],
p:"Rak uppgradering mot VD40 — samma pris men med äkta PTFE (Teflon) som faktiskt smörjer istället för att bara lägga en våtfilm. Vattenutträngande (som VD40) plus korrosionsskydd plus smörjning i ett, så du slipper tre separata produkter. Funkar på lås, gångjärn, elkontakter, verktyg och kabelvaljer. När kunder bytt från VD40 till vår så minskar förbrukningen typiskt med 30-40% eftersom smörjningen håller längre.",
sp:["✅ Äkta PTFE (Teflon) — smörjer, inte bara blöter","✅ Ersätter VD40 till samma pris eller billigare","✅ Vattenutträngande + korrosionsskydd + smörjning i ett","✅ 30-40% mindre förbrukning än VD40","✅ Säker på elkontakter (ingen konduktivitet)","✅ Samma applikationer som VD40 — ingen rutin-ändring"],
discovery:"Kör ni VD40 idag? Då är den här en ren uppgradering för samma pris.",
di:[{q:"Kör ni VD40?"}],
pr:"149kr",fm:["Enstaka","Dussin"],art:"250200"},

{id:"kedja",n:"Kedjespray",cat:"Sprayer",r:2,e:"⛓️",c:"#8b5cf6",tags:["skog"],
p:"Bygger en seg hartsfilm som klibbar fast på kedjan och INTE slungas av vid högt varvtal — det som händer med billigare sprayer. Vattenavvisande så den klarar regn och snö utan att spolas bort, vilket är avgörande för motorsåg i skogen. Kryper in mellan länkarna där det behövs mest, och funkar lika bra på industrikedjor, cykelkedjor och transportband. Räcker typiskt 3-4x längre än olja eftersom vidhäftningen är så mycket starkare.",
sp:["✅ Hartsfilm som klibbar — slungas ej av vid varvtal","✅ Vattenavvisande — fungerar i regn och snö","✅ Kryper in mellan kedjans länkar","✅ Funkar: motorsåg, industri, cykel, transportband","✅ 3-4x längre hållbarhet än vanlig kedjeolja","✅ Reducerar kedjeutslitning med 20-30%"],
discovery:"Kör ni motorsåg, skogsmaskin eller industrikedja — doseringen är olika.",
di:[],
pr:"149kr",fm:["Enstaka"],art:"070106"},

{id:"kryp",n:"Krypfett/Mos2",cat:"Sprayer",r:2,e:"💛",c:"#eab308",tags:["verkstad"],
p:"MoS2 (molybdendisulfid) är samma grundämne som används i militär och flygindustri för extrema laster. Kryper in i springor och glidytor via kapillärverkan, fyller mikroytorna och minskar friktion med upp till 40%. Mellanting mellan flytande smörjmedel och fett — ger längre hållbarhet än allroundspray men är lättare att applicera än tubfett. Efter behandling lossas bultar 6-12 månader senare utan problem.",
sp:["✅ MoS2 — militär- och flygindustri-standard","✅ Kapillärverkan — kryper in där fett inte når","✅ 40% friktionsminskning vid belastade ytor","✅ Mellanting mellan spray och tubfett","✅ Bultar lossas lätt 6-12 mån senare","✅ Klarar högt tryck och hög temperatur"],
discovery:"Har ni svåråtkomliga glidytor eller gängor som behöver smörjas regelbundet?",
di:[],
pr:"149kr",fm:["Enstaka"],art:"240200"},

{id:"kyl",n:"Kylspray/Skärspray",cat:"Sprayer",r:2,e:"❄️",c:"#06b6d4",tags:["verkstad"],
p:"Förlänger borr-livslängd med 2-3 gånger genom att kyla skäreggen under bearbetning — utan kylning får du härdning och nedslitning direkt. Minskar friktion så matningen går jämnare, och spolar bort spånor samtidigt så de inte värmer upp skäret. Ett sprut per drag räcker på upp till 10 mm borrning, vilket gör den billig per arbete. Fungerar utmärkt på rostfritt, titan och härdat stål där vanlig borrolja misslyckas.",
sp:["✅ 2-3x längre borr-livslängd","✅ Kyler skäreggen — förhindrar härdning","✅ Spolar bort spånor samtidigt","✅ Ett sprut räcker per 10mm borrning","✅ Funkar på rostfritt, titan, härdat stål","✅ Billigare per hål än oljeskärvätska"],
discovery:"Hur mycket borrar och svarvar ni, och vilka material är vanligast?",
di:[],
pr:"149kr",fm:["Enstaka"],art:"72012"},

{id:"tefl",n:"Teflonspray PTFE",cat:"Sprayer",r:2,e:"⚪",c:"#64748b",tags:["verkstad"],
p:"Ren PTFE med friktionskoefficient 0,04 — halkigt som is och lägre än nästan alla andra smörjmedel. Torkar snabbt till en torr film som INTE samlar damm som oljor gör, vilket är avgörande på skenor, lager och gångjärn där damm blir slipmaterial. Perfekt för teflonbehandling av rörliga delar som behöver exakt rörelse utan kladd — rullmekanismer, skjutluckor, fönster. Applikationen är torr efter 3-5 minuter.",
sp:["✅ Rent PTFE — friktionskoefficient 0,04 (som is)","✅ Torr film — samlar INTE damm som oljor","✅ Perfekt för skenor, lager, gångjärn","✅ Torkar på 3-5 minuter","✅ Kladdfri yta — inga fingeravtryck","✅ Temperaturtålig från -50 till +250°C"],
discovery:"Vad smörjer ni på rörliga delar idag?",
di:[],
pr:"149kr",fm:["Enstaka"],art:"520800"},

{id:"citr",n:"Citrus A",cat:"Sprayer",r:2,e:"🍊",c:"#f59e0b",tags:["verkstad"],
p:"D-limonen från apelsinskal — naturligt lösningsmedel som är kraftigt på klister och tjära men skonsamt mot lack och plast. Tar dekaler, tuggummi, tjärstänk, kåda och även gamla limrester från tejp. Fantastisk citrusdoft så kunderna gillar när man använder den i kupén, till skillnad från aceton-baserade rengöringsmedel. Verka 30-60 sekunder så släpper klistret — skrapa försiktigt bort med plastskrapa.",
sp:["✅ D-limonen — naturligt från apelsinskal","✅ Lack- och plastsäker","✅ Tar dekaler, tuggummi, tjära, kåda","✅ Fantastisk citrusdoft (kundvänlig)","✅ Verkar på 30-60 sekunder","✅ Fungerar där aceton skulle skada lacken"],
discovery:"Har ni problem med klisterrester eller gamla dekaler någonstans?",
di:[],
pr:"149kr",fm:["Enstaka"],art:"550200"},

{id:"glas",n:"Glasrent",cat:"Sprayer",r:2,e:"🪟",c:"#0ea5e9",tags:["verkstad"],
p:"Uppgraderad formula 2024 — strimfri även på stora ytor som lastbilsrutor och butiksfönster där vanliga glasrent lämnar ränder. Ammoniakfri så den skadar inte plast, listgummi eller tintad film, vilket är viktigt på moderna bilar. Tar nikotin, vägfilm, fett och fingeravtryck i ett drag. Torkar snabbt utan att rinna, vilket gör den idealisk för vertikala glas som skyltfönster och MC-visir.",
sp:["✅ Strimfri även på stora ytor","✅ Ammoniakfri — säker på plast och listgummi","✅ Säker för tintad film (viktigt för moderna bilar)","✅ Tar nikotin, vägfilm, fett, fingeravtryck","✅ Torkar snabbt utan att rinna","✅ Funkar: bilrutor, butiksfönster, MC-visir, speglar"],
discovery:"Kör ni personbilsverkstad? Kunderna frågar efter den.",
di:[],
pr:"149kr",fm:["Enstaka"],art:"340100"},

{id:"multi",n:"Multiskum",cat:"Sprayer",r:2,e:"🫧",c:"#a855f7",tags:["åkeri"],
p:"Interiör-rengöring för lastbilshytter, bilkupéer och skåpbilar — skummar upp smutsen och torkas bort med fuktig duk, inget vatten eller spolning behövs. Funkar lika bra på textilsäten, plast, läder och dörrpaneler utan att blekta eller krympa materialet. Särskilt bra på lastbilshytter där bilar inte kan tas till tvätthall — applicera i morgon, kör hela dagen, torka på kvällen. En burk räcker till ungefär 10-15 interiör-rengöringar.",
sp:["✅ Inget vatten behövs — funkar i fordon","✅ Säker på textil, plast, läder","✅ Blekter ej eller krymper materialet","✅ Perfekt för lastbilshytter (kan inte tas till tvätt)","✅ 10-15 rengöringar per burk","✅ Tar kaffefläckar, dieselstänk, vardagssmuts"],
discovery:"Tvättar ni lastbilshytterna regelbundet?",
di:[],
pr:"149kr",fm:["Enstaka"],art:"101100"},

{id:"kopp",n:"Kopparspray",cat:"Sprayer",r:2,e:"🟤",c:"#b45309",tags:["verkstad"],
p:"Anti-seize som tål upp till 1100°C — för avgasgrenrör, lambdagängor, bromssadel-bultar och tändstift där aluminium och stål riskerar att kallsvetsas fast. Kopparpartiklarna fungerar som mikroskopiska kullager mellan gängorna så bultar lossas utan problem även år senare. OBSERVERA: ska aldrig användas på aluminiumgrenrör eller fälgbultar — där fräter koppar sönder aluminium via galvanisk korrosion. Använd keramikpasta istället på alu.",
sp:["✅ 1100°C värmetålig (avgasgrenrör, lambdasond)","✅ Anti-seize — bultar lossas år senare","✅ Koppar = mikroskopiska kullager mellan gängor","✅ Lambdasond, tändstift, bromssadel-gängor","⚠️ EJ på aluminium (galvanisk korrosion)","✅ En burk räcker till 50-80 applikationer"],
discovery:"Hur ofta byter ni avgaskomponenter eller bromssadelbultar?",
di:[],
pr:"149kr",fm:["Enstaka"],art:"060100"},

{id:"kont",n:"Kontaktspray",cat:"Sprayer",r:2,e:"⚡",c:"#eab308",tags:["verkstad"],
p:"Trycker ut fukt från elkontakter och löser oxid på kopparanslutningar — 70% av alla elfel i fordon är egentligen dålig kontakt snarare än trasiga komponenter. Säker på modern elektronik som ECU, ABS-pumpar och styrdosor, till skillnad från klorerade rengöringsmedel som kan lösa upp lackerade kretskort. Efter behandling bildas en tunn skyddsfilm mot framtida korrosion. Spraya, låt verka 30 sek, blås av med tryckluft — kontakterna är som nya.",
sp:["✅ 70% av elfel är kontakter, inte komponenter","✅ ECU/ABS-säker — löser inte lack på kretskort","✅ Trycker ut fukt (vattenutträngande)","✅ Löser oxid på kopparanslutningar","✅ Skyddsfilm mot framtida korrosion","✅ Fungerar på modern fordonselektronik"],
discovery:"Jobbar ni mycket med elfelsökning på fordon?",
di:[],
pr:"149kr",fm:["Enstaka"],art:"4148100"},

{id:"kera",n:"Keramikpasta",cat:"Sprayer",r:2,e:"⚪",c:"#d1d5db",tags:["verkstad"],
p:"Anti-seize upp till 1400°C — 300°C högre än kopparpasta och neutral mot aluminium där kopparn fräter sönder metallen. Det gör den till förstahandsvalet på moderna bilar med alu-grenrör, hjulnav och fälgbultar. Ingen metallkontakt så ingen galvanisk korrosion kan uppstå, samtidigt som gängorna hålls rörliga i åratal. Även MC-avgassystem med titan eller rostfritt fungerar perfekt.",
sp:["✅ 1400°C värmetålig (300°C över koppar)","✅ Aluminium-säker — ingen galvanisk korrosion","✅ Standard på moderna bilar (alu-grenrör, alu-nav)","✅ MC-avgassystem i titan/rostfritt","✅ Hjulnav och fälgbultar utan risk","✅ Ersätter koppar i nästan alla moderna applikationer"],
discovery:"Har ni alu-grenrör eller fälgbultar som ni brukar fastna med?",
di:[],
pr:"149kr",fm:["Enstaka"],art:"200792"},

{id:"tjar",n:"Tjärspray",cat:"Sprayer",r:2,e:"⬛",c:"#1e293b",tags:["åkeri"],
p:"Löser asfalt, tjära och bitumen utan att skada modern 2K-vattenbaserad billack — skonsammare än klassiska tjärborttagare som kan blekta metallic-färger. Perfekt efter arbete på nyasfalterade vägar eller vid stensprut från grusvägar. Spraya, låt verka 2 minuter, torka med mikrofiberduk — ingen gnuggning eller skrapning behövs. En burk räcker till komplett sidosanering av en lastbil.",
sp:["✅ 2K-lack säker (vattenbaserad modernlack)","✅ Skonsammare än gamla tjärborttagare","✅ Blekter ej metallic-färger","✅ Löser bitumen, asfalt, tjära","✅ Verkar på 2 minuter — ingen gnuggning","✅ En burk = komplett sida på lastbil"],
discovery:"Kör ni många lastbilar eller bilar med motorvägstrafik?",
di:[],
pr:"149kr",fm:["Enstaka"],art:"70022"},

// ══ 3. AVFETTNING & KEM ══
{id:"bamse",n:"Bamse Alkalisk Special",cat:"Avfettning & Kem",r:3,e:"🐻",c:"#dc2626",tags:["verkstad","åkeri","bygg"],box:"205L fat → 25L dunk → 5L",bonus:"108-delars verktygsväska (2000kr) + gottepåse gratis vid köp",
p:"📋 ORIGINAL:\n\nMANUS ALKALISK SPECIAL AVFETTNING (Bamse)\n\nIdag ska jag ta upp en produkt som är den mest sålda av alla produkter sen starten för 30 års sen då vi körde igång. Produkten vi pratar om är alltså vårt bamse avfettning, alkalisk special som Du varit väldigt nöjd med eller hur? Det är det gamla receptet som vi nu har börjat återanvända igen, då den gamla fabriken åter har öppnat sin tillverkning igen på det gamla BAMSE AVFETTNING SPECIAL.\n\nDet är det avfettningsmedlet som alla våra kunder använder tex Modo Skog, Assi Domän, Stockholms kommun, svenska kriminalvården och ca 6000 åkerier.\n\nDet är det avfettningsmedlet som Du använder till Dina maskiner, traktorer, bilar etc. Du späder från 50 ggr och neråt så det blir väldigt ekonomiskt som säkert märkt. Kunderna brukar säga att brukslösningspriset blir runt 2 kr/lit och det får Du hålla med om att det är billigt eller hur?\n\nDet fina med är alltså att Du får bestämma själv i hur starkt Du vill ha det. Andra avfettningsmedel har en aktivhalt på ca 18-23% men Perfectums ligger på 87% i aktivhalt och det innebär att om Du använder det koncentrerat så försvinner lacken på ditt fordon. Du kan även använda det på obehandlat aluminium där det bildas aluminiumoxid. Där fungerar det ruskigt bra.\n\nDessutom är det helt miljövänligt, det innehåller inga lösningsmedel eller petroleumprodukter. Detta gör vårt medel godkänt på kemikaliesvepets vita lista i Göteborg.\n\nDet fina är ju att Du bara lägger på det med typ en lågtryckssprua eller om Du doserar direkt från högtryckstvätten. Sedan är det bara att vänta några minuter innan Du kan spola av smutsen utan bearbetning.\n\nNu ska Du få höra ordinarie pris på ett fat idag är 99,90 men idag får Du möjlighet att teckna en order med 10% RABATT och endast behöva ta 60 liter...... dvs 89:- kr/lit.\n\n💡 TILLÄGG:\n\nDenna tar bokstavligtalat allt inklusive miljöoljor och fastbrända oljor. Vill du ha något mot asfalt behöver du en kallavfettning (Prickbort). Fungerar både i högtryckstvätt och vanliga handsprutor. Ihop med köp: 108-delars verktygsväska värd 2000kr + gottepåse med våra storsäljare (handskar, sockar, sprayer, kapskivor) och kataloger.",
sp:["✅ 87% aktivhalt vs konkurrenter 18-23%","✅ Späds 50x → brukspris 2-4 kr/L (billigast)","✅ Stockholms kommun, Kriminalvården, 6000 åkerier","✅ 30 år på svenska marknaden","✅ Kemikaliesvepets vita lista","✅ Miljövänlig — inga lösningsmedel eller petroleum","⚠️ Koncentrat tar lacken — måste spädas"],
discovery:"Vad kör ni på avfettning idag?",
di:[{q:"Alkaliskt eller kall?"},{q:"Prickbort?",lk:"prickbort"},{q:"Skumglans/Foamer?",lk:"skumglans"}],
pr:"119-149kr/L | Ord: 99,90/fat",fm:["5L","25L dunk","205L fat"]},

{id:"prickbort",n:"Prickbort Kallavfettning",cat:"Avfettning & Kem",r:3,e:"✨",c:"#e11d48",tags:["verkstad","åkeri"],box:"2x25L → 1x25L",
p:"📋 ORIGINAL:\n\nKallavfettning Prickbort (späder man inte)\n\n• Prickbort känner du säkert till, finns 3 olika varianter där vi har den starkaste\n• Denna ligger på 119 kr/l och tar bort allt som heter flygrost, gödsel, oljefläckar, kåda, gammal smuts som suttit i\n• Denna är så jäkla stark så här tillkommer det en farlig gods avgift men den betalar jag bara så du får testa denna\n\n💡 TILLÄGG:\n\nHögtryckscleaner för svårlösliga oljeföroreningar, asfalt och vägsmuts. Spraya på, vänta 2 minuter, skölj av. Svensktillverkad, biologiskt nedbrytbar — perfekt komplement till Bamse eftersom Bamse inte tar asfalt. 25L dunk är standardformat.",
sp:["✅ Starkaste av 3 Prickbort-varianter","✅ Späds INTE (tidsbesparing + ingen blandfel)","✅ Löser asfalt, flygrost, gödsel, oljespill","✅ Svensktillverkad","✅ Biologiskt nedbrytbar","✅ Kemikaliesvepet godkänd","✅ 2 minuter verkan → skölj → klart"],
discovery:"Rengör ni lastbilar, maskiner eller bilar på egen anläggning?",
di:[],
pr:"119kr/L (25L)",fm:["25L dunk"],art:"197"},

{id:"skumglans",n:"Skumglanschampo/Foamer",cat:"Avfettning & Kem",r:3,e:"🫧",c:"#0891b2",tags:["åkeri","verkstad"],box:"25L → 5L",
p:"📋 ORIGINAL:\n\nSkumglanschampo\n\nDe här vet du ju vad det är om du äger en foamer. Maskinen blir en grädtårta som man dammar av, går hur snabbt som helst. Den ligger på 149 kr/l men då har du två preparat i ett. Den tar bort all skit och sen har du bilvård på det, motsvarande bilvaxschampo.\n\nFråga som kan dyka upp: Hur använder jag det?\nIngen raketforskning, kallavfettning lägger du på som den är med hetvatten eller högtryck. Bamse likaså men den späder du. Detsamma med Skumglans men där behöver du en foamlancer så det blir en grädtårta.\n\nHar du dom i 5 liters?\nHar dom i 25 l. Funkar det för dig? Om inte svarar man, \"jag ber lagret lösa det på en 5 l\".\n\n💡 TILLÄGG:\n\n2-i-1 — rengöring + bilvård i samma produkt. Foamer/foamlancer på högtryckstvätt eller vanlig spraypistol fungerar. Lägger skyddsfilm efter tvätt som ger extra tid till nästa behov. 149kr/L men du får två preparat så det är egentligen 75kr/L per funktion.",
sp:["✅ 2-i-1: tvätt + vax i samma moment","✅ Hydrofob skyddsfilm håller i veckor","✅ Nästa tvätt — bara skölj, ingen skrubbning","✅ Foamlance eller högtryck","✅ Ersätter både schampo och separat vax","✅ 'Tårtskum' — kunderna älskar look och känsla"],
discovery:"Har ni foamer-skumlans på tvätthallen idag, eller kör ni handtvätt?",
di:[{q:"Har ni foamer?"}],
pr:"149kr/L",fm:["5L","25L"]},

{id:"algfasad",n:"Alg & Fasadtvätt",cat:"Avfettning & Kem",r:3,e:"🏠",c:"#059669",tags:["bygg"],box:"25L",
p:"📋 ORIGINAL:\n\nALG&FASADTVÄTT\n\nDetta som jag ska snacka med Dig om idag är en produkt man tidigare bara kunnat köpa på tex bygghandlare och Claes Olsson bla. Priset som Claes Olsson tar är tex mellan 200-350 litern för sitt Tak GTI. I samarbete med en stor svensk fabrik så har vi tagit fram en lika bra produkt som heter ALF&FASADRENT till ett helt annat pris till Dig som handlar och är kund här på Effectum.\n\nEFFECTUMS ALG&FASADRENT är en produkt som avlägsnar alger, mögel och lav på väggar, tak o övriga utrymmen. Det finns ju egentligen på alla hus mer eller mindre så det är något som man måste ha.\n\nVad är det för fastigheter som Ni har?\n\nDetta fungerar jättebra även till båtar, utemöbler samt till plasttak bla.\n\nMan ska heller inte glömma alla stuprännor som oftast det blir stora växtligheter och stopp i.\n\nDessutom som underhållstvätt inför målning är det en kanonprodukt.\n\nMeningen är att man ska använda detta medel vartannat år. Då minskar man risken för alger o mögeltillväxt. PERFECTUM ALG&FASADTVÄTT är ett kraftfullt decinficerande medel för de flesta ytor utomhus som mycket effektivt stoppar och bleker mögelsvampar och alger. ALG&FASAD TVÄTT sprutas på med en tex lågtryckssspruta direkt på taket eller väggen.\n\nMan behöver inte vara rädd för att ALG&FASADTVÄTT påverkar byggnadsmaterial negativt då det är biologiskt nedbrytbart så där är det grönt ljus hela vägen in mål.\n\nVårt medel spädes 10 ggr och då kostar det 16,90/lit i brukslösning och är Sveriges billigaste inom detta område.\n\nVill man inte spola bort resterna av alger eller lava så dör växtligheten snabbt och sen får man vänta på regnet som då spolar bort resterna.\n\n💡 TILLÄGG:\n\nSamma prestanda som Claes Olsson Tak GTI (200-350kr/l) fast till 16,90/l brukslösning — 15-20x billigare. Behöver ej spolas: regnet sköter det. 25L dunk är normalen för fastighetsbolag, BRF:er och entreprenörer. Perfekt uppdrag inför målningsjobb.",
sp:["✅ Brukspris 16,90 kr/L (Sveriges billigaste)","✅ Späds 10x","✅ Behöver EJ spolas — regnet sköter det","✅ Håller rent i 2 år","✅ Alger, mögel, lav, svartbeläggning","✅ Biologiskt nedbrytbar","✅ Fasader, stuprännor, plasttak, utemöbler, båtar"],
discovery:"Har ni fastigheter där det alltid kommer tillbaka grön hinna på norrsidan?",
di:[{q:"Fastigheter med alger/mögel?"}],
pr:"~169kr/L",fm:["25L"]},

{id:"vegavfett",n:"Veg-Avfettning Special",cat:"Avfettning & Kem",r:3,e:"🌿",c:"#16a34a",tags:["verkstad"],
p:"📋 ORIGINAL:\n\nNy produkt kampanj VEG-AVFETTNING SPECIAL\n\nHejsan! (Kör ett bra kallsnack)\n\nNu undrar Du säkert vad jag har på gång idag? Som Du säkert vet så har vi samarbetat med en svensk kem fabrik sedan starten lite drygt 25 ÅR tillbaka i tiden. Vilket har gjort det möjligt att testa fram en ny produkt i absolut högsta bästa tänkbara kvalite i rätt miljö med obegränsade resurser. Ett antal kemister har hjäpt oss med denna nya produkt.\n\nDen produkt som vi tog fram var ett specialavfettningsmedel för att avlägsna vegetabiliska hydralojor samt smörjfett. Effectum Veg avfettning är också speciellt bra mot fastbrända vätskor. Alltså smuts rester som konvetionella avfettningsmedel inte rör på eller mattning på margardrutorna.\n\nMedlet sprayas på eller penslas på, sedan skall man låta medlet verka i minst 10 min sedan är det bara och skölja av. Veg-Avfettning Special funkar alldeles utmärkt på sommaren för att göra rent din grill hemma på altanen så har man även det problemet löst inför sommaren.\n\nDet är ett starkt avfettningsmedel som innehåller 12,5 i ph så det ska blandas ut med vatten som gör att det är ett prislöst avfettningsmedel. Minst ett 1/5 fast ännu mera vatten vid de flesta tillfällena.\n\nDetta erbjudande innebär inte att man måste köpa på sig en hel massa utan man får en kartong med 4x5 lit som ett första prov. Priset för hela paketet är inte mer än 2495:- men då får du inte glömma bonusen iform av GPS VAKTEN som är värd 2995:- så hur många paket ska du ha denna gången?\n\n💡 TILLÄGG:\n\n25 år gammal svensk kemfabrik, pH 12,5, blandas 1:5. Vegetabilisk bas gör medlet perfekt för livsmedelsindustri och restaurang där petroleum inte är ok. 4x5L kartong 2495kr + GPS-vakt bonus 2995kr — paketvärde över 5000kr.",
sp:["✅ 100% vegetabilisk — ingen petroleum","✅ 25 år på svensk fabrik","✅ pH 12,5 — starkt men hudvänligt","✅ Perfekt för ESG-rapport och upphandling","✅ Blandas 1:5 (5L → 30L brukslösning)","✅ Bonus: GPS-vakt värd 2995 kr vid köp"],
discovery:"Har ni offentliga upphandlingar eller ESG-krav på era produkter?",
di:[],
pr:"Kontakta",fm:["4x5L kartong"],bonus:"GPS-vakt värd 2995kr"},

{id:"vaxschampo",n:"Vaxschampo",cat:"Avfettning & Kem",r:3,e:"🚗",c:"#0ea5e9",tags:["åkeri"],
p:"Vaxemulsion som tar bort vägsmuts, fett, salt och dieselstänk samtidigt som den bygger en hydrofob skyddsfilm. pH 10 gör den skonsam nog för dagligt bruk utan att blekta metallic-lacker. Särskilt effektivt mot rostangrepp på stensprutskador — vaxet fyller mikroskador så fukt inte når metallen. Fordonsflottan håller färgen längre och lacken matta mindre över åren.",
sp:["✅ Vaxemulsion — rengör + skyddar i ett","✅ Hydrofob skyddsfilm efter varje tvätt","✅ pH 10 — skonsam för metallic-lack","✅ Skyddar mot rost på stensprutskador","✅ Fordonsflottan håller färgen längre","✅ Funkar i automattvätt och handtvätt"],
discovery:"Hur ofta tvättar ni fordonsflottan?",
di:[],
pr:"Kontakta",fm:["5L"],art:"513"},

{id:"handrent",n:"Handrent Aloe Vera",cat:"Avfettning & Kem",r:3,e:"🤲",c:"#10b981",tags:["verkstad"],
p:"Tar bort diesel, olja och fett från händerna utan att behöva vatten — perfekt i servicebilen och på fältet. Aloe vera i formulan gör att huden INTE torkar ut som vid traditionell pimpsten-tvål, vilket sparar eksem och sprucken hud under vintern. Citrusdoft istället för kemikalie-lukt så det luktar gott i bilen. Pumpflaska i tre storlekar beroende på antal användare — 4,5L-flaskan räcker till 10 personer i ungefär en månad.",
sp:["✅ Ingen vatten behövs — funkar i servicebilen","✅ Aloe vera skyddar huden — förhindrar eksem","✅ Citrusdoft (inte kemilukt)","✅ Tar diesel, olja, fett, kåda","✅ Pumpflaska — doserat rätt varje gång","✅ 4,5L räcker till 10 personer/månad"],
discovery:"Hur många är ni som jobbar med olja och fett dagligen?",
di:[],
pr:"~12kr",fm:["1.5L","2.7L","4.5L"],art:"149"},

{id:"golvrent",n:"Verkstadsgolvrent Industri",cat:"Avfettning & Kem",r:3,e:"🧹",c:"#1e40af",tags:["verkstad","bygg"],
p:"Alkalisk (pH 11-12) industrigolvsrengöring för verkstadsgolv med inträngd olja, fett och gummimärken från truckhjul och lastbilsdäck. Späds 1:10 till 1:50 beroende på nedsmutsning — en dunk räcker länge. Tar även märken som väntat länge (månader+) genom att sugas in i porerna på betongen. Biologiskt nedbrytbar och fungerar lika bra i kombimaskin som med manuell mopp.",
sp:["✅ pH 11-12 alkalisk — löser inträngd olja","✅ Späds 1:10 - 1:50","✅ Tar gamla märken, gummispår, däckränder","✅ Biologiskt nedbrytbar","✅ Funkar i skurmaskin + manuell mopp","✅ Återställer grip i betongen (halkskydd)"],
discovery:"Har ni skurmaskin eller kör ni manuell mopp?",
di:[],
pr:"~149 kr/5L",fm:["5L","25L"]},

{id:"sanitetsrent",n:"Sanitetsrent Toaletter",cat:"Avfettning & Kem",r:3,e:"🚽",c:"#0891b2",tags:["verkstad","bygg"],
p:"Syrabaserad (salt- och citronsyra) för kalk och urinsten i toaletter, urinoarer och duschar. Tar det som vanliga rengöringsmedel inte rår på — gula missfärgningar, kalkringar och urinstenslager. Lämnar en tunn skyddsfilm så smutsen fastnar mindre nästa gång. Färgkodad röd för säkerhet — viktigt att personalen vet att det är syra och inte ska blandas med klor eller alkalisk rengöring.",
sp:["✅ Syrabaserad — tar kalk och urinsten","✅ Tar gulning och stenlager","✅ Skyddsfilm efter = mindre återsmutsning","✅ Färgkodad röd (säkerhet)","✅ Uppfyller lokalvårdsstandard","✅ Svanenmärkt variant finns","⚠️ Blanda ALDRIG med klor eller alkalisk"],
discovery:"Sköter ni egen städning av personalutrymmen?",
di:[],
pr:"~99 kr/L",fm:["1L","5L","25L"]},

{id:"flackbort",n:"Fläckborttagare Universal",cat:"Avfettning & Kem",r:3,e:"🧽",c:"#8b5cf6",tags:["verkstad","åkeri"],
p:"För arbetskläder med oljefläckar, gräsfläckar, blodfläckar och tjära — sprayas på fläcken 5 minuter före tvätt, sedan tvätt som vanligt. Funkar i 30-60°C så du slipper specialprogram. Textilsäker formula som inte bleker färgäkta plagg eller reflexer. Sparar arbetskläder som annars hade slängts — räkna med att en 500 ml-flaska räddar 10-15 plagg, så den betalar sig på första användningen.",
sp:["✅ Spray före tvätt → verka 5 min → tvätt som vanligt","✅ Funkar i 30-60°C (ingen specialtvätt)","✅ Textilsäker — bleker inte färg eller reflexer","✅ Olja, gräs, blod, tjära, kaffe, vin","✅ Räddar 10-15 arbetsplagg per 500ml","✅ Betalar sig första användningen"],
discovery:"Hur ofta får ni slänga arbetskläder pga fläckar som inte går bort?",
di:[],
pr:"~149 kr/L",fm:["0.5L spray","5L dunk"]},

{id:"rostbort",n:"Rostborttagare Fosforsyra",cat:"Avfettning & Kem",r:3,e:"🟤",c:"#b45309",tags:["verkstad","bygg"],
p:"Fosforsyra 15-20% som omvandlar ytrost till svart järnfosfatfilm — perfekt som primer före lackering eller pulverlackering. Ersätter blästring i många fall när du bara behöver ta bort ytrost på chassin, verktyg eller staket. Efter behandling är ytan svart/grå och lackeringsfärdig utan behov av ny rengöring. Obs: kräver ögon- och hudskydd eftersom fosforsyra irriterar hud och slemhinnor.",
sp:["✅ Fosforsyra 15-20% industristandard","✅ Rost → järnfosfatfilm (lackeringsfärdig)","✅ Alternativ till blästring på ytrost","✅ Chassi, verktyg, staket, containrar","✅ Svart/grå finish efter behandling","⚠️ Ögon- och hudskydd krävs (PPE)"],
discovery:"Renoverar ni gamla fordon eller rostiga maskiner?",
di:[],
pr:"~199 kr/L",fm:["1L","5L","25L"]},

{id:"flytande_tvattmedel",n:"Grovrengöring Industri",cat:"Avfettning & Kem",r:3,e:"🧴",c:"#059669",tags:["verkstad","bygg"],
p:"Mild alkalisk (pH 9-10) för daglig allmänrengöring av golv, väggar, maskinkåpor och verktygsbänkar — skonsam nog för varje dag men tillräckligt stark för att ta verkstadssmuts. Inga lösningsmedel eller aggressiv kem, så den är säker för personal utan PPE. Späds 1:20 till 1:100 beroende på behov, vilket ger ett extremt lågt arbetspris. Behaglig doft så arbetsmiljön blir inte 'kemikalie-aktig'.",
sp:["✅ pH 9-10 mild alkalisk — daglig användning OK","✅ Späds 1:20 till 1:100","✅ Ingen PPE krävs","✅ Golv, väggar, maskinkåpor, bänkar","✅ Ej lösningsmedel (miljövänlig)","✅ Behaglig doft — inte kemikalie-lukt"],
discovery:"Vad kör ni för allmän verkstadsrengöring idag?",
di:[],
pr:"~129 kr/5L",fm:["5L","25L"]},

// ══ 4. HANDSKAR ══
{id:"handskar",n:"Handskar — Översikt",cat:"Handskar",r:4,e:"🧤",c:"#2563eb",tags:["verkstad","svetsare","bygg","åkeri","skog"],box:"2 dussin (24 par) → 1 dussin (12 par)",
p:"📋 ORIGINAL:\n\nMen någonting som alltid går det är ju lite handskar och Strumpor, för man kan ju inte går runt naken som sagt Börje.\n\nÄr det för mer våta och oljiga miljöer du behöver handske för eller är det mer en vanlig montering handske du jobbar med?\n\nOljiga Miljöer = Aquagard\nMonteringhandske = Perfectum Handsken\nFör fina handskar för honom = Tunn Monteringshandske (Ergo Tec)\n\n💡 TILLÄGG:\n\n8 modeller i sortimentet: Ergo Tec (tunn montage 59kr), Aquaguard Thermo (vinter/olja 99-119kr), Duca Vinter/Sommar (getskinn 99-149kr), Perfectum Handsken (premium allround 149-189kr), Foamcut C (skärskydd 79-129kr), Svetshandskar. 69 000 par sålda 2024. Packning 24 par eller dussin 12.",
sp:["✅ 8 modeller — en för varje arbetstyp","✅ 69 000 par sålda 2024 (social proof)","✅ Storlekar 6-12 (barn till jätte-händer)","✅ Pris från 49 kr/st","✅ Styckvis / dussin 12 / kartong 24","✅ 24-pack 'bryt i mitten' — dela med kollega"],
discovery:"Vilka handskar kör ni mest idag, och vad är största problemet?",
di:[{q:"Tunn montage/nitril?",lk:"ergotec"},{q:"Oljiga/våta miljöer?",lk:"aquaguard"},{q:"Vinterhandskar getskinn?",lk:"ducavinter"},{q:"Skärskydd?",lk:"foamcut"},{q:"Svetshandskar?",lk:"svetshandske"},{q:"Premium allround?",lk:"perfhandsken"},{q:"Sommar precision?",lk:"ducasommar"}],
pr:"49-189kr/st",fm:["Styckvis","Dussin 12","Kartong 24"]},

{id:"ergotec",n:"Ergo Tec (Tunn montage)",cat:"Handskar",r:4,e:"✋",c:"#2563eb",tags:["verkstad","bygg"],box:"24 par → 12 par",
p:"📋 ORIGINAL:\n\nHandskar (Ergo tec) — om man vill ha en tunn handske med nitril undertill\n\nVad använder du för typ av handske? Är det en tunn montagehandske? Eller en tunn med nitril i innerhanden eller mer en klassisk ejendalare med getskin?\n\n• Montage handske med nitril undertill, tunn tyg upptill, dom kostar inte mer än 59 kr/st och då är det ändå inte en köp och släng handske utan den är slitstark och tvättbar för längre livslängd\n\nEv frågor: Vad har du för storlekar?\nSvar: Allt från 6 till 12 har jag\n\nDu kan fråga: Vad har du för storlek på händerna? Efter hens svar frågar du: Hur många är ni på bolaget? (För att fördela mängd och storlek)\n\n💡 TILLÄGG:\n\nPU+Nitril blandning, sömnlös stickad, siliconfri/kromfri/nickelfri. Precision så bra att du kan lyfta en 50-öring från backen. Konkurrenter (Ejendals, Showa) ligger 89-120kr för liknande kvalite — vi på 59kr. Packning 24 par eller 12 par.",
sp:["✅ 49 kr/par — marknadens billigaste kvalitetsmontage","✅ PU+nitril-doppning (inte bara latex)","✅ Sömnlös stickad baksida","✅ Lyft en 50-öring — precisionsnivå","✅ Silikon-, krom- och nickelfri (allergivän)","✅ Tvättbar 40°C — 5-10x längre livslängd","✅ Stl 6-12 (täcker alla)"],
discovery:"Vilken storlek kör du själv, och hur många är ni som använder montagehandskar?",
di:[{q:"Storlek?"},{q:"Hur många är ni?"}],
pr:"49kr/st",fm:["Stl 6-12"],art:"ADF-874"},

{id:"aquaguard",n:"Aquaguard Thermo (Vinter/Olja)",cat:"Handskar",r:4,e:"💦",c:"#0284c7",tags:["verkstad","åkeri"],box:"24→12",
p:"100% vattentät tack vare TRIPPELDOPPAD nitril — unikt på marknaden, andra tillverkare nöjer sig med dubbeldoppat. Sandygrip-yta ger stadigt grepp även på hala, oljiga verktyg och vattenblöta ytor. Akrylfoder isolerar för kallt väder utan att göra handsken tjock och klumpig — du behåller precisionen även vid -15°C. Perfekt för åkeriförare som växlar mellan inom- och utomhusjobb och alla som jobbar i slask och diesel vintertid.",
sp:["✅ TRIPPELDOPPAD — 100% vattentät (unikt)","✅ Sandygrip — grepp i olja och blött","✅ Akrylfoder — isolering ner till -15°C","✅ Behåller precision trots fodret","✅ Säker i diesel, hydraulolja, spolarvätska","✅ Elastisk manschett — ingen fukt in via handled","✅ Stl 8-12"],
discovery:"Jobbar ni ute i slask och olja på vintern?",
di:[{q:"Oljiga miljöer?"},{q:"Vattentät?"}],
pr:"99-119kr/st",fm:["Stl 8-12"],art:"HV-LKX970"},

{id:"ducavinter",n:"Perfectum Duca Vinter",cat:"Handskar",r:4,e:"❄️",c:"#1d4ed8",tags:["verkstad","bygg"],box:"24→12",
p:"Äkta getskinn plus fleece-foder — getskinn är slitstarkare än kohud men mycket mjukare, så precisionen finns kvar även genom fodret. Fingertopparna är förstärkta för de delar som sliter mest, och manschetten är designad så du lätt får på och av handsken med kalla händer. Finns även som sommarvariant (Duca Sommar, art 7900) med exakt samma getskinn men ofodrad. Perfekt för bygg och verkstad vintertid där precision krävs men händerna måste hållas varma.",
sp:["✅ Äkta getskinn — mjukare än kohud, slitstarkare","✅ Fleece-foder — varm ner till -20°C","✅ Fingertopps förstärkta (mest slitage)","✅ Lätt på/av med kalla händer","✅ Sommarvariant finns (art 7900, ofodrad)","✅ Precision genom fodret","✅ Stl 7-11 vinter, 7-12 sommar"],
discovery:"Vad använder gänget hos er för handskar på vintern idag?",
di:[{q:"Vinter eller sommar?"}],
pr:"99-149kr/st",fm:["Stl 7-11(vinter) 7-12(sommar)"],art:"6900(V)/7900(S)"},

{id:"ducasommar",n:"Perfectum Duca Sommar",cat:"Handskar",r:4,e:"☀️",c:"#f59e0b",tags:["verkstad"],
p:"Samma äkta getskinn som vinter-varianten, men ofodrad för vår, sommar och höst. Getskinn andas betydligt bättre än kohud så du svettas inte bort handsken under en arbetsdag — vanliga lederhandskar blir sura och hårda vid första värmeböjlan. Precision nog för småskruvar och el-arbete, ändå slitstark för verkstad. Samma förstärkta tumme och pekfinger som vinter-varianten.",
sp:["✅ Äkta getskinn — bästa sommarmaterialet","✅ Ofodrad — andas, svettas inte bort","✅ Förstärkt tumme + pekfinger","✅ Precision nog för småskruvar","✅ Vår, sommar, höst — 3 säsonger","✅ Ersätter 2-3 par billiga sommarhandskar","✅ Stl 7-12"],
discovery:"Hur ligger ni till med sommarhandskar idag?",
di:[],
pr:"Kontakta",fm:["Stl 7-12"],art:"7900"},

{id:"perfhandsken",n:"Perfectum Handsken (Brand Glove)",cat:"Handskar",r:4,e:"🏆",c:"#f97316",tags:["verkstad","bygg","svetsare"],box:"24→12",bonus:"Mest uppskattade handsken alla kategorier",
p:"📋 ORIGINAL:\n\nArbetshandskar (perf brand glove) — Perfectum Handsken\n\nVad använder du för typ av handske? Är det en tunn montagehandske? Eller en tunn med nitril i innerhanden eller mer en klassisk ejendalare med getskin?\n\n• Våran egna som är förstärkt i tumme och pekfinger\n• Mockaläder i innerhanden och spandex upptill och en komfortdyna i innerhanden som ett slags vibrationsskydd. Den ligger på 149 kr/st och har en air vent upptill, så den andas som en slags ventilation\n• Sitter som en smäck i handen och passar till precis alla arbetsområden\n\nEv frågor: Vad har du för storlekar?\nSvar: Allt från 6 till 12 har jag\n\nÄr den tunn eller tjock?\nDen är mer tunn än tjock, du kan lyfta en 50 öring från backen med dessa.\n\n💡 TILLÄGG:\n\nPremium allround som funkar i alla branscher — verkstad, bygg, svets, åkeri. Vinterversion med fleecefoder 189kr. Mest uppskattade handsken över alla kategorier enligt återkommande kunder. Vibrationsdämpningen gör stor skillnad vid långa pass med verktyg.",
sp:["✅ Mockaläder — premium komfort","✅ Vibrationsdämpning (spandex + inbyggd dyna)","✅ Air vent — ventilerar under tung belastning","✅ Förstärkt tumme + pekfinger","✅ 2-3x längre livslängd än billiga allround","✅ Mest uppskattade i alla 18 000 kundföretag","✅ Sommar 149 / Vinter 189"],
discovery:"Hur många hos er använder slagborr och mutterdragare dagligen?",
di:[{q:"Storlek?"},{q:"Hur många är ni?"}],
pr:"Sommar 149kr | Vinter 189kr",fm:["Sommar+Vinter"]},

{id:"foamcut",n:"Foamcut C (Skärskydd)",cat:"Handskar",r:4,e:"🔪",c:"#4f46e5",tags:["verkstad"],box:"24→12",
p:"Skärskyddsnivå C enligt EN388 4X42C — där Arbetsmiljöverket börjar kräva skärskydd i miljöer med plåt, glas eller vassa kanter. HPPE-fibrer med inlagd ståltråd i baksidan och nitril-doppning på handflatan för grepp och oljebeständighet. Nylanserad modell 2024 som är smidigare än tidigare skärskyddshandskar — du kan fortfarande arbeta med småskruvar. 2-i-1 funktion: montage + skärskydd i samma handske, så personalen slipper byta.",
sp:["✅ Nivå C (EN388 4X42C) — AMV-godkänd","✅ HPPE + ståltråd i baksidan","✅ Nitril-doppning för grepp","✅ Oljebeständig + vattenresistent","✅ 2-i-1: montage + skärskydd","✅ Nylanserad 2024 — smidigare modell","✅ Stl 6-12 (12-pack eller 120-pack)"],
discovery:"Jobbar ni med plåt, glas eller vassa kanter där Arbetsmiljöverket kräver skärskydd?",
di:[{q:"Kräver ni skärskydd?"}],
pr:"79-129kr/st",fm:["Stl 6-12 (12/120)"],art:"HV-NJE3231"},

{id:"svetshandske",n:"Svetshandskar",cat:"Handskar",r:4,e:"🔥",c:"#b91c1c",tags:["svetsare"],
p:"Håller sig mjuka även efter veckor av svetsarbete — billiga svetshandskar blir stenhårda efter första arbetsveckan pga värmeexponering. Oxidbehandlat mockaläder ytterst, bomullsfoder innerst för isolering och svettupptagning. Funkar lika bra för TIG (precision krävs), MIG/MAG (långa pass) och MMA (slaggstänk). En handske för alla tre processer så svetsaren slipper byta beroende på jobb.",
sp:["✅ Mjuka över tid — billiga blir stenhårda","✅ Oxidbehandlat mockaläder","✅ Bomullsfoder — isolering + svettupptagning","✅ TIG + MIG/MAG + MMA i samma handske","✅ Tål gnistor och slaggstänk","✅ Långa manschetter för underarmsskydd","✅ EN 12477 svetshandske-standard"],
discovery:"Hur många svetsare är ni, och vilken process kör de mest?",
di:[],
pr:"Kontakta",fm:["Styckvis"]},

// ══ 5. KAP & SLIP ══
{id:"kapskivor",n:"Kapskivor Perfectum Premium",cat:"Kap & Slip",r:5,e:"⚙️",c:"#a855f7",tags:["verkstad","svetsare","bygg"],box:"100st (2 lådor) → 50st",bonus:"25% rabatt: 49→34,95. FLEX 125 vinkelslip (1700kr) vid 2 lådor. Paket 4995:-. Bara ~10 kvar!",
p:"📋 ORIGINAL:\n\nMANUS KAPSKIVOR + VINKELSLIP\n\nDet som det handlar om idag är en mordenisering&uppdatering av RHODIUS/Perfectum Premium kapskiva som är utav tysk superkvalite och motsvarar Tyrolit XGTS vilket är otroligt bra industriskiva.\n\nDenna uppdatering av kapskiva har gjort den 20-40% bättre men trots det har samma goda pris som 2021 (Accept). Kvaliten är alltså mycket högre, vilket resulterar i att priset självklart anses vara lägre och det är ju en god förutsättning eller hur?\n\nRODIHU/Perfectum skivan är alltså av högsta industrikvalite med 20-40% mer kapmeter än tyrolit. Samt att det är dubbel ythärdning som gör att det inte vobblar o splittras. Denna skiva har vi nu lagt under egen brand så den heter alltså from 2021 Perfectum Premium! Dessutom lite ytterligare förbättrad 2025!\n\nDär skall tilläggas att TyrolitsXGTS rankades som en av världens bästa industriskiva under 2022. Vi är alltså snäppet högre på den stegen. Det vi pratar om idag är inga större mängder utan just det nödvändigaste dimenstiornerna där Du har 25% rabatt på de kapskivorna du kör och dessutom i o med din företagsrabatt har Du rätt att plocka ut en FLEX 125 vinkelslip värde ca 1700 kr.\n\nDet är alltså en FLEX 125 vinkelslip utav tysk proffskvalite som ligger på 1010 watt och klara smått otroliga 11500 varv/min, så det är ett riktigt monster!!!!! Det låter bra eller hur?\n\nOm inte historien ljuger så är det mest 125 o 180 mm ni kör med? Så vi pratar alltså om ett 50 pack av varje dimension där vi är nere på 49:-\n\nOch inte nog med det så får Du även med en vinkelslip värde 1700:- helt kostnadsfritt ihop med paketpris på 4995:- Grymt eller hur?\n\nAvslut: Så detta paket är det endast ca 10 st kvar av så vilken leveransvecka passar Dig bäst vecka 34 eller 36?\n\n💡 TILLÄGG:\n\nHydroteck — tål vatten och väte, unikt i branschen. Kunder vittnar: plöjt igenom ett kylskåp, går hur lätt som helst. 25% rabatt på styck (49→34,95kr). Artnr 125x0.8/1.0/1.5: 6912510-515, 180x1.5: 6918015, 230x1.9/2.5: 6923019.",
sp:["✅ Rhodius XT10 — tysk marknadsledare","✅ 20-40% längre vs Tyrolit XGTS","✅ HydroProtect — åldras inte i lagret","✅ Dubbelförstärkt (2 glasfibertyg)","✅ EN 12413 + oSa-märkt","✅ Järn- och svavelfri (rostfritt-säker)","✅ Destruktivt testade (säkerhet)","✅ 49 kr/st → 34,95 med rabatt"],
discovery:"Kör ni 125 eller 230 mm, och hur många går det åt per månad?",
di:[{q:"125 eller 230?"},{q:"Slip?",lk:"slipskivor"},{q:"Lamell?",lk:"lamell"},{q:"Vision Pro?",lk:"visionpro"}],
pr:"49kr/st → 34,95 rabatt | Paket 4995:- inkl FLEX",fm:["125x0.8/1.0/1.5","180x1.5","230x1.9/2.5","50st/packe"],art:"6912510/515/6918015/6923019"},

{id:"slipskivor",n:"Slipskivor Ferox",cat:"Kap & Slip",r:5,e:"💿",c:"#9333ea",tags:["verkstad"],
p:"📋 ORIGINAL:\n\nKap och slip går ju alltid åt, kör du 125or eller 230? Använder du nån slip eller lamelltrissa i mindre skala? Jobbar du med 1,0:or, 1,5:or eller 0,8:or till och med?\n\nKap och slip samt lamell:\n• Är ju våran logga på våra skivor men vi tillverkar inga skivor utan det är en tysk proffskiva som heter Rohdius XT10\n• Känner du igen tyrolit? Det är en erkänt bra skiva, våran har 40% längre livslängd och då ligger den på 49 kr/st vare sig man tar 125 eller 230 skivor och då är dom även hydroteck till skillnad från alla andra skivor. Dom tål vatten och väte\n• Jag har plöjt igenom ett kylskåp med dessa och det går hur bra som helst. Nu säger jag inte att du kommer göra de men de går hur lätt som helst\n\nEV frågor: Hur många är det i ett packe?\nSvar: Vanligtvis 50 st men då får ni blanda med tjockleken om ni vill ha 1,0 eller 1,5 eller större\n\n💡 TILLÄGG:\n\nSlipskivor Ferox i 125x7.0 (artnr 200451), 180x7.0 (200442), 230x7.0 (200466). Lamellskivor 125 i P40 (204015), P60 (204018), P80 (204021), finns även i 180. Perfekt komplement till kapskivor-paketet — samma Rohdius XT10-kvalite genomgående.",
sp:["✅ Tysk kvalitet — Ferox","✅ Korund + optimerad harts","✅ Glöder ej rött — ingen regnbågsanlöpning","✅ Rostfritt-säker för livsmedel/mejeri","✅ 7 mm tjocklek (optimal balans)","✅ Svets-förslipning + kantfasning","✅ 125/180/230 mm"],
discovery:"Jobbar ni mycket med svets-förslipning eller kantfasning?",
di:[],
pr:"49kr/st",fm:["125x7.0","180x7.0","230x7.0"],art:"200451/442/466"},

{id:"lamell",n:"Lamellskivor",cat:"Kap & Slip",r:5,e:"🌀",c:"#7c3aed",tags:["verkstad"],
p:"📋 ORIGINAL:\n\nLamelltrissa i mindre skala? Jobbar du med finish efter grovslipning? Lamellskivor finns i 125 och 180 mm med kornhet P40, P60 och P80 — ett komplement till våra kapskivor och slipskivor.\n\n💡 TILLÄGG:\n\nArtnr: 125-P40 (204015), 125-P60 (204018), 125-P80 (204021). Används för finish efter grovslipning — tar bort slipspår och ger jämn yta inför lackering eller svetsning. 40% längre livslängd än Tyrolit tack vare XT10-basmaterialet. Vision Pro Cool (separat produkt) är premium-lamell med kylning.",
sp:["✅ Zirkonium-korund — självskärpande","✅ P40 grovt / P60 utjämning / P80 finish","✅ Glöder EJ som fasta skivor","✅ Lameller böjer sig = självkylande","✅ Jämn aggressivitet hela livslängden","✅ Fastnar ej i kanter","✅ 125 och 180 mm"],
discovery:"Vad är vanligast för er — grovslipning eller finish?",
di:[],
pr:"Kontakta",fm:["125/180"],art:"204015/018/021"},

{id:"visionpro",n:"Vision Pro Cool (Premium Lamell)",cat:"Kap & Slip",r:5,e:"🌟",c:"#eab308",tags:["verkstad","svetsare"],box:"10st → 5st",bonus:"Ord 279→189kr (32% rabatt). Ferox borrsats värd 3300kr.",
p:"FÖRSTA I SVERIGE med flygplanspropeller-design — 3 mellanrum mellan lamellsektionerna ger 30% kylare slipning än konventionella lamellskivor. Mellanrummen fungerar som luftfickor som kyler både skiva och arbetsstycke, vilket är avgörande på rostfritt, aluminium och tunnplåt där värme orsakar missfärgning eller förvridning. Fastnar INTE i skarpa kanter vilket är vanligt med vanliga lameller. Klar sikt på arbetsytan eftersom luftfickorna skapar utsyn.",
sp:["✅ FÖRSTA I SVERIGE med propeller-design","✅ 30% kylare slipning","✅ Luftfickor = självkylande","✅ Klar sikt på arbetsytan","✅ Fastnar EJ i kanter","✅ Perfekt för rostfritt, alu, tunnplåt","✅ P40/P60/P80","✅ Ord 279 → 189 kr (32% rabatt)"],
discovery:"Jobbar ni mycket med rostfritt, alu eller tunnplåt där värme är ett problem?",
di:[{q:"Rostfritt/alu?"}],
pr:"189kr/st (ord 279, 32% rabatt)",fm:["P40/P60/P80"]},

// ══ 6. SMÖRJMEDEL & OLJOR ══
{id:"motorolja",n:"Motorolja Heavy Duty",cat:"Smörjmedel & Oljor",r:6,e:"🛢️",c:"#1e40af",tags:["åkeri","verkstad"],box:"205L fat → 20L dunk",
p:"10W-40 och 15W-40 för tunga fordon, entreprenad och marin. Uppfyller ACEA E7/E9 och API CI-4-standarder, godkänd för Scania, Volvo och MAN. Heavy duty-additivpaket ger längre byteintervall och bättre skydd i hårt belastade dieselmotorer. Vid bulk-köp (fat eller IBC) ligger priset 40% under grossist-priser för 5L-dunkar — stora åkerier sparar tusentals per år.",
sp:["✅ 10W-40 och 15W-40","✅ ACEA E7/E9 + API CI-4","✅ Scania, Volvo, MAN-godkänd","✅ Heavy duty-additiv — längre byteintervall","✅ Skyddar i hårt belastade dieslar","✅ Bulk = 40% billigare än grossist 5L","✅ 5L / 20L / 208L fat / 1000L IBC"],
discovery:"Vilken viskositet kör ni på lastbilsflottan, 10W-40 eller 15W-40?",
di:[{q:"Vilken viskositet?"},{q:"Hydraulolja?",lk:"hydraulolja"}],
pr:"Volymbaserat",fm:["5L","20L","208L fat","1000L IBC"]},

{id:"hydraulolja",n:"Hydraulolja HLP 46",cat:"Smörjmedel & Oljor",r:6,e:"🔧",c:"#0369a1",tags:["åkeri","verkstad","bygg","skog"],box:"205L → 20L",
p:"HLP 46 är Sveriges mest sålda hydraulolja — passar entreprenadmaskiner, vedklyvar, kranar och de flesta pumpar. DIN 51524 del 2-standard, ISO VG 46 är 'standardviskositeten' för nordiskt klimat. Högt viskositetsindex gör att den håller rätt tjocklek både i -20°C på morgonen och +80°C under drift. Anti-wear zink-additiv skyddar pumparna, och bra demulsifiering skiljer vatten så kondens från tank inte bildar emulsion.",
sp:["✅ HLP 46 = mest sålda i Sverige","✅ DIN 51524 del 2-standard","✅ ISO VG 46 (nordisk standard)","✅ Högt viskositetsindex (-20°C till +80°C)","✅ Anti-wear zink-additiv","✅ Bra demulsifiering (skiljer vatten)","✅ Även HLP 32 och 68 finns"],
discovery:"Vilken ISO VG kör ni i hydraulsystemet, 32, 46 eller 68?",
di:[{q:"Vilken ISO VG?"},{q:"Bio-hydraulolja?",lk:"biohydraul"}],
pr:"Volymbaserat",fm:["20L","208L fat","1000L IBC"]},

{id:"biohydraul",n:"Bio-hydraulolja HEES 46",cat:"Smörjmedel & Oljor",r:6,e:"🌿",c:"#059669",tags:["skog","bygg","åkeri"],box:"205L → 20L",
p:"Biologiskt nedbrytbar HEES (syntetisk ester) enligt ISO 15380 — 60%+ bryts ner på 28 dagar. Krav i skogsbruk, vid vattendrag och i naturskyddade områden där mineralolja kan ge böter på hundratusentals kronor vid läckage. Svanenmärkt och EU Ecolabel-godkänd. Bättre smörjegenskaper än mineralolja faktiskt, och fungerar i blandning med befintlig olja under övergångsperiod. Premium-produkt men lag betalar sig snabbt genom lägre riskexponering.",
sp:["✅ HEES enligt ISO 15380","✅ 60%+ nedbrytbar på 28 dagar","✅ EU Ecolabel + Svanenmärkt","✅ Lagkrav nära vatten och naturskydd","✅ Bättre smörjning än mineralolja","✅ Blandbar med mineralolja (övergång OK)","✅ Undviker miljöböter vid läckage"],
discovery:"Jobbar ni i skog eller nära vattendrag där bio-olja är krav?",
di:[],
pr:"Volymbaserat (premium)",fm:["20L","208L fat"]},

{id:"vaxellolja",n:"Växellådsolja 75W-90",cat:"Smörjmedel & Oljor",r:6,e:"⚙️",c:"#7c3aed",tags:["åkeri","verkstad"],
p:"Syntetisk 75W-90 med API GL-5-specifikation för manuella växellådor och bakaxlar med hypoidväxel. Extremtryck-additiv (EP) klarar belastningen i tunga dieselfordon och entreprenad. Fungerar från -40°C upp till +150°C vilket är nödvändigt för skandinavisk vinter och sommar. Även 80W-90 (mineralisk) och ATF (automat) finns i sortimentet — Volvo, Scania, MAN-specifikationer på begäran.",
sp:["✅ API GL-5 / MT-1 (hypoidväxel-godkänd)","✅ Syntetisk basolja","✅ Extremtryck-additiv (EP)","✅ -40°C till +150°C operativ","✅ Manuell växellåda + bakaxel","✅ Även 80W-90 + ATF finns","✅ Volvo/Scania/MAN-spec tillgängliga"],
discovery:"Manuell växellåda, automat eller bakaxel — jag har alla tre?",
di:[{q:"Vilken typ av växellåda?"}],
pr:"Volymbaserat",fm:["1L","20L","208L fat"]},

{id:"kompressorolja",n:"Kompressorolja ISO 100",cat:"Smörjmedel & Oljor",r:6,e:"💨",c:"#475569",tags:["verkstad","bygg"],
p:"Syntetisk kompressorolja för skruv- och kolvkompressorer, ISO VG 100 är standardviskositeten för tyngre industriella kompressorer. Långt byteintervall på 4000-8000 driftstimmar jämfört med 2000 för mineralolja — sparar både pengar och stopptid. Låg oxidation så inga avlagringar bildas i kompressorn och minskar risken för överhettning. Uppfyller DIN 51506 VDL, även ISO VG 46 och 68 finns för mindre kompressorer.",
sp:["✅ Skruv- + kolvkompressor","✅ ISO VG 100 standard","✅ 4000-8000 h byteintervall (dubbla mot mineral)","✅ Låg oxidation — inga avlagringar","✅ Minskar överhettningsrisk","✅ DIN 51506 VDL-certifierad","✅ ISO VG 46/68 finns för mindre kompressorer"],
discovery:"Vilken typ av kompressor har ni — skruv eller kolv?",
di:[],
pr:"Kontakta",fm:["5L","20L","208L fat"]},

{id:"motorsagolja",n:"Sågkedjeolja Bio",cat:"Smörjmedel & Oljor",r:6,e:"🌲",c:"#16a34a",tags:["skog"],box:"205L → 20L",
p:"100% vegetabilisk raps-bas — biologiskt nedbrytbar och icke-giftig vid inandning, krav i yrkesmässigt skogsbruk. Vidhäftande så den klibbar fast på kedjan även vid maximalt varvtal, och flödar fortfarande ner till -25°C vilket är avgörande för vinterjobb. Funkar i alla motorsågar, både Stihl och Husqvarna. Skonar både operatörens lungor (ingen oljeanda) och miljön — spruten kommer i kontakt med jord och grundvatten.",
sp:["✅ 100% vegetabilisk (raps-bas)","✅ Biologiskt nedbrytbar","✅ Icke-giftig — säker för operatör","✅ Vidhäftande — slungas ej av","✅ Flödar ner till -25°C","✅ Stihl, Husqvarna, alla märken","✅ Lagkrav i yrkesmässigt skogsbruk"],
discovery:"Hur många motorsågar kör ni under säsong?",
di:[],
pr:"Volymbaserat",fm:["5L","20L","208L fat"]},

{id:"skarvatska",n:"Skärvätska Emulsion",cat:"Smörjmedel & Oljor",r:6,e:"💧",c:"#0891b2",tags:["verkstad"],
p:"Mineraloljebaserad emulsion som blandas 5-10% med vatten i CNC eller manuella bearbetningsmaskiner — kyler verktyg och arbetsstycke, spolar spånor, smörjer skäreggen. Bakterie- och svampresistent formula så tanken inte börjar stinka efter några veckor (vanligt problem med billiga emulsioner). Rostskydd gör att skärstål inte får ytrost mellan arbetspass. pH-stabil mellan 8,8-9,2 för längsta tankens livslängd.",
sp:["✅ Blandas 5-10% med vatten","✅ Bakterie- och svampresistent (ej stinkande)","✅ Rostskydd på skärstål","✅ Svarvning + fräsning + borrning","✅ pH-stabil 8,8-9,2","✅ Helolja + syntetisk variant finns","✅ CNC-kompatibel"],
discovery:"Har ni CNC-maskiner eller manuell bearbetning, och hur ofta byter ni skärvätska?",
di:[],
pr:"Kontakta",fm:["5L","20L","208L fat"]},

{id:"bromsvatska",n:"Bromsvätska DOT 4",cat:"Smörjmedel & Oljor",r:6,e:"🛑",c:"#dc2626",tags:["verkstad","åkeri"],
p:"DOT 4 ESL (Extended Service Life) med förlängt byteintervall till 3 år istället för standard 2. Kokpunkt 265°C torr och 170°C våt — viktigt eftersom bromsvätska absorberar fukt från luften, vilket sänker kokpunkten och kan ge 'mjuk pedal' i extremsituationer. ISO 4925 Class 6, FMVSS No. 116 och SAE J1704 godkänd, vilket betyder den fungerar i alla moderna fordon. Även DOT 3 (billigare, äldre fordon) och DOT 5.1 (racing) finns i sortimentet.",
sp:["✅ DOT 4 ESL — 3 års byteintervall","✅ Kokpunkt 265°C torr / 170°C våt","✅ ISO 4925 Class 6","✅ FMVSS No. 116 + SAE J1704","✅ Alla moderna fordon","✅ DOT 3 + DOT 5.1 finns också","✅ 0,5L / 1L / 5L / 20L"],
discovery:"Vilken bromsvätska kör ni idag — DOT 4 standard eller ESL?",
di:[],
pr:"Kontakta",fm:["0.5L","1L","5L","20L"]},

{id:"smorjfett",n:"Smörjfett LX-Polar",cat:"Smörjmedel & Oljor",r:6,e:"🔧",c:"#f97316",tags:["verkstad"],box:"2 lådor (50 tuber) → 1 låda (25)",bonus:"Vid 2 lådor: GRATIS batterispruta 690 bar (4000-6000kr). 340000 sålda/år. Bransch 140-190kr → Perfectum 89kr.",
p:"📋 ORIGINAL:\n\nVad kör du för smörfett, kör du vanligt lock eller med skruvgängat lock?\n\nSmörjfett LX-Polar (Blir till Maxi)\n\n★ Vi har ett som är till för rymdskepp höll jag på att säga, som har en väldigt låg pumpbarhet på -33 annars ligger de på -20\n★ Den har en hög droppunkt på 120 celcius och 220 i centistoke, annars ligger det på 50 centistoke\n★ Både till kull och glidlager\n★ EP2 klassat och litiumkomplex baserat\n\nMen den är ju för rymdskep som sagt, ligger vanligtvis på 139 kr/tuben men jag tänkte inte prata om den utan vi har ett fett som är 50 kr/tuben som är billigare. Den pratar jag alltid om för priset kontra prestandan är minimal. Den tycker jag du ska testa!\n\nEgentligen ligger det lilla packet LX på 25 tuber och Maxi på 50 tuber, men nu ska du ju bara testa dessa är tanken, därför kan jag ringa in till lagret och bryta ett packe så du får testa 25 st.\n\n💡 TILLÄGG:\n\nVi representerade Castrol förut — detta är helt annan nivå. Lube Shuttle kladdfria tuber med skruvgänga (Hugo Eff 0002) — ingen mer gris om fingrarna. 340 000 tuber sålda senaste året. Konkurrenterna ligger 140-190kr/tub. Batterispruta 690 bar (normalt 450), 100gr/min, värd 4000-6000kr — ingår gratis vid 2 lådor fett.",
sp:["✅ EP2 litiumkomplex (premium-klass)","✅ -33°C pumpbarhet vs bransch -20°C","✅ 260°C droppunkt vs bransch 100-120°C","✅ 220 cst viskositet vs bransch 50","✅ 340 000 tuber sålda per år","✅ Lube Shuttle kladdfritt","✅ 89 kr vs branschens 140-190 kr"],
discovery:"Vilken fettspruta har ni — vanligt lock eller skruvgängat Lube Shuttle?",
di:[{q:"Vanligt/skruvgängat lock?"},{q:"Fettspruta?",lk:"fettspruta"}],
pr:"89kr/tub (bransch 140-190) | Maxi 99kr",fm:["LX 25 tuber","Maxi 50","Hugo Eff 0002 (skruv)"],art:"Hugo Eff 0002"},

{id:"fettspruta",n:"Fettspruta Batteri 690 bar",cat:"Smörjmedel & Oljor",r:6,e:"💉",c:"#ea580c",tags:["verkstad"],
p:"690 bar arbetstryck vs vanliga handsprutor som klarar 450 bar — pressar igenom även packade, igensatta smörjnipplar där andra ger upp. Batteridriven så du slipper handarbeta, vilket sparar både tid och axlar. 100 gram fett per minut = 15-20 minuter sparad tid per fordon vid komplett nipplbehandling. Använder Lube Shuttle-tuber (400 g) så inga trasor, ingen kladd, ingen tidsspillan på att fylla på.",
sp:["✅ 690 bar vs handspruta 450 bar","✅ Pressar igenom packade nipplar","✅ 100 g fett/minut","✅ Batteridriven — sparar axlar","✅ Lube Shuttle 400 g — kladdfritt","✅ 15-20 min sparat per fordon","✅ GRATIS vid 2 lådor fett"],
discovery:"Hur mycket smörjning gör ni dagligen?",
di:[],
pr:"4000-6000kr (GRATIS vid 2 lådor fett)",fm:["Batteridragen"]},

// ══ 7. RENGÖRING ══
{id:"vatservetter",n:"Våtservetter Unicleaner",cat:"Rengöring",r:7,e:"🧻",c:"#14b8a6",tags:["verkstad","åkeri"],box:"50st → 12st → 6st",
p:"📋 ORIGINAL:\n\nAnvänder du våtservetter på burk? Alltså till händer, verktyg och interiörer. Man brukar ju ha nån i verkstad, nån i maskin eller ute på fält.\n\nVåtservetter på burk (Unicleaner):\n• Våra våtservetter är för både händer, verktyg och interiöer då du har en slätt sida och en räfflad sida\n• Motsvarande scrubs kostar ju 299 våra är liksom 50 spänn billigare och bättre\n• Våra är lagom blötta och det jag gillar med dom är att när du har öppnat ett lock så torkar inte skiten ut, sånt kan man ju bli vansining på annars eller att det frostar till i vintern\n• Allt ligger ju i 24 packe men de fattar jag ju att det är alldeles för mycket, men funkar ett dussin eller 6 st? Så har du fått testa dom\n\n💡 TILLÄGG:\n\nPerfekt paketstorlek — 1 burk till varje användningsplats (verkstad, maskin, fält). Scrubs kostar 299kr, våra 80kr — samma kvalite eller bättre. Slät sida för händer/skärmar, räfflad sida för verktyg. Torkar aldrig ut, frostar inte vintertid.",
sp:["✅ Samma funktion som Scrubs — 75% billigare","✅ Slät + räfflad sida på samma servett","✅ Torkar INTE ut i burken","✅ Frostar ej i kyla (servicebil OK)","✅ Händer, verktyg, interiör","✅ 80 kr vs Scrubs 299 kr","✅ 50-burk räcker 2-3 veckor i verkstad"],
discovery:"Kör ni Scrubs idag? Då sparar ni nästan 75% per burk.",
di:[{q:"Kör ni Scrubs?"}],
pr:"~80kr/burk",fm:["50st","12st","6st"]},

// ══ 8. KLÄDER ══
{id:"understall",n:"Underställ Millers Bambu",cat:"Kläder",r:8,e:"👕",c:"#059669",tags:["verkstad","bygg","åkeri"],
p:"Bambu istället för ull — andas mycket bättre (ull håller bara värmen), är antibakteriellt naturligt (kan bäras 2-3 dagar utan lukt) och temperaturreglerande (varmt när det är kallt, svalt när det är varmt). Halva priset mot kvalitetsullställ som ligger över 1500 kr, vi ligger under 750 kr för både över- och underdel. Mjukt som siden mot huden — inget av det klassiska ull-kliet. Dam- och herrmodeller säljs styckvis så du kan bygga rätt kombination.",
sp:["✅ 100% bambu — andas bättre än ull","✅ Antibakteriellt — bärs 2-3 dagar","✅ Temperaturreglerande (varmt + svalt)","✅ Mjukt som siden — kliar ej","✅ Halva priset mot kvalitetsull (1500+)","✅ Under 750 kr för över+underdel","✅ Dam + herr styckvis"],
discovery:"Kör ni ullunderställ idag, och hur många är ni i växlande temperaturer?",
di:[{q:"Kör ni ull?"},{q:"Hur många?"}],
pr:"Under 750kr",fm:["Överdel","Underdel"],art:"5212(H)/5307(D)"},

{id:"strumptjock",n:"Perfectum Dura (Tjock strumpa)",cat:"Kläder",r:8,e:"🧦",c:"#b45309",tags:["verkstad","bygg","åkeri"],box:"12 par → 6 par",
p:"85 000 par sålda 2024 — sannolikt Sveriges mest sålda arbetsstrumpa i den kategorin. Frottésula dämpar för långa arbetsdagar i säkerhetsstövlar på betonggolv, och kraftigt resår håller strumpan på plats i stöveln istället för att glida ner och samlas vid fotbladet (klassiskt problem med billiga strumpor). Finns i fyra storlekar 35-38 upp till 47-50 så alla kan bäras. Räkna med att 6-pack räcker en person i 2-3 veckor dagligt bruk.",
sp:["✅ 85 000 par sålda 2024","✅ Frottésula — dämpar långa pass","✅ Kraftigt resår — glider ej i stöveln","✅ Passar alla säkerhetsstövlar","✅ 4 storlekar 35-38 till 47-50","✅ 6-pack räcker 2-3 veckor","✅ 89-99 kr/par"],
discovery:"Vilken skostorlek har du själv, och hur många är ni?",
di:[{q:"Skostorlek?"},{q:"Hur många?"}],
pr:"89-99kr/par",fm:["Stl 35-38/39-42/43-46/47-50"],art:"69-(stl)"},

{id:"strumptunn",n:"Perfectum Dura Spring (Tunn)",cat:"Kläder",r:8,e:"🧦",c:"#16a34a",tags:["verkstad","bygg","åkeri"],box:"12→6",
p:"80% bomull, 15% polyester, 5% elastan — funktion för vår, sommar och höst men ser clean ut så den fungerar även till vardags med sneakers. Förstärkt tå och häl där slitaget är som störst, vriststriktning håller den på plats. Vid order 300+ par kan vi göra eget tryck med firmans logga på kanten — 59 kr/par, perfekt som gåva till anställda eller profilprodukt. Svart clean design som ser professionell ut under arbetsbyxor.",
sp:["✅ 80% bomull + 15% poly + 5% elastan","✅ Förstärkt tå + häl (mest slitage)","✅ Vriststriktning — glider ej","✅ Vår/sommar/höst","✅ Funkar även till vardags","✅ 300-pack = eget tryck 59 kr/par","✅ Svart clean design"],
discovery:"Vad kör ni idag, tunna eller tjocka strumpor?",
di:[{q:"Tunna eller tjocka?"}],
pr:"69-99kr/par (300st: 59kr eget tryck)",fm:["Stl 39-42/43-46/47-50"],art:"69-10101"},

// ══ 9. SVETS ══
{id:"svetshjalm",n:"Svetshjälmar",cat:"Svets",r:9,e:"⚡",c:"#dc2626",tags:["svetsare"],
p:"Auto-darkening med reaktionstid under 0,1 millisekund — ljusbågen hinner aldrig bränna ögat som med billiga hjälmar där reaktionstiden kan vara 1-2 ms. DIN 9-13 justerbart så du kan anpassa mörkertalet efter process (TIG kräver mindre mörkläggning än MMA). Slipfunktion inbyggd så du växlar sömlöst mellan svets och slipning utan att byta hjälm. Solcell plus litiumbatteri så den är alltid laddad när arbetsdagen börjar.",
sp:["✅ Reaktion <0,1 ms (billiga 1-2 ms)","✅ DIN 9-13 justerbart mörkertal","✅ Slipfunktion — växla sömlöst","✅ Solcell + litiumbatteri","✅ Alltid laddad efter arbetsdag","✅ TIG + MIG + MMA — alla processer","✅ EN 379 + EN 175 certifierad"],
discovery:"Hur många svetsare är ni, och vad kör de mest — TIG, MIG eller pinne?",
di:[{q:"Hur många svetsare?"}],
pr:"Se katalog",fm:["Diverse"]},

{id:"svetsmaskin",n:"Svetsmaskiner",cat:"Svets",r:9,e:"🔌",c:"#b91c1c",tags:["svetsare"],
p:"Inverterteknologi ger 5-15 kg kroppsvikt men fortfarande 200+ ampere uteffekt — 10x lättare än transformatorsvetsar från 90-talet. Finns som dedikerade TIG, MIG/MAG, MMA eller kombimaskiner som klarar flera processer. Bärbar så man kan ta med upp i ställningar och trånga utrymmen utan problem. Elektronisk strömreglering gör att svetsningen håller samma kvalitet oavsett strömspikar i elnätet — viktigt på byggarbetsplatser där strömmen kan variera.",
sp:["✅ Inverter 5-15 kg (vs 50-100 kg transform)","✅ 200+ ampere uteffekt","✅ TIG + MIG/MAG + MMA eller kombi","✅ Bärbar till ställning","✅ Elektronisk strömreglering","✅ Stabil kvalitet trots strömvariation","✅ EN 60974 certifierad"],
discovery:"Vill ni ha dedikerade maskiner eller kombimaskin som klarar flera processer?",
di:[{q:"TIG, MIG eller pinne?"}],
pr:"Se katalog",fm:["Diverse"]},

{id:"elektroder",n:"NC 312ER Super Speed",cat:"Svets",r:9,e:"⚡",c:"#991b1b",tags:["svetsare"],box:"16-20kg kartong → 4kg",
p:"Reparationselektrod för när du inte vet exakt vad materialet är — rostfritt, fjäderstål, mangan eller gjutjärn, alla stålsorter fungerar. Kan köras i alla svetslägen (vertikal, horisontal, tak) och både AC och DC-ström, så en och samma elektrod täcker det mesta. Jämnare båge än billiga reparationselektroder — kläber mindre i materialet, rent smält, lättare att tända första dra. Syrafri och rostfri svets som inte rostar under ytan efteråt.",
sp:["✅ Alla stålsorter (rostfritt/fjäder/mangan/gjut)","✅ Alla svetslägen (vertikal/tak/horiz)","✅ AC + DC-ström","✅ Sprickbeständig + korrosionsbeständig","✅ Lätt tänd första dragen","✅ Jämn båge — klänger ej i materialet","✅ Syrafri + rostfri svets"],
discovery:"Vilken dimension kör ni mest — 2,5 eller 3,25?",
di:[{q:"Vilken dimension?"}],
pr:"2.00: 236kr(in)/599(ut)/680\n2.50: 165(in)/179(ut)\n3.25: 150(in)/449/221\n4.00: 160(in)",fm:["2.00x300 4kg","2.50x300 4kg","3.25x350 5kg","4.00x350 5kg"],art:"1612212/249250/244320/1614312"},

{id:"svetskl",n:"Svetskläder",cat:"Svets",r:9,e:"🧥",c:"#a21c1c",tags:["svetsare"],
p:"EN ISO 11611-certifierade crust-lädervaror — lagkrav från Arbetsmiljöverket för svets. Vanliga arbetskläder (polyester/bomull-mix) brandfarliga och kan tändas vid första slaggstänket, vilket är ett stort arbetsmiljöproblem. Crust-läder är bättre än split-läder eftersom det är ytterlagret av huden — slitstarkare och tål högre temperaturer. Finns som förkläden, ärmar, huvor och helkroppsdräkter beroende på svetspositionering.",
sp:["✅ EN ISO 11611-certifierad","✅ Lagkrav Arbetsmiljöverket","✅ Crust-läder (bättre än split)","✅ Tål gnistor och slaggstänk","✅ Förkläden, ärmar, huvor, helkropp","✅ Hållbar — byts sällan","✅ Skyddar även UV-strålning från båge"],
discovery:"Kör ni mycket tak- eller vertikalsvets där stänk ramlar ner?",
di:[],
pr:"Se katalog",fm:["Diverse"]},

{id:"migsvetstrad",n:"MIG-tråd SG2 (ER70S-6)",cat:"Svets",r:9,e:"🎗️",c:"#dc2626",tags:["svetsare"],
p:"Standardtråden för MIG/MAG-svetsning av kolstål — ER70S-6 (amerikansk nomenklatur) eller SG2 (europeisk). Kopparbelagd för jämn matning genom pistolen utan glapp eller fastnande, vilket är avgörande för konstant svetskvalitet. Silikon-mangan-legering ger rent smält och minskar spraymängd. Fungerar i kortbåge (tunnplåt) såväl som spraybåge (tjockare material) beroende på strömstyrka. 5 kg D200-spole för mindre jobb, 15 kg D270 för produktion.",
sp:["✅ SG2 / ER70S-6 — standarden för kolstål","✅ Kopparbelagd — jämn matning","✅ Silikon-mangan-legering","✅ 0,8 / 1,0 / 1,2 mm","✅ Kortbåge + spraybåge","✅ CO2 eller M21 blandgas","✅ 5 kg D200 / 15 kg D270 spole"],
discovery:"Vilken dimension kör ni på MIG-tråden — 0,8 eller 1,0?",
di:[],
pr:"Spolbaserat",fm:["5 kg D200","15 kg D270","Ø 0,8 / 1,0 / 1,2"]},

{id:"rostfri_trad",n:"Rostfri MIG-tråd ER308LSi",cat:"Svets",r:9,e:"✨",c:"#64748b",tags:["svetsare"],
p:"ER308LSi är standard för svetsning av 304-rostfritt (mest använd kvalitet). ER316LSi för 316 syrabeständigt (livsmedel, kemi, marin). ER309LSi för blandade fogar mellan vanligt stål och rostfritt — viktigt vid reparationer. Förhöjt kiselinnehåll (Si) ger smidigare båge och mindre sprut. Kräver Ar+2% CO2-blandgas (M12) — för mycket CO2 kolar materialet och förstör den rostfria egenskapen.",
sp:["✅ ER308LSi = 304-rostfritt standard","✅ ER316LSi = syrabeständigt (316)","✅ ER309LSi = blandfog stål/rostfritt","✅ Kisel-förhöjd (Si) — smidig båge","✅ Ar+2% CO2 (M12) skyddsgas","✅ 5 kg och 15 kg spolar","✅ Ø 0,8 / 1,0"],
discovery:"Svetsar ni 304 eller 316 rostfritt, och vilken blandgas kör ni?",
di:[],
pr:"Spolbaserat (premium)",fm:["5 kg","15 kg","Ø 0,8 / 1,0"]},

{id:"alutrad",n:"Aluminium MIG-tråd ER4043/5356",cat:"Svets",r:9,e:"⚪",c:"#94a3b8",tags:["svetsare"],
p:"ER4043 med 5% kisel för gjutaluminium — mjukare svets som följer materialets termiska rörelse utan att spricka. ER5356 med magnesium-legering för konstruktionsaluminium (profiler, plåt) — starkare svets men stumare. Kräver ren argon som skyddsgas (INTE CO2-blandning som förstör alu). Spool-gun rekommenderas starkt eftersom alu-tråd är mjuk och knäcker lätt i lång matarkabel. 2 kg och 7 kg spolar.",
sp:["✅ ER4043 (5% Si) — gjutaluminium, mjukare","✅ ER5356 (Mg-legering) — konstruktion, starkare","✅ Ren Argon som skyddsgas","✅ 0,8 / 1,0 / 1,2 mm","✅ 2 kg + 7 kg spolar","✅ Spool-gun rekommenderas (alu knäcker)","⚠️ ALDRIG CO2-bland — förstör aluminium"],
discovery:"Jobbar ni med aluminium — gjutdelar eller plattor/profiler?",
di:[],
pr:"Kontakta",fm:["2 kg","7 kg","Ø 0,8 / 1,0 / 1,2"]},

{id:"skyddsgas_argon",n:"Skyddsgas Argon/Mix",cat:"Svets",r:9,e:"💨",c:"#0284c7",tags:["svetsare"],
p:"Skyddsgaser klassificerade enligt SS-EN ISO 14175 — rätt gas för rätt process är avgörande för svetskvaliteten. Ren Argon (I1) för TIG och alu, Ar+18% CO2 (M21) för kolstål-MIG, Ar+2% CO2 (M12) för rostfritt MIG, och ren CO2 för kortbåge på tjockare kolstål. Tumregel för flöde: 10-12x tråddiametern i liter per minut. Även MISON-varianter finns med liten NO-tillsats som bryter ner ozon som bildas vid svetsning — bättre arbetsmiljö.",
sp:["✅ SS-EN ISO 14175-standard","✅ Ren Argon (I1) — TIG + alu","✅ Ar+18% CO2 (M21) — kolstål MIG","✅ Ar+2% CO2 (M12) — rostfritt MIG","✅ Ren CO2 — tjockare kolstål","✅ MISON-variant bryter ner ozon (arbetsmiljö)","✅ 10L / 20L / 50L flaska"],
discovery:"Vilken skyddsgas kör ni idag — ren Argon, Mix eller ren CO2?",
di:[],
pr:"Volymbaserat",fm:["10L","20L","50L flaska"]},

{id:"slipmedel_svets",n:"Svetsspray Anti-stänk",cat:"Svets",r:9,e:"🔥",c:"#ef4444",tags:["svetsare"],
p:"Sprayas på GASMUNSTYCKET (inte arbetsstycket) — skyddar munstycket från att fastna i slagg och förlänger livslängden 3-5 gånger. Billig förebyggande åtgärd som sparar gasmunstycken (200-400 kr styck). Silikonfri så svetsfogen kan eftermålas utan primerproblem — viktigt på lackerade produkter. OBS: får INTE sprayas på arbetsstycket, då uppstår giftiga gaser under svetsning. Hållbar film så ett sprut räcker länge.",
sp:["✅ Sprayas på MUNSTYCKET (ej arbetsstycket)","✅ 3-5x längre munstyckslivslängd","✅ Sparar 200-400 kr per bytt munstycke","✅ Silikonfri — kan eftermålas","✅ Mindre rengöringstid mellan svets","⚠️ ALDRIG på arbetsstycket (giftiga gaser)","✅ En burk räcker till en veckas arbete"],
discovery:"Hur mycket tid lägger ni på att rengöra gasmunstycket efter svetsning?",
di:[],
pr:"~149 kr/burk",fm:["Enstaka","Dussin"]},

// ══ 10. MASKINER ══
{id:"flex",n:"Vinkelslip FLEX 125",cat:"Maskiner",r:10,e:"🔩",c:"#6366f1",tags:["verkstad"],
p:"Tyska Flex uppfann vinkelslipen 1954 — originaltillverkaren har 70 års erfarenhet och det märks i varje detalj. 1010 W motor med 11 500 varv per minut ger den kraft som behövs för tyngre kap- och slipjobb. Vibrationsdämpat handtag minskar vitfingersjuka-risken vid långa arbetspass. Soft-start eliminerar rycket vid start vilket sparar både armen och skivan. Tyskt proffsmonster som håller 10+ år med normalt bruk — den sista vinkelslipen du behöver köpa på länge.",
sp:["✅ Flex uppfann vinkelslipen 1954 (original)","✅ 1010 W + 11 500 varv/min","✅ Vibrationsdämpat handtag","✅ Soft-start — ingen ryckstart","✅ Tysk kvalitet — håller 10+ år","✅ Arbetsmiljövänlig (minskad vitfinger-risk)","✅ GRATIS vid 2 lådor kapskivor"],
discovery:"Hur många vinkelslipar går åt per år hos er?",
di:[],
pr:"~1700kr (bonus vid 2 lådor kap)",fm:["1st"],art:"4383"},

{id:"slangvindor",n:"Slangvindor Blubird",cat:"Maskiner",r:10,e:"🔄",c:"#475569",tags:["verkstad"],box:"2st → 1st",
p:"📋 ORIGINAL:\n\nMANUS SLANGVINDOR\n\nVi var nere på verktygsmässan i Köln 2025 och träffade en producent från tyskland. Denna fabriken gör alltså slangvindor och dem tillverkar bara åt dem absolut bästa märkena.\n\nDeras särklass största marknad är USA men nu vill dom in på den europiska marknaden.\n\nVi har fått möjligheten att vara med att lansera deras storsäljare blubird i vårt eget varumärke Perfectum.\n\nFör det första så är det 5 års garanti på både slang o vinda. Det säger en del om kvaliten eller hur?\n\nDet är givetvis ett stort tryck på kartongen med alla uppgifter man behöver.\n\nJust denna slangen är lättare än allt annat på marknaden och klarar extrema förhållande.\n\nDet klarar av tuffa utomhus förhållande — alltså direkt solljus som normalt förstör en slang på nolltid. Något som Du kanske vart ute för själv?\n\nDen är helt olje o fett resistent och klara tom diesel som är superbra såklart eller hur?\n\nSlangen är flexibel även i kalla temperaturer och klarar tom minusgrader utan att bli stel. Detta är ovanligt måste jag ändå säga!\n\nVi har tagit fram 2 olika dimensioner med både vatten o luft slang på samma vinda. Alltså 2 olika möjligheter på varje vinda.\n\n💡 TILLÄGG:\n\nTysk tillverkare (blubird), nu under Perfectum-brand. Konkurrenter Cejn och Nederman ligger betydligt högre prismässigt utan 5 års garanti. Perfekt för verkstäder som tröttnat på att slangar förstörs av UV/olja. 2 dimensioner per vinda = luft + vatten i samma enhet.",
sp:["✅ Tysk producent (Köln-mässan 2025)","✅ 5 års garanti (unikt i Sverige)","✅ Lättaste på marknaden","✅ Tål direkt solljus (UV)","✅ Olje-/fett-/dieselresistent","✅ Flexibel i minusgrader","✅ 2 dimensioner per vinda (vatten + luft)"],
discovery:"Har ni slangvindor idag eller släpar ni slang på verkstadsgolvet?",
di:[{q:"Har ni slangvindor?"},{q:"Tryckluft?"}],
pr:"Kontakta",fm:["Vatten","Luft","2 dimensioner/vinda"]},

{id:"induktion",n:"Induktionsvärmare",cat:"Maskiner",r:10,e:"🌡️",c:"#9333ea",tags:["verkstad"],
p:"Värmer ENBART metallen via elektromagnetisk induktion — ingen öppen låga, ingen brandrisk, ingen värme på omgivande gummi, lackerad del eller packning. 30 sekunder för att värma en M12-mutter jämfört med 5 minuter med gasbrännare. Perfekt för fastrostade bultar, hjullager, drivaxlar och andra komponenter där gasbrännare skulle orsaka sekundärskador. Oumbärligt för åkeri, skog och entreprenad där allt är fastrostat.",
sp:["✅ 30 sek vs 5 min gasbrännare","✅ Ingen brandrisk — ingen öppen låga","✅ Värmer ENBART metallen","✅ Inga skador på gummi/lack/packning","✅ Fastrostade bultar + hjullager","✅ Spar 15-30 min per fastrostad del","✅ Typ återbetalning inom 1-2 veckor i åkeri"],
discovery:"Jobbar ni mycket med äldre fordon, skogsmaskiner eller lastvagnar där allt är fastrostat?",
di:[{q:"Fastrostade bultar?"}],
pr:"Kontakta",fm:["Diverse"]},

{id:"starthjalp",n:"Starthjälp RIMAC",cat:"Maskiner",r:10,e:"🚗",c:"#059669",tags:["åkeri","verkstad"],
p:"RIMAC-boostern finns i 12V (personbilar) och 24V (lastbilar) med 20 000+ mAh kapacitet — startar döda dieselmotorer ner till -20°C pålastat. USB-C snabbladdning gör att du får full kapacitet på 2-3 timmar, ingen mer 'den var inte laddad när jag behövde den'. Inbyggd LED-arbetslampa för natt-service. Kompakt så den får plats i skåpbilen eller verktygsskåpet — tar ingen extra plats.",
sp:["✅ 12V eller 24V modeller","✅ 20 000+ mAh kapacitet","✅ Startar döda dieslar i -20°C","✅ USB-C snabbladdning (2-3h)","✅ LED-arbetslampa inbyggd","✅ Kompakt — får plats överallt","✅ RIMAC — välrenommerad tillverkare"],
discovery:"Kör ni åkeri där lastbilar kan ligga döda efter helgen?",
di:[],
pr:"Se katalog",fm:["Diverse"]},

{id:"led",n:"LED-lampor",cat:"Maskiner",r:10,e:"💡",c:"#eab308",tags:["verkstad"],
p:"Arbetslampor, ficklampor och pannlampor i olika styrkor — från 500 lumen (läsa servicebok) upp till 3000 lumen (belys hela verkstadsinteriör). Magnetfäste på många modeller så du kan sätta upp dem på maskiner utan händer. IP54-67 damm- och stänkskydd beroende på modell, så de klarar verkstadsmiljö och utomhusbruk. USB-C laddning betyder slut på engångsbatterier — du laddar med samma kabel som mobilen.",
sp:["✅ 500-3000 lumen efter behov","✅ Magnetfäste — hands-free","✅ IP54-67 damm/stänk","✅ USB-C laddning (ej engångsbatterier)","✅ Skuggfritt arbetsljus","✅ Arbetslampa + ficklampa + pannlampa","✅ Miljövänligt (laddningsbart)"],
discovery:"Vilken typ behöver ni mest — arbetsljus, ficklampa eller pannlampa?",
di:[],
pr:"Kontakta",fm:["Diverse"]},

// ══ 11. SKÄRANDE FÖR BORRNING I METALL ══
{id:"hssbor",n:"HSS Spiralborr-sats",cat:"Skärande Borrning Metall",r:11,e:"🔩",c:"#0f172a",tags:["verkstad","bygg"],
p:"Snabbstål enligt DIN 338 — standarden för professionellt bruk. 118° spetsvinkel är optimerad för standardstål, gjutjärn och aluminium. Ånganlöpta för extra slitstyrka, cylindriska skaft passar alla borrchuckar. 1-13 mm i 0,5 mm steg täcker 90% av dagligt behov. Vid rostfritt, titan eller härdat stål — gå upp till koboltborr istället, HSS räcker inte till.",
sp:["✅ DIN 338 standardprofil","✅ HSS snabbstål","✅ 118° spets för standardstål/gjutjärn/alu","✅ Ånganlöpt för extra slitstyrka","✅ Cylindriska skaft — alla chuckar","✅ 1-13 mm i 0,5 mm steg","✅ Sats 1-10 eller 1-13 mm"],
discovery:"Vilket material borrar ni mest i — standardstål eller rostfritt?",
di:[{q:"Rostfritt?",lk:"koboltbor"},{q:"Större hål?",lk:"karnbor"}],
pr:"Satsvis från 495 kr",fm:["Sats 1-10mm","Sats 1-13mm","Styckvis"]},

{id:"koboltbor",n:"Kobolt-borr HSS-E (5% Co)",cat:"Skärande Borrning Metall",r:11,e:"💎",c:"#7c3aed",tags:["verkstad"],
p:"HSS-E (även kallat M35) med 5% kobolt-legering — 20 gånger längre livslängd i svårbearbetat material jämfört med vanligt HSS. Tål 600°C utan att tappa härdning, vilket är avgörande i rostfritt, titan och nickellegeringar där friktionsvärmen normalt förstör borrspetsen. 135° korsspets gör centrering enklare och minskar axialkraften — borren 'vandrar' inte. Klarar stål upp till 1300 N/mm² hållfasthet, rostfritt upp till 1100 N/mm².",
sp:["✅ 5% kobolt — HSS-E / M35-standard","✅ 20x längre livslängd vs vanligt HSS","✅ Tål 600°C (HSS bara 400°C)","✅ Rostfritt + titan + nickel + härdat stål","✅ 135° korsspets — centrering utan vandring","✅ Stål upp till 1300 N/mm²","✅ Rostfritt upp till 1100 N/mm²"],
discovery:"Hur ofta borrar ni i rostfritt, och hur snabbt slits borren ut?",
di:[],
pr:"149-399 kr/st beroende dim",fm:["1-13 mm styckvis","Sats 1-10 mm","Sats 1-13 mm"]},

{id:"karnbor",n:"Kärnborr HSS-XE / HM",cat:"Skärande Borrning Metall",r:11,e:"🕳️",c:"#4338ca",tags:["verkstad","bygg"],
p:"Tre serier för olika stålklasser: Gold-Line (HSS-XE med kobolt) för stål upp till 1100 N/mm², Hard-Line (HM-skär, hårdmetall) för material upp till 40 HRC inkl aluminium och rostfritt, och Hardox-Line för extremstål upp till 50 HRC inkl Hardox 400/500/600. Kärnborrar borrar bara en tunn ring istället för hela hålet — 3-5x snabbare än spiralborr på plåt över 13 mm. 12-100 mm diameter.",
sp:["✅ 3 serier för olika stålklasser","✅ Gold: HSS-XE kobolt (1100 N/mm²)","✅ Hard: HM-skär för 40 HRC + rostfritt","✅ Hardox-Line: upp till 50 HRC + Hardox","✅ 3-5x snabbare än spiralborr på plåt","✅ 12-100 mm diameter","✅ Universalfäste Weldon/Tricut"],
discovery:"Borrar ni mycket hål över 13 mm i plåt eller profiler?",
di:[],
pr:"295-1295 kr beroende dim",fm:["12-30 mm","30-60 mm","60-100 mm"]},

{id:"stegbor",n:"Stegborr (Kottborr)",cat:"Skärande Borrning Metall",r:11,e:"📐",c:"#6366f1",tags:["verkstad","bygg"],
p:"4-32 mm borrdiametrar i ETT och samma borr — revolutionerande för plåtarbete där du annars behöver byta borr 5-6 gånger. Borra, förstora och avgrada i ett enda moment, perfekt för plåt 0,5-4 mm. Titannitrid-beläggning (TiN) förlänger livslängden 2-3x vs obelagd HSS. Kopplings- och elektriker använder den för genomföringar i plåtskåp och ventilationsrör — sparar 10-15 minuter per hål vid installation.",
sp:["✅ 4-32 mm i ETT borr (vs 5-6 byten)","✅ Borra + förstora + avgrada samtidigt","✅ TiN-beläggning — 2-3x längre livslängd","✅ Plåt 0,5-4 mm optimalt","✅ Ingen skarv mellan diametrar","✅ 10-15 min sparat per hål","✅ Standard för el/kopplings-arbete"],
discovery:"Jobbar ni med plåtelektronik eller ventilations-installation?",
di:[],
pr:"295-495 kr",fm:["4-12 mm","4-20 mm","4-32 mm"]},

{id:"halsag",n:"Hålsåg Bi-Metal",cat:"Skärande Borrning Metall",r:11,e:"⭕",c:"#1e293b",tags:["verkstad","bygg"],
p:"Bi-Metal konstruktion — HSS skäreggar med 8% kobolt svetsade på fjäderstålskropp. Kombinerar koboltens slitstyrka i skäret med fjäderstålets flexibilitet i kroppen, vilket ger både livslängd och brottsäkerhet. Fungerar i trä, plåt upp till 3 mm, plast, gipsskiva och mjukare metaller. 14-152 mm diameter täcker allt från elinstallation till ventilationsgenomföringar. Universalfäste passar alla standardiserade borrfästen (Weldon/3/8\" chuck).",
sp:["✅ Bi-Metal: HSS skär + fjäderstål kropp","✅ 8% kobolt i skäreggen","✅ Trä + plåt (upp till 3mm) + plast + gips","✅ 14-152 mm diameter","✅ Universalfäste (Weldon/3/8\")","✅ Bryter sällan pga flexibilitet","✅ Sats med centrerborr + utkastare"],
discovery:"Borrar ni många genomföringar i plåtskåp eller träpaneler?",
di:[],
pr:"Kontakta",fm:["Styckvis","Sats 6 st","Sats 11 st"]},

{id:"gangtapp",n:"Gängtappar HSS Sats",cat:"Skärande Borrning Metall",r:11,e:"🔧",c:"#334155",tags:["verkstad"],
p:"M3-M12 eller M3-M16 i satser med 3-stegs gängning (förtapp för grovgängning, mellantapp för finjustering, sluttapp för exakt passform). HSS-stål ger rätt balans mellan hårdhet och seghet så tapparna bryter inte i hålet — ett av de värsta scenarierna i verkstan. Perfekt för reparationer där gängor dragits upp, och för att gänga nya hål i egen konstruktion. Förvaringslåda med gängtapphållare kan köpas som tillval.",
sp:["✅ HSS-stål — rätt hårdhet + seghet","✅ 3-stegs gängning (för+mellan+slut)","✅ M3-M12 (18 delar) eller M3-M16 (27)","✅ Även NPT och BSP finns","✅ Förvaringslåda inkluderad","✅ Gängtapphållare som tillval","✅ Bryter sällan i hålet"],
discovery:"Gängar ni mycket i stål, eller främst i aluminium?",
di:[],
pr:"Satsvis",fm:["M3-M12 (18 delar)","M3-M16 (27 delar)"]},

// ══ 12. VERKTYG ══
{id:"gangsats",n:"Gängsats Mannesmann 110 delar",cat:"Verktyg",r:12,e:"🔩",c:"#334155",tags:["verkstad"],
p:"Tyskt Mannesmann från Remscheid — en av Tysklands äldsta verktygstillverkare med över 100 års historia. 110 delar komplett, M2-M18 gängområde, 70 gängtappar (35 förtappar + 35 sluttappar) plus gängsnitt, gängkloppshållare, gängkloppar och tappadaptrar. HSS-stål genomgående och 10 års garanti. Värd 3000-3500 kr i handeln — vi ger bort den GRATIS vid beställning av 2x25L spolarvätska som introduktionskampanj.",
sp:["✅ Tyskt Mannesmann (100+ år historia)","✅ 110 delar komplett sats","✅ M2-M18 gängområde","✅ 70 gängtappar (förtapp + sluttapp)","✅ HSS-stål genomgående","✅ 10 års garanti","✅ Värd 3000-3500 kr","✅ GRATIS vid 2x25L spolarvätska"],
discovery:"Vilken gängsats har ni i verkstan idag, och vad saknas av storlekar?",
di:[],
pr:"GRATIS vid kampanj",fm:["Komplett sats"]},

{id:"handverktyg",n:"Handverktyg & Väskor",cat:"Verktyg",r:12,e:"🛠️",c:"#334155",tags:["verkstad","bygg"],
p:"Nyckelsatser, hylsor, skruvmejslar och tänger i Cromvanadin-stål — industristandard för handverktyg som ska hålla. Verktygsväska med 94 delar ingår vid etablering av samarbete som introduktionsgåva, 108 delar för större kundföretag. Magnetiska skruvmejsel-spetsar håller skruven på plats vid montering, 2-komponent ergonomiska handtag minskar belastningen på handen. Kan byggas som kitt efter vad ni saknar — skicka lista så offererar vi.",
sp:["✅ Cromvanadin-stål (industristandard)","✅ 94-delars väska vid samarbete","✅ 108-delars vid större köp","✅ Magnetiska skruvmejsel-spetsar","✅ 2-komp ergonomiska handtag","✅ Skräddarsys efter ert behov","✅ Hela verktygsbilar kan byggas"],
discovery:"Vad saknas mest i verkstan just nu?",
di:[],
pr:"Väska ingår",fm:["Satser"]},

{id:"sagblad",n:"Mandrex Tigersågblad",cat:"Verktyg",r:12,e:"🪚",c:"#64748b",tags:["verkstad","bygg"],
p:"Made in Germany med 9 typer för alla material — 3X Fastcut (8% kobolt, trippelsidig tandning för stål), Multicut (universal), Steelcut (plåt), Hardcut (härdat), Woodcut (trä), Toughcut (rostfritt), Multicut Varia, Multicut Renovering (spikar i trä), Ezygrind (tegel/betong). Universalskaft passar alla tigersågar på marknaden: AEG, Bosch, Makita, Milwaukee, DeWalt. Säljs i 2-packs-förpackning för praktisk användning.",
sp:["✅ Made in Germany — Mandrex","✅ 9 typer täcker ALLA material","✅ 3X Fastcut = 8% kobolt + trippelsidig","✅ Universalskaft (AEG/Bosch/Makita/etc)","✅ Trä/plåt/sten/diamant/rostfritt/härdat","✅ Säljs i 2-pack","✅ Namnet 'Multicut Renovering' = spikar i trä OK"],
discovery:"Vilka material jobbar ni mest i — trä, plåt, betong eller blandat?",
di:[{q:"Vilka material?"}],
pr:"Se prislista",fm:["Diverse (2st förp.)"]},

{id:"brandsack",n:"Brandsläckare",cat:"Verktyg",r:12,e:"🧯",c:"#ef4444",tags:["verkstad"],
p:"ABC-pulver 6 kg är standarden för verkstad och fordon — släcker A (trä/papper), B (vätska/olja) och C (gas) i en och samma släckare. Årlig kontroll är lagkrav enligt SS 3656 och byte vart 5:e år oavsett om den använts eller inte. Vi levererar och kopplar upp kontrollfirma (SVEBRA) så du slipper boka själv — påminnelse skickas automatiskt. CO2-släckare för elrum och serverhallar finns också i sortimentet.",
sp:["✅ ABC-pulver 6 kg — verkstad/fordonsstandard","✅ SS 3656 svensk norm","✅ Släcker trä/vätska/gas i en","✅ Årlig SVEBRA-kontroll (lagkrav)","✅ Byte vart 5:e år (oavsett användning)","✅ Automatiska påminnelser","✅ CO2 finns för elrum"],
discovery:"Hur många brandsläckare har ni i lokal och fordon, och när kontrollerades de senast?",
di:[],
pr:"Kontakta",fm:["Diverse"]},
];

// Kundtyper
const CTYPES=[
{id:"verkstad",n:"🔧 Verkstad",ps:["sprayer","brake","smorjfett","motorolja","hydraulolja","kapskivor","handskar","ergotec","vatservetter","bamse","skarvatska","bromsvatska","hssbor","koboltbor"]},
{id:"svetsare",n:"⚡ Svetsare",ps:["kapskivor","slipskivor","svetshandske","svetshjalm","svetsmaskin","elektroder","migsvetstrad","rostfri_trad","alutrad","skyddsgas_argon","slipmedel_svets","sprayer","brake","visionpro"]},
{id:"åkeri",n:"🚛 Åkeri",ps:["spolar","glykol","adblue","motorolja","hydraulolja","vaxellolja","bromsvatska","handskar","aquaguard","vatservetter","citr","skumglans","starthjalp"]},
{id:"bygg",n:"🏗️ Bygg",ps:["handskar","ergotec","ducavinter","kapskivor","sprayer","understall","strumptjock","algfasad","hydraulolja","kompressorolja","hssbor","halsag","stegbor"]},
{id:"skog",n:"🌲 Skog",ps:["kedja","motorsagolja","biohydraul","handskar","foamcut","sprayer","understall","strumptjock"]}
];

// SNI-branscher (V9.6)
const BRANCHES=[
{id:"uthyr_bygg_forare",sni:"43.99",n:"🏗️ Uthyrning bygg/anläggning MED förare",
desc:"Företag som hyr ut maskiner inkl. operatör. Slits hårt, behöver förbrukning + smörjning.",
ps:["spolar","adblue","hydraulolja","biohydraul","motorolja","smorjfett","fettspruta","handskar","ergotec","aquaguard","ducavinter","starthjalp","vatservetter","led","induktion"]},

{id:"uthyr_bygg",sni:"77.32",n:"🚜 Uthyrning bygg/anläggning UTAN förare",
desc:"Hyresflotta — maskinerna måste alltid fungera, snabba reparationer + rengöring mellan kunder.",
ps:["hydraulolja","biohydraul","smorjfett","fettspruta","bamse","prickbort","skumglans","handskar","aquaguard","kapskivor","rost","allround","brake","led","starthjalp"]},

{id:"uthyr_diverse",sni:"77.39",n:"📦 Uthyrning diverse maskiner/utrustning",
desc:"Blandad uthyrning — allt från byggtorkar till liftar. Behöver brett sortiment löpande.",
ps:["hydraulolja","smorjfett","bamse","handskar","ergotec","perfhandsken","kapskivor","vatservetter","led","sprayer","brake","rost","allround","kont","bromsvatska"]},

{id:"uthyr_bat",sni:"77.34",n:"⛵ Uthyrning fartyg och båtar",
desc:"Marin miljö — vattentålig utrustning, saltvatten-resistenta produkter, bio-kem krävs.",
ps:["biohydraul","algfasad","skumglans","handskar","aquaguard","vatservetter","rost","kont","citr","glas","vegavfett","led"]},

{id:"uthyr_jordbruk",sni:"77.31",n:"🚜 Uthyrning jordbruksmaskiner",
desc:"Traktorer + skördemaskiner — universella oljor (UTTO), smörjfett mot kyla, rost på redskap.",
ps:["motorolja","hydraulolja","vaxellolja","smorjfett","fettspruta","adblue","spolar","glykol","rost","handskar","perfhandsken","starthjalp","led"]},

{id:"uthyr_lastbil",sni:"77.12",n:"🚛 Uthyrning lastbilar/tunga fordon",
desc:"Tung trafik — AD-Blue + motorolja är livlina, kem-avfettning dagligen, snabbstart vintertid.",
ps:["adblue","motorolja","spolar","glykol","vaxellolja","bromsvatska","bamse","prickbort","skumglans","aquaguard","vatservetter","starthjalp","tjar"]},

{id:"gronytor",sni:"81.30",n:"🌿 Skötsel grönytor",
desc:"Parkförvaltning och fastighetsskötsel — gräsklippare, motorsågar, rensare, bio-olja krav.",
ps:["motorsagolja","biohydraul","kedja","handskar","foamcut","perfhandsken","understall","strumptjock","algfasad","bamse","led","starthjalp"]},

{id:"drivning",sni:"02.20",n:"🪓 Drivning (skogsavverkning)",
desc:"Avverkning med skördare/skotare — bio-hydraulik lagkrav, motorsåg-olja, vatten/oljeresistenta handskar.",
ps:["biohydraul","motorsagolja","kedja","smorjfett","fettspruta","aquaguard","foamcut","perfhandsken","understall","strumptjock","handskar","induktion","starthjalp"]}
];

// Invändningar
const OBJ=[
{q:"Vi har redan leverantör",a:"Perfekt — vi kompletterar med det de inte har. Testa en handske!",w:"Tala inte illa"},
{q:"Skicka mejl",a:"Mejl hamnar bland hundra. Testpaket — 2 min att utvärdera?",w:"Bara maila"},
{q:"Inte intresserad",a:"De flesta säger så innan de sett. Köper ni handskar nånstans?",w:"Ge upp"},
{q:"Ingen budget",a:"Budget för förbrukningsvaror har ni redan — ni testar en produkt ni redan köper.",w:"Acceptera"},
{q:"Ring i augusti",a:"Skickar varuprov nu — du testar, vi stämmer av i augusti!",w:"Bara boka om"},
{q:"Inte beslutsfattare",a:"Vem bestämmer om inköp? Jag ringer rätt person.",w:"Avfärda"},
{q:"Får inte ta emot gåvor",a:"Inga gåvor — varuprover för utvärdering. Som Würth-tester.",w:"Insistera gåva"},
{q:"Vi har ramavtal",a:"Ramavtal täcker inte allt. Specifikt på handskar/kem? Komplettera!",w:"Bryta ramavtal"},
{q:"Skicka prislista",a:"Vilka 3 produkter mest? Skräddarsyr offert.",w:"Generisk PDF"},
{q:"Vi köper lokalt",a:"Vi sitter i Skövde — mer lokalt blir det inte!",w:"Argumentera"},
{q:"Låter för bra",a:"18 000 kunder, Skövde sedan 2017. Ingen hake.",w:"Bli defensiv"},
{q:"Vad är haken?",a:"Haken: vi räknar med att du gillar det. Inget avtal.",w:"Undvika"},
{q:"Har inte tid",a:"45 sek: vi levererar handskar, kem, verktyg. Vilken adress?",w:"Prata längre"},
{q:"Nöjda med leverantör",a:"Inte ersätta — vi är back-up som alltid har grejerna.",w:"Attackera"},
{q:"Tionde som ringer",a:"Skillnaden: jag ber inte köpa. Testpaket, du bestämmer.",w:"Ignorera"},
{q:"Ring chefen",a:"Vad heter chefen? Kan jag nämna att vi pratat?",w:"Inte ta namn"},
{q:"Bara huvudleverantörer",a:"Fortsätt! Vi kompletterar — det lilla varje vecka.",w:"Dag 1 huvud"},
{q:"För dyrt",a:"Jämfört med vad? Totalkostnad med leverans = billigare.",w:"Sänk direkt"},
{q:"Testade er förut",a:"Vad funkade inte? Vi gjort om en hel del.",w:"Förneka"},
{q:"Ska tänka",a:"Vad specifikt? Kanske jag kan hjälpa med info?",w:"Bara okej"},
{q:"Kör Biltema/Jula",a:"Levererar till dörren, faktura, bättre löpande.",w:"Tala illa"},
{q:"Vi är för små",a:"Perfekt! Exakt sådana vi jobbar med — 5-20 anställda.",w:"Köp mer"},
{q:"Litar inte telefonsäljare",a:"Köper det. Därför vill jag komma ut. En kvart?",w:"Bli kränkt"},
];

// Skämt
const JOKES=[
{cat:"🎤 Öppning",items:["Sitter du i grävarn?","Brödfödan ska ju in oavsett tid och väder!","Femte växeln!","Hoppas jag inte ringer mitt i fikat","Ännu en telefonförsäljare — men trevligaste idag!","Stör mitt i nåt viktigt? Typ googla semesterresor?"]},
{cat:"😅 Självdiss",items:["Min chef sa jag ska bli jobbig — jag gör mitt bästa!","Inget är gratis — men det här kommer nära","Lovar att inte ringa igen... förrän om 2 månader","Skövdes trevligaste telefonförsäljare"]},
{cat:"🎬 Avslut",items:["Svetsmaskin också va? Nej tänkte väl det!","Ska jag skicka Tesla? Skämt... eller?","Verktygsvagn 339 delar på det? Om du inte vill?"]},
{cat:"🔄 Comeback",items:["Bra! Testa handskarna — skämta mer nästa gång","Roligare än förra kunden — han la bara på","Den sparar jag!"]},
{cat:"⏰ Stressad",items:["30 sekunder, lovar","Kortare än reklamfilm","Halv minut bara"]},
];

// Status pipeline
const STATUSES=[
{id:"ny",l:"🟡 Ny kontakt",c:"#f59e0b"},
{id:"skickad",l:"📦 Skickad",c:"#3b82f6"},
{id:"uppfoljning",l:"📞 Uppföljning",c:"#8b5cf6"},
{id:"order",l:"✅ Första order",c:"#10b981"},
{id:"aterkommande",l:"🔄 Återkommande",c:"#059669"},
{id:"forlorad",l:"❌ Förlorad",c:"#6b7280"},
];
